### ISSUE TITLE
When use the Simple View , there has an error: Call to undefined method ::start()

### ISSUE THREAD

**Issue by lujunjie521** [phalcon/cphalcon#12330] opened 2016-10-17 09:44 UTC
in the index.php, i register two module:
    $application->registerModules(
        array(
            'admin'  => array(
                'className' => 'Multiple\Admin\Module',
                'path'      => '../apps/admin/Module.php',
            ),
            'api' => array(
                'className' => 'Multiple\Api\Module',
                'path'      => '../apps/api/Module.php',
            ),
        )
    );

in the api/Module.php, i set the simple view 
 public function registerServices(DiInterface $di){
  // Registering the view component
        $di->set('view', function () {
            $view = new SimpleView();
            $view->setViewsDir('../templet/front/');
            return $view;
        },true);
}

but when i use call the api module, the error is  Call to undefined method ::start()

**Comment by Jurigag** [comment] 2016-10-17 09:53
More info ? OS, php version, phalcon version etc ? Follow issue template pls.

**Comment by sergeyklay** [comment] 2016-10-18 23:30
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Closed by sergeyklay** 2016-10-18 23:30 UTC
Labels: Need information, Need script to reproduce

**Comment by lujunjie521** [comment] 2016-10-21 07:25
OS:centos 7
php:7.0.11
phalcon version:3.0.1
trace:Call to undefined method SHO ::start() ; only this

**Comment by Jurigag** [comment] 2016-10-21 07:27
There is just no such method in simple view. Simple view is not replacement for full view.

**Comment by Ultimater** [comment] 2017-09-07 06:31
I'm getting this issue on Phalcon 3.2.2 with a lightweight multi-module structure.  

Below is a section from my ModuleBase.php:
```
    public function registerServices(\Phalcon\DiInterface $di)
    {
        extract($this->config);
        $di->set('dispatcher', function() use ($ns){
            $dispatcher = new Dispatcher();
            $dispatcher->setDefaultNamespace("$ns\\Controller");
            return $dispatcher;
        });
        $di->set('view', function() use ($dir){
            $view = new \Phalcon\Mvc\View\Simple();
            $view->setViewsDir(__DIR__ . "/views/");
            return $view;
        });

    }
```
My ModuleBase above contains a class and implements Phalcon\Mvc\ModuleDefinitionInterface.

All my modules are written extend it.  
Here is my `/modules/Pages/Module.php`:  
```
<?php
namespace Ultimater\Pages;
class Module extends \ModuleBase
{
    protected $config = ['ns'=>__NAMESPACE__,'dir'=>__DIR__];
}
```
Here is my `/modules/AjaxApi/Module.php`: 
```
<?php
namespace Ultimater\AjaxApi;
class Module extends \ModuleBase
{
    protected $config = ['ns'=>__NAMESPACE__,'dir'=>__DIR__];
}
```
All my modules are built like this, differing only in their namespace and extending my module base.

My application is booted like so:  
```
class Application extends \Phalcon\Mvc\Application
{
    protected function _registerServices()
    {
       require dirname(__DIR__).'/config/services.php';
    }

    public function main()
    { 
        // There are my modules.
        $modules=['Pages','AjaxApi','Error'];
        $toRegister = [];
        foreach($modules as $module)
        {
            $toRegister[$module]=[
                'className'=>'Ultimater\\'.$module.'\\Module',
                'path' => realpath(dirname(__DIR__) . '/modules/'.$module.'/Module.php')
            ];
        }
        $this->registerModules($toRegister);
        $this->_registerServices();   
        echo $this->handle()->getContent();
    }
}
```

then finally my index.php file runs:  
```
$application = new Application();
$application->main();
```
which invokes the Application class in my previous snippet




My application was working great with:
```
        $di->set('view', function() use ($dir){
            $view = new \Phalcon\Mvc\View();
            $view->setViewsDir(__DIR__ . "/views/");
            return $view;
        });
```

But then decided to re-organize my views like so:  
```
        $di->set('view', function() use ($dir){
            $view = new \Phalcon\Mvc\View\Simple();
            $view->setViewsDir(__DIR__ . "/views/");
            return $view;
        });
```
This results in my application producing an unexpected error:

```
RuntimeException

Call to undefined method ::start()
```
I believe this is caused by \Phalcon\Mvc\Application trying to call "start()" on the view, not checking what type of view it is, whether it even has the "start" method as previously pointed out.


I was able to workaround this issue by doing:  
```
class SimpleView extends \Phalcon\Mvc\View\Simple
{
    public function start(){
    }
    }
}
```
followed by:  
```
        $di->set('view', function() use ($dir){
            $view = new SimpleView();
            $view->setViewsDir(__DIR__ . "/views/");
            return $view;
        });
```
I believe Phalcon should be checking if a "start" method exists before trying to call it.

**Comment by Ultimater** [comment] 2017-09-07 06:41
Meant to include a link to https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/application.zep#L276

**Comment by Ultimater** [comment] 2017-09-07 06:52
Alright, I tracked this down to ImplicitView:

		/**
		 * Start the view component (start output buffering)
		 */
		if implicitView === true {
			view->start();
		}

and

				/**
				 * Finish the view component (stop output buffering)
				 */
				if implicitView === true {
					view->finish();
				}

This fixes it:  
```
$application = new Application();
$application->useImplicitView(false);
$application->main();
```
If anything, I think Phalcon should be outputting a more friendly error that mentions ImplicitViews if the start method isn't found on the view.
