### ISSUE TITLE
can not delete cookie successfully

### ISSUE THREAD

**Issue by wangshibiaoFlytiger** [phalcon/cphalcon#11780] opened 2016-05-12 08:56 UTC
In my controller, I call the api function failed: 
$this->cookies->delete($key)
the delete function return false, but give no reason.

**Comment by sergeyklay** [comment] 2016-08-13 08:29
@wangshibiaoFlytiger Could you please provide script to reproduce? Provide the way in which do you write cookies. Phalcon, PHP, OS version

**Comment by sergeyklay** [comment] 2016-09-30 10:08
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Closed by sergeyklay** 2016-09-30 10:08 UTC
Labels: Need information, Need script to reproduce
