### ISSUE TITLE
Syntax error when parsing sql

### ISSUE THREAD

**Issue by vGhost2000** [phalcon/cphalcon#9925] opened 2015-03-10 13:40 UTC
I use Postgresql db:

Syntax error, unexpected token FROM, near to ' event_date) = 2015', when parsing: SELECT * FROM \kernel\Models\Organizer where EXTRACT(year FROM event_date) = 2015 (81)

```php
$var = \Phalcon\Mvc\Model\Query\Lang::parsePHQL("
    SELECT
        *
    FROM
        \\kernel\\Models\\Organizer
    WHERE
        EXTRACT(year FROM event_date) = 2015
");
```

OR

Syntax error, unexpected token FROM, near to ' event_date) = 2015 ', when parsing: SELECT [kernel\Models\Organizer].* FROM [kernel\Models\Organizer] WHERE  EXTRACT(year FROM event_date) = 2015

```php
$parameters = array(
    'conditions' => ' EXTRACT(year FROM event_date) = 2015 ',
);

$res =  Organizer::find($parameters);
```

**Comment by golovanov** [comment] 2015-03-12 13:28
PHQL is not SQL

**Comment by vGhost2000** [comment] 2015-03-12 13:34
I know. But \Phalcon\Mvc\Model\Query\Lang - use to parse query.
How i can push this query into database?

**Comment by vGhost2000** [comment] 2015-03-13 15:10
> RAW-SQL 
It works, thanks.
But, i think it's not right way.

**Comment by andresgutierrez** [comment] 2015-04-07 20:35
Closed as not a bug

**Closed by andresgutierrez** 2015-04-07 20:35 UTC
