### ISSUE TITLE
[BUG]: Query builder trims the word 'not' from column name?

### ISSUE THREAD

**Issue by colinberlinger** [phalcon/cphalcon#15443] opened 2021-04-30 07:35 UTC
**Describe the bug**
When querying a column name that begins with the string 'not' (eg. notification_date), the 'not' seems to be trimmed from the name, resulting in a column not found error.

**To Reproduce**

```php
<?php

include 'vendor/autoload.php';

use Phalcon\Di\FactoryDefault;
use Phalcon\Mvc\Model;
use Phalcon\Db\Adapter\Pdo\Mysql;
use Phalcon\Mvc\Model\Query;

$di = new FactoryDefault();
$di->setShared('myConnection', function() {
    return new Mysql([
        'host' => 'localhost',
        'username' => 'root',
        'password' => 'secret',
        'dbname' => 'mydatabase',
    ]);
});

class MyModel extends Model
{
    public function initialize(): void
    {
        $this->setConnectionService('myConnection');
        $this->setSource('my_table');
    }
}

$query = new Query("select * from MyModel where notification_date = '2021-04-29 07:14:22'", $di);
$query->execute();
```

**Output**

```
PHP Fatal error:  Uncaught Phalcon\Mvc\Model\Exception: Column 'ification_date' doesn't belong to any 
of the selected models (1), when preparing: select * from MyModel where notification_date = '2021-04-29 07:14:22' in /var/www/test.php:30
Stack trace:
#0 [internal function]: Phalcon\Mvc\Model\Query->_getQualified(Array)
#1 [internal function]: Phalcon\Mvc\Model\Query->_getExpression(Array, true)
#2 [internal function]: Phalcon\Mvc\Model\Query->_getExpression(Array)
#3 [internal function]: Phalcon\Mvc\Model\Query->_prepareSelect()
#4 [internal function]: Phalcon\Mvc\Model\Query->parse()
#5 /var/www/test.php(30): Phalcon\Mvc\Model\Query->execute()
#6 {main}
  thrown in /var/www/test.php on line 30
```

**Expected behavior**
Query should execute normally and return a result.

**Details**
 - Phalcon version: 4.1.2
 - PHP Version: 7.3
 - Operating System: macOS Big Sur 11.3
 - Installation type: Compiling from source
 - Database: Mysql (Pdo)

**Additional context**

- Adding an extra 'not' to the column name in the query (eg. notnotification_date), results in the query executing normally.
- Problem occurs with all column types.
- Column names beginning with other reserved keywords (eg. and, or, like, select, drop etc) don't seem to have this problem.

**Comment by Jeckerson** [comment] 2021-05-04 11:25
Duplicate of #14641

**Closed by Jeckerson** 2021-05-04 11:25 UTC
Labels: duplicate
