### ISSUE TITLE
[2.0.3] It's not possbile to catch errors. 

### ISSUE THREAD

**Issue by salarmehr** [phalcon/cphalcon#10540] opened 2015-06-24 13:25 UTC
I a model is reference by some foreign keys, its not possible to display appropriate error message to user. The executions exits with 
`````
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign
 key constraint fails (`db`.`robots`, CONSTRAINT `FK_entity_foo` FOREIGN KEY (`type`) REFERENCES
 `parent_table` (`id`))
`````
 message.
~~~~~
$robot = Robots::findFirst(11);
if ($robot != false) {
    if ($robot->delete() == false) {
        echo "Sorry, we can't delete the robot right now: \n";
        foreach ($robot->getMessages() as $message) {
            echo $message, "\n";
        }
    } else {
        echo "The robot was deleted successfully!";
    }
}

**Comment by andresgutierrez** [comment] 2015-06-24 14:24
Duplicate of #10541

**Closed by andresgutierrez** 2015-06-24 14:24 UTC
