### ISSUE TITLE
[BUG]: Volt is defined and array in 

### ISSUE THREAD

**Issue by ismail0234** [phalcon/cphalcon#14816] opened 2020-02-05 12:49 UTC
Questions? Forum: https://phalcon.link/forum or Discord: https://phalcon.link/discord

**Describe the bug**
Using these two together will give the wrong result.

> Provide minimal script to reproduce the issue

```volt
// WRONG Result:
{% if categoryIds is defined AND category['id'] in categoryIds %}
    checked
{% endif %}

// Correct Result:
{% if categoryIds is defined AND (category['id'] in categoryIds) %}
    checked
{% endif %}
```

**Expected behavior**

```php
// WRONG RESULT
<?php if ($this->isIncluded(isset($categoryIds) && $category['id'], $categoryIds)) { ?>
   checked
<php } ?>

// Correct RESULT
<?php if (isset($categoryIds) && $this->isIncluded($category['id'], $categoryIds)) { ?>
   checked
<php } ?>
```

**Screenshots**

**Details**
 - Phalcon version: v3.4.5
 - PHP Version: 7.3
 - Operating System: Windows
 - Installation type: installing via package manager
 - Zephir version (if any): Latest
 - Server: FASTCGI

**Comment by Jeckerson** [comment] 2020-02-07 09:17
Confirmed, here is screenshot of generated code from volt

![image](https://user-images.githubusercontent.com/3289702/74016613-9dcd1880-498a-11ea-8f1b-b92d9b7f7d68.png)

**Comment by niden** [comment] 2020-03-10 18:34
This needs work on the PHQL parser since the right part after the `&&` is not parsed on its own.

For now the workaround with parentheses works but the suggested syntax should work also.

**Comment by sergeyklay** [comment] 2020-03-26 10:11
Fixed in 4.0.x branch. Thank you for the report, and for helping us make Phalcon better.

**Closed by sergeyklay** 2020-03-26 10:11 UTC
Labels: 4.0.6, bug, status: medium
