### ISSUE TITLE
Error in params for Relation on Models

### ISSUE THREAD

**Issue by gtux** [phalcon/cphalcon#10442] opened 2015-05-29 18:00 UTC
Hi, 

  I want to restrict one relationship over two models with one business logic. Because in documentation not have any reference for the options of relation, I have to read the source code in order to learn to use.

I did this:

```php
// model.zep [3338]:  
protected function hasMany(var fields, string! referenceModel, var referencedFields, options = null) -> <Relation>
{
	return (<ManagerInterface> this->_modelsManager)->addHasMany(this, fields, referenceModel, referencedFields, options);
}
```

```php
// model/manager.zep [831]: 
/**
 * Create a relationship instance
 */
let relation = new Relation(
	Relation::HAS_MANY,
	referencedModel,
	fields,
	referencedFields,
	options
);
```

```php
// model/relation.zep [73]:

public function __construct(type, string! referencedModel, var fields, var referencedFields, var options = null)
{
	let this->_type = type,
	this->_referencedModel = referencedModel,
	this->_fields = fields,
	this->_referencedFields = referencedFields,
	this->_options = options;
}
```

then, in relation class I see this code, that not exists in documentation:

```php
// model/relation.zep [181]: 

/**
 * Returns parameters that must be always used when the related records are obtained
 *
 * @return array
 */
public function getParams()
{
	var options, params;
	let options = this->_options;
	if typeof options == "array" {
		if fetch params, options["params"] {
			if params {
				return params;
			}
		}
	}
	return false;
}
```

So, I initialize my model like this:

```php
// model Clientes.php
        $this->hasMany(
            'id_cliente',
            'Inngresa\Models\Personas',
            'id_cliente',
            array(
                'foreignKey' => array('action' => Relation::ACTION_CASCADE),
                'alias' => 'personas',
                'params' => array(
                    'conditions' => 'activo = 1',
                )
            )
        );
```

I try to get personas like this:

```php
$cliente = Clientes::findFirst($id);
$personas = $cliente->getPersonas();
```

But, the filter that I setup does not works! 

I think the bug is at getRelationRecords method of Manager, lines 239 - 253:

```php
/**
 * We don't trust the user or data in the database so we use bound parameters
 * Create a valid params array to pass to the find/findFirst method
 */
let findParams = [
	join(" AND ", conditions),
	"bind"      : placeholders,
	"di"        : record->{"getDi"}()
];

if typeof parameters == "array" {
	let findArguments = array_merge(findParams, parameters);
} else {
	let findArguments = findParams;
}
```

On my initialization, that seems correct, I have a params array, so then I do $cliente->getPersonas(), in source code from line 111 to 150 get this:

```php
 // extraParameters = array('conditions' => 'activo = 1')
let parameters = extraParameters;
// preConditions here is still null
```

So then reach the line 250, the result of array merge is the condition that I initialize for hasMany on model is ignored, that is because the variable findParams have a condition on key 0, so other conditions is ignored.

Maybe for fix this, at lines 214 to 218 is needed evaluate the variable called extraParameters in order to find conditions to populate it here, so in the line 250 already have the conditions that was setup.

```php
if preConditions !== null {
	let conditions = [preConditions];
} else {
	let conditions = [];
}
```

I hope may I make me clear. Sorry my bad English

**Comment by andresgutierrez** [comment] 2015-05-31 22:35
I've submitted a fix in 2.0.3, can you try again using this version?

**Comment by gtux** [comment] 2015-06-01 15:04
I did update to 2.0.3, but now I have other bug on different model that it does working well, until now.

I got an Exception on this backtrace:

```php
// Model::save
// Model::_preSave:: 1855
let emptyStringValues = metaData->getEmptyStringAttributes(this);
// Metadata::getEmptyStringAttributes::576
let data = this->readMetaDataIndex(model, self::MODELS_EMPTY_STRING_VALUES);
// Metadata::readMetaDataIndex:: 271
if fetch metaData, this->_metaData[key][index] {
	return metaData;
}
```

The error came because the metadata cache file does not generate the 13 index (self::MODELS_EMPTY_STRING_VALUES), I've erased the metadata cache files before run the script.

**Comment by gtux** [comment] 2015-06-01 16:26
In other news, I have the same bug, I have this in my model's initialize method:

```php
// Clientes.php::initialize
        $this->hasMany(
            'id_cliente',
            'Inngresa\Models\Personas',
            'id_cliente',
            array(
                'foreignKey' => array('action' => Relation::ACTION_CASCADE),
                'alias' => 'personas',
                'params' => array(
                    'conditions' => 'activo = 1'
                )
            )
        );
// then on IndexController
$cliente = Clientes::findFirst($id);
$personas = $cliente->getPersonas();
```

here still get the 'activo = 0' persons, on my db.log get:
 
```
SELECT `personas`.`id_persona`, `personas`.`id_cliente`, `personas`.`identificacion`, `personas`.`nombre`, `personas`.`apellido_paterno`, `personas`.`apellido_materno`, `personas`.`fiv`, `personas`.`sexo`, `personas`.`fecha_nacimiento`, `personas`.`sueldo`, `personas`.`caracteristicas`, `personas`.`created`, `personas`.`activo` FROM `personas` WHERE `personas`.`id_cliente` = :0
```

Like you can see, only the id_cliente is filtered.

I did this:
```
1) erase my clone of repository
2) git clone https://github.com/phalcon/cphalcon.git
3) cd cphalcon
4)  git checkout 2.0.x
5) git pull
6) git status
7) cd build/
8) rm -f /usr/lib64/php/5.5/modules/phalcon.so
9) ./install
10) service httpd restart
```

By the way, how can I debug if I modify the zep code? I try but does not work either.

Thanks in advance

**Comment by andresgutierrez** [comment] 2015-06-02 02:29
I can't reproduce the issue, I'm using the following script, and it works fine:

```php
<?php

namespace Some;

use Phalcon\DI,
    Phalcon\Db\Column,
    Phalcon\Mvc\Model,
    Phalcon\Events\Manager as EventsManager,
    Phalcon\Db\Adapter\Pdo\MySQL as Connection,
    Phalcon\Mvc\Model\Manager as ModelsManager,
    Phalcon\Mvc\Model\Metadata\Memory as ModelsMetaData;

$eventsManager = new EventsManager();

$di = new DI();

$connection = new Connection(array(
    "host"     => "localhost",
    "username" => "root",
    "password" => "hea101",
    "dbname"   => "phalcon_test",
));

$connection->setEventsManager($eventsManager);

$eventsManager->attach('db',
    function ($event, $connection) {
        switch ($event->getType()) {
            case 'beforeQuery':
                echo $connection->getSqlStatement(), "\n";
                break;
        }
    }
);

$modelsManager = new ModelsManager();
$modelsManager->setDi($di);
$di['db'] = $connection;
$di['modelsManager'] = $modelsManager;
$di['modelsMetadata'] = new ModelsMetadata();

class Robots extends Model
{
    public function initialize()
    {
        $this->hasMany('id', 'Some\RobotsParts', 'robots_id', [
            'alias' => 'parts',
            'params' => ['conditions' => 'parts_id = 0']
        ]);
    }
}

class RobotsParts extends Model
{

}

$robot = Robots::findFirst();
foreach ($robot->parts as $robotPart) {
    echo $robotPart->id, PHP_EOL;
}
```

Output:

```sql
SELECT IF(COUNT(*) > 0, 1, 0) FROM `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_NAME` = 'robots' AND `TABLE_SCHEMA` = DATABASE()
DESCRIBE `robots`
SELECT `robots`.`id`, `robots`.`name`, `robots`.`type`, `robots`.`year`, `robots`.`datetime`, `robots`.`text` FROM `robots` LIMIT 1
SELECT IF(COUNT(*) > 0, 1, 0) FROM `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_NAME` = 'robots_parts' AND `TABLE_SCHEMA` = DATABASE()
DESCRIBE `robots_parts`
SELECT `robots_parts`.`id`, `robots_parts`.`robots_id`, `robots_parts`.`parts_id` FROM `robots_parts` WHERE (`robots_parts`.`robots_id` = :0) AND (`robots_parts`.`parts_id` = 0)
```

**Comment by gtux** [comment] 2015-06-02 14:09
Hi, I'm trying to make some debug over the code, like the user phalcon recommend (#10456): I build the extension with the command "zephir build", but, when I do this all goes wrong! I'm my log's file I get:

```
// application.log
Exception: [42000] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' , host=xxx.rds.amazonaws.com;dbname=xxx_testfhos' at line 1

// db.log
host=xxxx.rds.amazonaws.com;dbname=xxx_test
```

But when I build with the clasic "cd build && ./install" all works fine. I'm trying to help, but it's strange

**Comment by andresgutierrez** [comment] 2015-06-02 14:47
Try installing from ext/

```bash
cd cphalcon/ext
git checkout 2.0.x
sudo ./install
```

**Comment by gtux** [comment] 2015-06-03 01:04
Hi, I'm trying to debug this strange behavior and run your code in my environment, I did this:

```php
// on cphalcon/mvc/model.zep 
public static function findFirst(parameters = null) -> <Model>
{
        var params, builder, query, bindParams, bindTypes, cache, resultset, hydration, dependencyInjector, manager;
        let dependencyInjector = \Phalcon\Di::getDefault();
        let manager = <ManagerInterface> dependencyInjector->getShared("modelsManager");

echo "parameters "; var_dump(parameters); echo "\n";

      if typeof parameters != "array" {
            let params = [];
            if parameters !== null {
                  let params[] = parameters;
            }
      } else {
            let params = parameters;
      }

      /**
       * Builds a query with the passed parameters
       */
      let builder = manager->createBuilder(params);
      builder->from(get_called_class());

      /**
       * We only want the first record
       */
      builder->limit(1);
      let query = builder->getQuery();      
var_dump(params);
      /**
       * Check for bind parameters
       */
      let bindParams = null, bindTypes = null;
var_dump(bindParams);
      if fetch bindParams, params["bind"] {
            fetch bindTypes, params["bindTypes"];
      }
var_dump(bindParams);

      /**
       * Pass the cache options to the query
       */
      if fetch cache, params["cache"] {
            query->cache(cache);
      }

      /**
       * Return only the first row
      */
      query->setUniqueRow(true);
      /**
       * Execute the query passing the bind-params and casting-types
       */
      let resultset = query->execute(bindParams, bindTypes);

      /**
       * Define an hydration mode
       */
      if typeof resultset == "object" {
                if fetch hydration, params["hydration"] {
                      resultset->setHydrateMode(hydration);
                }
           }

           return resultset;
      }
```

then create a issue-10442.php:

```php
<?php
namespace Gt;

use Phalcon\Events\Manager;
use Phalcon\Di\FactoryDefault;
use Phalcon\Db\Adapter\Pdo\Mysql;
use Phalcon\Mvc\Model\MetaData\Memory;
use Phalcon\Mvc\Model\MetaData\Strategy\Annotations;
use Phalcon\Loader;
use Inngresa\Models\Clientes;

// this script is in /public/tmp
define('BASE_DIR', dirname(realpath(__DIR__.'/../')));
$eventsManager = new Manager();
$di = new FactoryDefault();
// setup connection to db
$connection = new Mysql(array(
    'host' => 'xxx.xxx.us-west-2.rds.amazonaws.com',
    'username' => '',
    'password' => '',
    'dbname' => 'xxx_test'
));
// sets events manager
$connection->setEventsManager($eventsManager);
// callback en beforeQuery
$eventsManager->attach('db', function ($event, $connection) {
    switch ($event->getType()) {
        case 'beforeQuery':
            echo $connection->getSqlStatement(), "\n";
            break;
    }
});
// models manager
$modelsManager = new \Phalcon\Mvc\Model\Manager();
$modelsManager->setDI($di);
// sets services
$di['db'] = $connection;
$di['modelsManager'] = $modelsManager;
$di['modelsMetadata'] = function () {
    $metaData = new Memory(array(
        'metaDataDir' => BASE_DIR. '/data/cache/metadata'
    ));
    $metaData->setStrategy(new Annotations());
    return $metaData;
};
$di['modelsCache'] = function () {

    // Cache data for one day by default
    $frontCache = new \Phalcon\Cache\Frontend\Data(array(
        "lifetime" => 86400
    ));

    // File
    $cache = new \Phalcon\Cache\Backend\File($frontCache, array(
        "cacheDir" => BASE_DIR.'/data/cache/',
        'prefix' => 'inn-'
    ));

    return $cache;
};
// cargo loader
$loader = new Loader();
// registro directorio de modelos
$loader->registerDirs(array(
    BASE_DIR.'/apps/models'
));
// registro namespaces generales
$loader->registerNamespaces(array(
    'Inngresa' => BASE_DIR.'/apps/library/Inngresa',
    'Gt' => BASE_DIR . '/apps/library/Gt',
    'Inngresa\Models' => BASE_DIR.'/apps/models'
));
// registro el loader
$loader->register();
error_reporting(E_ALL);

header('Content-Type: text/plain;charset=UTF-8');
ini_set('error_log', 'syslog');
echo \Phalcon\Version::get(), "\n";

try {
    $cliente = Clientes::findFirst(2);
    $personas = $cliente->getPersonas();
    var_dump(count($personas));
} catch (\Phalcon\Mvc\Model\Exception $e) {
    var_dump($e->getTrace());
}
```

then i run: 
```
[]$ zephir fullclean && zephir build && service httpd restart
```

and this is what i get:

```
2.0.3
parameters int(2)

array(1) {
  [0]=>
  int(2)
}    // var_dump(params)
NULL // var_dump(bindParams)
string(73) "host=xxx.xxx.us-west-2.rds.amazonaws.com;dbname=xxx_test"  // var_dump(bindParams)
// the exception
array(4) {
  [0]=>
  array(4) {
    ["function"]=>
    string(14) "_prepareSelect"
    ["class"]=>
    string(23) "Phalcon\Mvc\Model\Query"
    ["type"]=>
    string(2) "->"
    ["args"]=>
    array(0) {
    }
  }
  [1]=>
  array(4) {
    ["function"]=>
    string(5) "parse"
    ["class"]=>
    string(23) "Phalcon\Mvc\Model\Query"
    ["type"]=>
    string(2) "->"
    ["args"]=>
    array(0) {
    }
  }
  [2]=>
  array(4) {
    ["function"]=>
    string(7) "execute"
    ["class"]=>
    string(23) "Phalcon\Mvc\Model\Query"
    ["type"]=>
    string(2) "->"
    ["args"]=>
    array(2) {
      [0]=>
      string(73) "host=xxx.xxx.us-west-2.rds.amazonaws.com;dbname=xxx_test"
      [1]=>
      NULL
    }
  }
  [3]=>
  array(6) {
    ["file"]=>
    string(56) "/var/www/vhosts/xxx.com/public/temp/issue-10442.php"
    ["line"]=>
    int(85)
    ["function"]=>
    string(9) "findFirst"
    ["class"]=>
    string(17) "Phalcon\Mvc\Model"
    ["type"]=>
    string(2) "::"
    ["args"]=>
    array(1) {
      [0]=>
      int(2)
    }
  }
}
```

I'm really crazy trying to find out when the variable bindParams sets to my dbconnect params.

**Comment by gtux** [comment] 2015-06-03 01:12
When I compile phalcon with this:

```
cd build && ./install && service httpd restart
```
On issue-10442.php I get:

```
2.0.3
SELECT `clientes`.`id_cliente`, `clientes`.`nombre`, `clientes`.`configuracion`, `clientes`.`identificacion`, `clientes`.`id_pais`, `clientes`.`activo`, `clientes`.`hash`, `clientes`.`confirmado`, `clientes`.`apikey`, `clientes`.`created` FROM `clientes` WHERE `clientes`.`id_cliente` = 2 LIMIT 1
SELECT `personas`.`id_persona`, `personas`.`id_cliente`, `personas`.`identificacion`, `personas`.`nombre`, `personas`.`apellido_paterno`, `personas`.`apellido_materno`, `personas`.`fiv`, `personas`.`sexo`, `personas`.`fecha_nacimiento`, `personas`.`sueldo`, `personas`.`caracteristicas`, `personas`.`created`, `personas`.`activo` FROM `personas` WHERE `personas`.`id_cliente` = :0
int(8)
```

Like you see, do not filter with 'activo = 1' constraint on initialize method.

**Comment by andresgutierrez** [comment] 2015-06-03 01:13
@gtux Installation from build is outdated, did you compile from ext/ ?

**Comment by gtux** [comment] 2015-06-03 01:14
I'll do it right now

**Comment by gtux** [comment] 2015-06-03 01:29
I did this:
```
cd ext && ./install && service httpd restart
```

And I get this:

```
2.0.3
array(4) {
  [0]=>
  array(4) {
    ["function"]=>
    string(14) "_prepareSelect"
    ["class"]=>
    string(23) "Phalcon\Mvc\Model\Query"
    ["type"]=>
    string(2) "->"
    ["args"]=>
    array(0) {
    }
  }
  [1]=>
  array(4) {
    ["function"]=>
    string(5) "parse"
    ["class"]=>
    string(23) "Phalcon\Mvc\Model\Query"
    ["type"]=>
    string(2) "->"
    ["args"]=>
    array(0) {
    }
  }
  [2]=>
  array(4) {
    ["function"]=>
    string(7) "execute"
    ["class"]=>
    string(23) "Phalcon\Mvc\Model\Query"
    ["type"]=>
    string(2) "->"
    ["args"]=>
    array(2) {
      [0]=>
      string(73) "host=xxx.xxx.us-west-2.rds.amazonaws.com;dbname=xxx_test"
      [1]=>
      NULL
    }
  }
  [3]=>
  array(6) {
    ["file"]=>
    string(56) "/var/www/vhosts/xxx.com/public/temp/issue-10442.php"
    ["line"]=>
    int(85)
    ["function"]=>
    string(9) "findFirst"
    ["class"]=>
    string(17) "Phalcon\Mvc\Model"
    ["type"]=>
    string(2) "::"
    ["args"]=>
    array(1) {
      [0]=>
      int(2)
    }
  }
}
```

**Comment by andresgutierrez** [comment] 2015-06-03 01:44
I can't execute your example because it has external dependencies that are not posted in the example.

**Comment by gtux** [comment] 2015-06-03 16:09
Hi, It's impossible to get right, today I did this:

1) Uninstall php and all this modules and configurations. I was installed php 5.5
2) Install php 5.6 and configure to minimal to work.
3) Checkout 2.0.x branch.
4) Build phalcon with: zephir build -> shows the dbconnect params con findFirst
5) Build phalcon with: ext/install -> same above
6) Build phalcon with: build/install -> the bug persists, it do not filter with params setup on relationship.

Sincerely I had to rollback and install phalcon 2.0.2 stable because the problems are strange. At this afternoon will try to make a new instance on Amazon to re-create my environment and also try with your code.

**Comment by andresgutierrez** [comment] 2015-06-03 19:56
@gtux Just added a fix in Zephir, could you please download changes from zephir and phalcon (2.0.x branch) and try again?

**Comment by gtux** [comment] 2015-06-04 16:04
This is what I did:

1) Create another new instance on AWS.
2) Build 2.0.3 branch and install ALL my environment again.

Only this way, it works!

So, right now, I do not have this issue any more, but not the same history with the others issues :worried:

**Comment by andresgutierrez** [comment] 2015-06-04 16:06
Thanks, I'm closing this

**Closed by andresgutierrez** 2015-06-04 16:06 UTC
Labels: Need script to reproduce
