### ISSUE TITLE
Phalcon\Paginator\Adapter\QueryBuilder total_items wrong value

### ISSUE THREAD

**Issue by KristijanBenkovic** [phalcon/cphalcon#10581] opened 2015-07-01 13:58 UTC
This is my first bug report. I hope I am not missing something.

Here is my source:

```
$paginator = new Phalcon\Paginator\Adapter\QueryBuilder(array(
            "builder"  => $queryBuilder,
            "limit" => 1,
            "page"  => 1
));

$totalItems             = $paginator->getPaginate()->total_items;
$totalPages             = $paginator->getPaginate()->total_pages;
$queryBuilderTotalItems = $queryBuilder->getQuery()->execute()->count();

var_dump($totalItems, $totalPages, $queryBuilderTotalItems, get_class($queryBuilder)); 
```

Output:
```
int 2
int 2
int 6504
string 'Phalcon\Mvc\Model\Query\Builder' (length=31)
```

I except $totalItems would be equals to $queryBuilderTotalItems.

I guess [this](https://github.com/phalcon/cphalcon/blob/master/phalcon/paginator/adapter/querybuilder.zep#L163) is why total_items returns 2 because I have group by in my query.

Is this a bug or expected behaviour?

**Comment by andresgutierrez** [comment] 2015-07-03 04:22
Duplicate of #2411

**Closed by andresgutierrez** 2015-07-03 04:22 UTC
