### ISSUE TITLE
NFR Rename Volt "compiled"

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#13815] opened 2019-02-09 15:53 UTC
Request to remove "compiled" from ``setOptions`` and simply use it like this;
Because eveyone who uses Volt know that this ``setOptions`` are "compiled" :-)

```php
$di->set('view', function() {
  $view = new View();
      $view->setViewsDir('../app/views/');
      $view->registerEngines([
        '.volt' => function($view, $di) {
        $volt = new Volt($view, $di);
          $volt->setOptions([
            'path' => '../app/cache/',  // "compiledPath"
            'extension' => '.html',  // "compiledExtension"
            'separator' => '_',  // "compiledSeparator"
            'stat' => true,
            'always' => true,  // "compileAlways"
          ]);
          return $volt;
        }]);
  return $view;
});
```

I think by now you can guys see that LESS is MORE :-) Its better to have less typed alias, commands and functions. Because who wants to type ``someFunctionNameAgainAndAgain()``

To have backward compability you can simply create alias for this. So everyone who uses "compiled" it will still work, or simply note this in Phalcon changelog that it has been changed like few recent renames of functions you have done :-) Love it!

**Comment by dschissler** [comment] 2019-02-14 23:55
I like it without the alias.  Phalcon v3 was around for a very long time.  I think that it bough the project some leeway to break stuff in v4.  If anything I would emit a warning if the "compiled" key exists and then just remove that warning later in the v4 cycle.

If people can agree that removing the "compiled" level is good then I could do this PR.  I find that what Phalcon really lacks in its issues is a "Sounds good, lets do it".  So issues just sit there maybe in agreement but then nobody does it.  So @niden it would be great if you could get in the habit of "in theory" approving changes.  Of course that doesn't mean you are bound to the implementation.  I have no idea if you would actually accept something or if you are just being kind and tagging it.  So I pretty much just only do stuff that I feel that I can't live without.  Nothing else is worth the uncertainty.

**Comment by niden** [comment] 2019-02-15 03:49
@dschissler I always try to add labels to issues. Aside from the glaring obvious `not a bug` or won't fix`, the RFC one is where we need comments from the community. Anything else pretty much gets a NFR/Enhancement or Bug.

Any of these that fit the workload of the current version are added in the v4 project here:

https://github.com/phalcon/cphalcon/projects/3

Anything that is not, will be introduced in v4.1 etc. I cannot develop more than what the current project has, otherwise we will end up with an alpha version that lasts a while year. The tasks on the project are pretty much heavy with PSR and all that.

If anyone from the community wants to take a stab at any of the NFRs remaining by all means we will not turn it down and will add it in the upcoming release whatever that is.

As for your first comment, for v4 I would do what you mentioned, allow the `compile*` syntax but emit a warning/deprecated and allow also the non prefix.. That and the docs should be a good way to raise awareness for the change

**Comment by dschissler** [comment] 2019-02-15 11:51
@niden Ok.  Is there a way that you can tag things to be done sometime in the 4 series but not specifically in 4.0?  Then I could get a few of them done myself.  That will say over year net you extra time (since you won't have to do it later).  By my assessment you won't be losing much time because I won't be getting involved with the heavy redesigns and so this is the only thing that I would get involved with at this time.

In particular I'm interested in two things; 1) Removing as much general API clunk as possible, 2) improve parts of Phalcon that are locked into inflexibility to the detriment of Perch.

For 1) it would help if all recent requests were marked with something like `4.0` and `4.x`.  Do you get what I mean?  That would give a clear path for me to bang out one or possibly even two of these smaller ones per week.

For 2) Its just a matter of putting code out.  I've found that in some cases creating an issue is almost pointless because nobody understands exactly what I'm trying to do when its presented in abstract terms.  I have put enormous time into something that is basically like a Phalcon -> Perch ~ Symfony -> Laravel.  So I've discovered some things and I need the time to get the code to you.  This v4 alpha window started IMO say six months too late.

**Comment by niden** [comment] 2019-02-24 15:51
This has been addressed

**Closed by niden** 2019-02-24 15:51 UTC
Labels: New Feature Request
