### ISSUE TITLE
[BUG]: form entity isn't passed to validator

### ISSUE THREAD

**Issue by stijn1989** [phalcon/cphalcon#15567] opened 2021-07-01 06:35 UTC
When setting an entity to a form on construction and calling isValid($data), the entity isn't passed to the validator. The only entity that is passed, is the entity that is passed with isValid($data, $entity). But you shouldn't do this, because you already pass this entity to the form on construction.

**To Reproduce**

Person.php
```php
<?php
class Person extends \Phalcon\Mvc\Model
{
    public $name;

    public function validation(): bool
    {
        return $this-validate(new PersonValidator());
    }
}
```

PersonValidator.php
```php
<?php
class PersonValidator extends \Phalcon\Validation
{

    public function __construct()
    {
        parent::__construct([
            'name' => [
                new \Phalcon\Validation\Validator\Uniqueness(['message' => "Person name must be unique!"])
            ]
        ]);
    }

}
```

PersonForm.php
```php
<?php
class PersonForm extends \Phalcon\Forms\Form
{

    public function initalize($entity = null, $options = []): 
    {
        $name = new \Phalcon\Forms\Element\Text('name');
        $name->setLabel('Name');

        $this->add($name);
        $this->setValidation(new PersonValidator());
    }

}
```

> Provide minimal script to reproduce the issue

PersonController.php
```php
<?php
class PersonController extends \Phalcon\Mvc\Controller
{

    public function editAction($name)
    {
        $person = Person::findByName($name);
        $form = new PersonForm($person);

        if($this->request->isPost()) {
            if($form->isValid($this->request->getPost()) {
                $person->save();
                $this->flash->success('Person saved!');
            } else {
                $this->flash->error( implode('<br>', $form->getMessages());
            }
        }

        $this->view->form = $form;
    }

}
```

**Expected behavior**
If you run this edit action and just hit save and **don't change** anything. It should produce the success message **Person saved!**. 
But it doesn't. It gives the error message **Person name must be unique!**.

If you change the isValid() line to the line below, it works.

```php
....
if($form->isValid($this->request->getPost(), $person) {
....
```

**Details**
 - Phalcon version: 4.1
 - PHP Version: 7.4
 - Operating System: Debian
 - Installation type: Installing from PECL.
 - Zephir version (if any):
 - Server: Nginx

**Comment by wurst-hans** [comment] 2021-07-15 04:43
Shouldn't the validator be attachted to field instead?
Try to use `$name->addValidator(new PersonValidator());`

**Comment by stijn1989** [comment] 2021-07-15 05:45
> Shouldn't the validator be attachted to field instead?
> Try to use `$name->addValidator(new PersonValidator());`

No, because you set validators for the field in PeronValidator. It's better to separate validation rules in a class. That way you can use that validation everywhere like in Forms and Models.

**Comment by wurst-hans** [comment] 2021-07-15 06:36
I see. Still, can't reproduce it here on 4.1.0. I've created a validation class and attached it to a form and to the related model. No problems on adding a new (non-existing) `name`

**Comment by stijn1989** [comment] 2021-07-15 06:41
Adding is not a problem because the entity is in TRANSIENT state. Fetch an existing one and don't change the name and submit the form. Then it doesn't validate.

And that's the problem, because the form object doesn't pass his entity to the validation. And the Uniqueness validator checks on the state of the entity.

**Comment by wurst-hans** [comment] 2021-07-15 07:06
BTW: I would use `public function initialize()` instead of overwriting constructor for extended validation class.

But as the problem happens in model validation, does it really depends on form? I mean, form validation passes and in `isValid()` the data is bound to entity. Can you try if this also fails, when getting object from database and `save()` it immediately without using a form?

**Comment by niden** [comment] 2021-08-12 17:02
Resolved in https://github.com/phalcon/cphalcon/pull/15568

**Closed by niden** 2021-08-12 17:02 UTC
Labels: bug, status: unverified
