### ISSUE TITLE
ConstraintViolation 

### ISSUE THREAD

**Issue by karborator** [phalcon/cphalcon#3080] opened 2014-11-26 14:27 UTC
When i try to implement soft delete on model with relation hasOne i get this error:

object(Phalcon\Mvc\Model\Message)[132]
  protected '_type' => string 'ConstraintViolation' (length=19)
  protected '_message' => string 'Record is referenced by model \Modules\Admin\Models\Options\EndpointType' (length=72)
  protected '_field' => string 'endpoint_type' (length=13)
  protected '_model' => null
  protected '_code' => int 0

**Comment by andresgutierrez** [comment] 2015-07-17 01:23
Could you please provide the script to reproduce this issue?

**Comment by sergeyklay** [comment] 2016-09-03 08:26
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Closed by sergeyklay** 2016-09-03 08:26 UTC
Labels: Need script to reproduce
