### ISSUE TITLE
Call to undefined method ::registerautoloaders()

### ISSUE THREAD

**Issue by Niko9911** [phalcon/cphalcon#13346] opened 2018-04-13 13:31 UTC
```
  | Call to undefined method ::registerautoloaders()<br>#0 /home/betapori/public_html/public/index.php(73): Phalcon\Mvc\Application-&gt;handle()<br />
-- | --
  | #1 {main}
```

```php
try {

    // Setup Dependency Injector.
    $di = new Phalcon\DI\FactoryDefault();

    // Include autoloader.
    require STARTUP.DS.'loader.php';

    // Get configuration.
    /** @noinspection PhpUndefinedMethodInspection */
    $config = $di->getConfig();

    // Initialize ACL
    \Purs\Libs\Acl::init();

    // Handle request.
    $application = new Phalcon\Mvc\Application($di);
    $application->registerModules(
        [
            'front' => [
                'className' => FrontModule::class,
                'path'      => MODULES.DS.'FrontModule.php',
            ],
            'cms' => [
                'className' => CmsModule::class,
                'path'      => MODULES.DS.'CmsModule.php',
            ],
            'intra' => [
                'className' => IntraModule::class,
                'path'      => MODULES.DS.'IntraModule.php',
            ],
            'api'  => [
                'className' => ApiModule::class,
                'path'      => MODULES.DS.'ApiModule.php',
            ]
        ]
    );

    echo $application->handle()
        ->getContent();

} catch (Exception $e) {
	echo $e->getMessage(), '<br>';
	echo nl2br(htmlentities($e->getTraceAsString()));
}
```

### Details

* Phalcon version: 3.3.2
* PHP Version: 7.2.4
* Operating System: CentOS

**Comment by Niko9911** [comment] 2018-04-13 13:33
```
<?php

$loader = new Phalcon\Loader();


$loader->registerNamespaces([
    'Purs\Libs'                         => LIBS.DS,
]);


$loader->registerDirs([
    LIBS.DS.'plugins',
]);


$loader->registerFiles([
    BASE.DS.'vendor'.DS.'autoload.php',      
    STARTUP.DS.'sharedServices.php',            
    STARTUP.DS.'checks.php',         
    CONFIG.DS.'Define.php',                
]);


foreach (array_filter(glob(APP.DS.'*', GLOB_ONLYDIR)) as $key => $dir)
{
    $modules[$key] = substr($dir, strrpos($dir, '/') + 1);
}
define('MODULE_DIRS', $modules ?? die('No Modules Available!'));    

/** @noinspection ForeachSourceInspection */
foreach (MODULE_DIRS as $MODULE)            
{
    $loader->registerFiles(
        [
            APP.DS.$MODULE.DS.ucfirst($MODULE).'Routes.php',
            APP.DS.$MODULE.DS.ucfirst($MODULE).'Module.php',
        ], true);
}


$loader->register();
```

**Comment by Niko9911** [comment] 2018-04-13 16:40
Okey. I know what causes this.

Basicly loading "APP.DS.$MODULE.DS.ucfirst($MODULE).'Module.php'," crashes hole shit. I do not why.
That file is just empty and reserved for "future" use. 

I wrote `<?php ` to that file, nothing else. Still it gives error. But then I leave that out, it works. Weird..

**Comment by Ark4ne** [comment] 2018-04-14 09:43
The modules must implement the registerAutoloader & registerServices functions.

https://docs.phalconphp.com/en/3.3/application#module
https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/moduledefinitioninterface.zep

**Comment by Jurigag** [comment] 2018-04-14 10:01
It expects file as a class implementing proper interface. If it's empty then why you have a problem. Though im not sure why this method is fired at all.

**Comment by sergeyklay** [comment] 2018-04-17 05:08
> That file is just empty and reserved for "future" use.

As @Jurigag said expects file as a class implementing proper interface. As workaround you can create an empty implementation. Anyway i'm closing since this is a not a bug report. Feel free to discuss on the [official forums](https://forum.phalconphp.com), and/or the internals repo.

**Closed by sergeyklay** 2018-04-17 05:08 UTC

**Comment by Niko9911** [comment] 2018-04-17 08:59
@sergeyklay This is caused by namespace collision... Not because implementing wrong interface...
