### ISSUE TITLE
Parameter 'message' must be a string in FileValidator

### ISSUE THREAD

**Issue by be4i** [phalcon/cphalcon#12947] opened 2017-07-07 05:33 UTC
When i try to validate file upload, and the file exceeds the 'maxSize' specified in the FileValidator i get "Parameter 'message' must be a string" exception.
### Code

```
$form = new Form();
$file = new File('test');

$file->addValidator(new FileValidator([
	'maxSize'           => '3M',
	'allowEmpty'        => true,
	'allowedTypes'      => [
		'image/jpeg',
		'image/png'
	],
]));

$form->add($file);

if($this->request->isPost())
{
	if($form->isValid(array_merge($this->request->getPost(), $_FILES)))
	{

	}
	else
	{
		foreach($form->getMessages() as $message)
		{
			$this->flash->error($message);
		}
	}
}

$this->view->form = $form;
```

```
{{ form('', 'method': 'post', 'enctype': 'multipart/form-data') }}
    {{ form.render('test') }}
    <input type="submit" value="Go" />
{{ endForm() }}
```

Output

```
Parameter 'message' must be a string
#0 [internal function]: Phalcon\Validation\Message->__construct(false, 'test', 'FileIniSize', NULL)
#1 [internal function]: Phalcon\Validation\Validator\File->validate(Object(Phalcon\Validation), 'test')
#2 [internal function]: Phalcon\Validation->validate(Array, NULL)
#3 /home/be4i/Projects/phalcontest/app/controllers/IndexController.php(29): Phalcon\Forms\Form->isValid(Array)
#4 [internal function]: IndexController->indexAction()
#5 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(IndexController), 'indexAction', Array)
#6 [internal function]: Phalcon\Dispatcher->_dispatch()
#7 [internal function]: Phalcon\Dispatcher->dispatch()
#8 /home/be4i/Projects/phalcontest/public/index.php(42): Phalcon\Mvc\Application->handle()
#9 {main}
```

### Details

* Phalcon version: 3.2.0
* PHP Version: PHP 7.0.20-1~dotdeb+8.2
* Operating System: Debian Jessie
* Installation type: installing via package manager
* Zephir version (if any): 0.9.8-6335775f25
* Server: Apache2

**Comment by Jurigag** [comment] 2017-07-07 09:21
Not sure what happens here. Somehow you have false returned as message. Can you check what `$validation->getDefaultMessage('FileIniSize')` returns?

**Comment by be4i** [comment] 2017-07-07 14:34
/home/be4i/Projects/phalcontest/app/controllers/IndexController.php:40:string 'File :field exceeds the maximum file size' (length=41)

**Comment by Jurigag** [comment] 2017-07-07 15:02
Oh https://github.com/phalcon/cphalcon/blob/master/phalcon/validation/validator/file.zep#L114 there is no replacePairs defined, i guess when there is no replace pairs and those are not replaced there is false returned? @sergeyklay

**Comment by Jurigag** [comment] 2017-07-07 15:04
I will try to fix it later.

**Comment by Zaszczyk** [comment] 2017-07-19 10:10
I've also occured this bug

**Comment by haginaga** [comment] 2017-08-27 08:19
Same problem happened to me.
I am waiting to merge.

**Comment by martijnenco** [comment] 2017-09-14 15:55
I've the exact same problem. 
I will do a work around now with a callback for as long as this bug persits.

My error messege:
`( ! ) Fatal error: Uncaught InvalidArgumentException: Parameter 'message' must be a string in /var/source/app/dpdk/Validators/DynamicVacancyValidator.php on line 212
( ! ) InvalidArgumentException: Parameter 'message' must be a string in /var/source/app/dpdk/Validators/DynamicVacancyValidator.php on line 212
Call Stack
#	Time	Memory	Function	Location
1	0.0573	368192	{main}( )	.../index.php:0
2	1.6264	599160	dpdk\Bootstrap\BaseBootstrap->run( )	.../index.php:11
3	1.6264	599376	handle ( )	.../BaseBootstrap.php:70
4	1.6266	617888	dispatch ( )	.../BaseBootstrap.php:70
`

**Comment by sergeyklay** [comment] 2017-09-14 21:24
Fixed in the `3.2.x branch`. Feel free to open a new issue if the problem appears again. Thank you for contributing.

**Closed by sergeyklay** 2017-09-14 21:24 UTC
Labels: Bug - Low

**Comment by deadboy2** [comment] 2017-10-05 10:39
Не работает. Проблема актуальна

**Comment by martijnenco** [comment] 2017-10-05 10:57
What version do you run?  It has been fixxed 21 days ago..
Also I have made a work around. Currently I check the size manually (since we run an older version).
Also, isnt there a policy about communicating in english on this forum?

**Comment by deadboy2** [comment] 2017-10-05 10:59
Sorry. 

Phalcon version: 3.2.2
PHP Version: PHP 7.1
Operating System: Win10
Server: OpenServer

**Comment by deadboy2** [comment] 2017-10-05 11:22
I can't go on while the problem is actually. I hope you'll decide it as soon as possible.

**Comment by Zaszczyk** [comment] 2017-10-05 11:24
@deadboy2 just use try..catch:
```
try {
    $messages = $validator->validate($fileTemp);
} catch (\InvalidArgumentException $e) {
    //send message
}
```

**Comment by deadboy2** [comment] 2017-10-05 11:37
Its WORK! Thank you!
