### ISSUE TITLE
Phalcon phql can't increase column value using update

### ISSUE THREAD

**Issue by xfight0** [phalcon/cphalcon#3091] opened 2014-11-30 12:38 UTC
Code:
```php
$money = 1111;
$phql = 'update User set money =  money + :money: WHERE id = 17';
$result = $this->modelsManager->executeQuery($phql,[
    'money' => $money
]);
```
There is a error:
```
PDOException: SQLSTATE[HY093]: Invalid parameter number: 
mixed named and positional parameters
```
Is it a bug?

**Comment by andresgutierrez** [comment] 2015-04-09 19:59
Duplicate of #2373

**Closed by andresgutierrez** 2015-04-09 19:59 UTC
