### ISSUE TITLE
[BUG]:  Object of class Phalcon\Db\RawValue could not be converted to float

### ISSUE THREAD

**Issue by sowork** [phalcon/cphalcon#14635] opened 2019-12-19 06:05 UTC
**Describe the bug**
```
An error occurred when I performed the update operation using the PHQL statement
```

```php
result: 
Object of class Phalcon\Db\RawValue could not be converted to float
```

```php
$updatePHQL = "update " . XXX::class . " set lockedValue = lockedValue + :lockedValue: where id = :id: and nominalValue >= :lockedValue:";
        return $this->modelsManager->executeQuery($updatePHQL, [
            'lockedValue' => '12',
            'id' => $equityId
        ]);
```

**Details**
 - Phalcon version: 3.4.1
 - PHP Version: PHP 7.1.30-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: May 31 2019 11:43:14) ( NTS )
 - Operating System: windows
 - Server: swoole|nginx

**Comment by ruudboon** [comment] 2019-12-20 20:29
I think this related to https://github.com/phalcon/cphalcon/issues/14567 Not a bug but missing feature. Could you try it with out summing the column?

**Comment by ruudboon** [comment] 2020-01-02 09:46
Closing this in favour of #14567 Feel free to reopen if you tested this and the issue doesn't relate.

**Closed by ruudboon** 2020-01-02 09:46 UTC
Labels: bug, status: unverified
