### ISSUE TITLE
Placeholder :controller is not replaced in beforeMatch()

### ISSUE THREAD

**Issue by Sorbing** [phalcon/cphalcon#2459] opened 2014-05-22 14:25 UTC
Hi. Is this behavior normal?
```php
// http://test/base-controller
$router->add('/test/{controller:[a-z_-]+}')->beforeMatch(function($uri, $route) {
    $paths = $route->getPaths();
    $paths['controller'] = 'Other';
    $route->reConfigure($route->getPattern(), $paths);

    echo $route->getPaths()['controller']; // Why returns `1`?
    echo $paths['controller']; // Why returns `1` but not `Other`?
});
```
Thanks)

**Comment by andresgutierrez** [comment] 2015-06-25 03:05
Closed as not a bug

**Closed by andresgutierrez** 2015-06-25 03:05 UTC
Labels: Not a bug
