### ISSUE TITLE
Bug in validation 2.1.x

### ISSUE THREAD

**Issue by Izopi4a** [phalcon/cphalcon#10940] opened 2015-09-12 19:16 UTC
```php

public function validation()
    {
        $validator = new Validation();

        $validator->add(
            'email',
            new EmailValidator()
        );

        $validator->add(
            'username',
            new UniquenessValidator(
                [
                    'message' => 'Sorry, That username is already taken',
                ]
            )
        );

        return $this->validate();
    }

```

gives

```
<pre><br />
<b>Fatal error</b>:  Uncaught exception 'BadMethodCallException' with message 'Wrong number of parameters' in /var/www/phalcon.myapp.net/application/modules/common/models/User.php:599
Stack trace:
#0 /var/www/phalcon.myapp.net/application/modules/common/models/User.php(599): Phalcon\Mvc\Model-&gt;validate()
#1 [internal function]: Home\Models\User-&gt;validation()
#2 [internal function]: Phalcon\Mvc\Model-&gt;fireEventCancel('validation')
#3 [internal function]: Phalcon\Mvc\Model-&gt;_preSave(Object(Phalcon\Mvc\Model\MetaData\Memory), false, 'id')
#4 [internal function]: Phalcon\Mvc\Model-&gt;save(NULL, NULL)
#5 /var/www/phalcon.myapp.net/application/modules/api/controllers/UsersController.php(38): Phalcon\Mvc\Model-&gt;create()
#6 [internal function]: Api\Controller\UsersController-&gt;registerAction()
#7 [internal function]: Phalcon\Dispatcher-&gt;dispatch()
#8 /var/www/phalcon.myapp.net/vendor/ovr/phalcony/src/Application.php(183): Phalcon\Mvc\Application-&gt;handle(NULL)
#9 /var/www/phalcon.myapp.net/public/index.php(32): Phalcony\Appl in <b>/var/www/phalcon.myapp.net/application/modules/common/models/User.php</b> on line <b>599</b><br />
```

**Comment by KorsaR-ZN** [comment] 2015-09-12 19:22
Replace to: `return $this->validate($validator);`

**Comment by Izopi4a** [comment] 2015-09-12 19:24
then i get 

```<pre><br />
<b>Fatal error</b>:  Uncaught exception 'Phalcon\Validation\Exception' with message 'There is no data to validate' in phalcon/validation.zep:400
Stack trace:
#0 [internal function]: Phalcon\Validation-&gt;getValue('email')
#1 [internal function]: Phalcon\Validation\Validator\Email-&gt;validate(Object(Phalcon\Validation), 'email')
#2 [internal function]: Phalcon\Validation-&gt;validate(NULL, Object(Home\Models\User))
#3 /var/www/phalcon.myapp.net/application/modules/common/models/User.php(599): Phalcon\Mvc\Model-&gt;validate(Object(Phalcon\Validation))
#4 [internal function]: Home\Models\User-&gt;validation()
#5 [internal function]: Phalcon\Mvc\Model-&gt;fireEventCancel('validation')
#6 [internal function]: Phalcon\Mvc\Model-&gt;_preSave(Object(Phalcon\Mvc\Model\MetaData\Memory), false, 'id')
#7 [internal function]: Phalcon\Mvc\Model-&gt;save(NULL, NULL)
#8 /var/www/phalcon.myapp.net/application/modules/api/controllers/UsersController.php(38): Phalcon\Mvc\Model-&gt;create()
#9 [internal function]: Api\Controller\UsersController-&gt;registerAction()
# in <b>phalcon/validation.zep</b> on line <b>400</b><br />
```

i use it :

```
$user = new \Home\Models\User();
        $user->setActive(0);
        $user->setEmail($this->request->getPost('email', 'email', ''));

        echo "<pre>";
        var_dump($user->create());
        echo "</pre>";
        exit;
```

**Comment by Izopi4a** [comment] 2015-09-12 19:32
even this code of yours:

```
https://github.com/KorsaR-ZN/phalcon-core/blob/902c32675776fbcfbd3a5a6178d4cd07833c7e79/unit-tests/models/Subscriptores.php
```

doesnt work for me, with the latest pull of 2.1.x branch

**Comment by KorsaR-ZN** [comment] 2015-09-12 19:39
@Izopi4a Please show your model

**Comment by Izopi4a** [comment] 2015-09-12 19:43
if that is ok for you...
http://phalcon.opticlan.net/test.txt

I have skype / teamviewer btw, if you are instrested to do it faster :-)

**Comment by KorsaR-ZN** [comment] 2015-09-12 19:55
@Izopi4a 
It works for me.

Please replace to:
```
        $validator->add(
            'email',
            new \Phalcon\Validation\Validator\Uniqueness(array(
                "model" => $this,
                "message" => "Value of field 'email' is already present in another record"
            ))
        );
```

**Comment by Izopi4a** [comment] 2015-09-12 19:59
bah... still the same for me....

can it be  because of the Phalcony ?

https://github.com/ovr/phalcon-module-skeleton

https://github.com/ovr/phalcony

**Comment by KorsaR-ZN** [comment] 2015-09-12 20:05
@Izopi4a Give your Skype

**Comment by Izopi4a** [comment] 2015-09-12 20:05
r1d3r_bg

**Comment by KorsaR-ZN** [comment] 2015-09-12 20:37
@andresgutierrez Please regenerating build

**Comment by michanismus** [comment] 2015-09-13 16:52
Same here, when validation is called with 
let messages = validator->validate(null, this);
the no data exception is raised, when I try to execute the validation with entity (this) as first param 
let messages = validator->validate(this);
everything works fine 

https://github.com/phalcon/cphalcon/blob/2.1.x/phalcon/mvc/model.zep#L1401

**Comment by KorsaR-ZN** [comment] 2015-09-13 19:34
@michanismus 
This is fixed in `2.1.x` branch, you must regenerating build:
`zephir build`

**Comment by michanismus** [comment] 2015-09-13 19:41
Thanks

**Comment by michanismus** [comment] 2015-09-13 20:24
Now i get the following Exception: 
 RuntimeException: Trying to call method getdi on a non-object
 at Phalcon\Validation\Validator\Uniqueness->getColumnNameReal(User.php:281)
 at Phalcon\Validation\Validator\Uniqueness->isUniqueness(Unknown Source)
 at Phalcon\Validation\Validator\Uniqueness->validate(Unknown Source)
 at Phalcon\Validation->validate(Unknown Source)
 at Phalcon\Mvc\Model->validate(Unknown Source)



        $validation = new Validation;
        $validation->add('username', new Uniqueness(
            array(
                'model'   => 'User'
            )
        ));
        $test = $this->validate($validation); (line 281)

**Comment by michanismus** [comment] 2015-09-13 20:27
Ok, Model param was changed from static model class to model object, my fault. Now everything works as expected.
Thanks

**Comment by michanismus** [comment] 2015-09-13 20:38
Nope, me again :)
My model is loaded and I try to update the record. 
Primary key in condition is ignored:

if record->getOperationMade() == Model::OP_UPDATE {
....

getOperationMade() return 0 (OP_NONE) because nothing happened so far.

**Comment by KorsaR-ZN** [comment] 2015-09-13 20:47
@michanismus Please show your model to reproduce and fix the problem

**Comment by michanismus** [comment] 2015-09-13 21:11
My validation function:

```php
    /**
     * @inheritdoc
     */
    public function validation($context = null)
    {
        $validation = new Validation;
        $validation->add('username', new Uniqueness(
            array(
                'model'   => $this,
                'message' => "Username already exists."
            )
        ));

        $validation->add('email', new Uniqueness(
            array(
                'model'   => $this,
                'message' => "Email already exists."
            )
        ));

        $this->validate($validation);

        return parent::validation($context);
    }
```
Parent validation function:
```php
    /**
     * @param  \Symfony\Component\Validator\Context\ExecutionContext $context
     * @return boolean
     */
    public function validation($context = null)
    {
        $valid = $this->validationHasFailed() != true;

        if (!$valid && $context instanceof \Symfony\Component\Validator\Context\ExecutionContext) {
            foreach ($this->getMessages() as $message) {
                $context->buildViolation((string) $message)
                    ->atPath($message->getField())
                    ->addViolation();
            }
        }

        return $valid;
    }
```

My fields:
```php
class User extends AbstractModel
{
    /**
     * @var integer
     *
     * @Primary
     * @Identity
     * @Column(type="integer", nullable=false)
     */
    protected $id;

    /**
     * @Column(type="string", nullable=false, column="username", size="64")
     */
    protected $username;

    /**
     * @Column(type="string", nullable=false, column="email", size="255")
     */
    protected $email;
```

Data dump of record before validation function is called (nothing was changed/edited in html form):
```
array(3) {
  ["id"]=>
  string(1) "1"
  ["username"]=>
  string(11) "michanismus"
  ["email"]=>
  string(21) "mail@server.com"
}
```

**Comment by michanismus** [comment] 2015-09-13 21:17
I guess the error is here:
https://github.com/phalcon/cphalcon/blob/902c32675776fbcfbd3a5a6178d4cd07833c7e79/phalcon/validation/validator/uniqueness.zep#L114
Because there was no operation so far, I try to validate the record first and then update it...

**Comment by michanismus** [comment] 2015-09-15 06:37
@KorsaR-ZN 
The line should be:

```zephir
if record->getDirtyState() == Model::DIRTY_STATE_PERSISTENT {
```

**Comment by aguilera51284** [comment] 2015-10-08 17:26
i have the same problem in validation models. 
@KorsaR-ZN  by chance you'll have the .dll for this error

**Comment by mzf** [comment] 2016-02-19 07:38
Have this issue too, Phalcon 2.1.RC1

**Comment by sergeyklay** [comment] 2016-02-19 10:54
@Izopi4a Can you please check now `2.1.x`?

**Comment by Izopi4a** [comment] 2016-02-19 11:01
Hi @sergeyklay , 

this is working for me for quite some time now. There are some other comments that's why i didn'i close it. 

If you think you can close it.

**Comment by martin9348** [comment] 2016-02-24 16:05
I have this error (Trying to call method getdi on a non-object, with new validation, like first post but with return $this->validate($validator);) with Phalcon 2.1.0.RC1 - Windows x86 for PHP 5.6.0 (vc11). Has the fix been put in this release? Thank you.

**Closed** 2016-02-24 17:59 UTC
