### ISSUE TITLE
[Bug] Invalid Resultset\Complex with multiple LEFT joins in PHQL to the same table

### ISSUE THREAD

**Issue by skintagain** [phalcon/cphalcon#2428] opened 2014-05-14 09:43 UTC
Using Phalcon 1.3.2

When performing the following PHQL query the resulting Resultset\Complex does not hydrate models when there are multiple left joins to the same table:

````
SELECT a.*,b.*,b2.* FROM ModelA a
LEFT JOIN ModelB b on a.id=b.id and b.filter=1
LEFT JOIN ModelB b2 on a.id=b2.id and b.filter=2
````

The above result contains rows for table a and b2 but no b. By reversing the joins to:

````
SELECT a.*,b.*,b2.* FROM ModelA a
LEFT JOIN ModelB b2 on a.id=b2.id and b.filter=2
LEFT JOIN ModelB b on a.id=b.id and b.filter=1
````

This now contains rows for table a and b but no b2. The query executed on MySQL is entirely valid so this appears to be a bug with the hydration of the ResultSet.

Thanks

**Comment by andresgutierrez** [comment] 2015-04-14 16:10
Duplicate of #2113

**Closed by andresgutierrez** 2015-04-14 16:10 UTC
