### ISSUE TITLE
[2.1.x] Uniqueness validator with multiple fields is not compatible with old validator

### ISSUE THREAD

**Issue by Besedin86** [phalcon/cphalcon#11807] opened 2016-05-19 11:01 UTC
With old approach I can validate combination of fields for uniqueness like this:

```php
public function validation()
    {
       ...
       $this->validate(new Uniqueness(["field" => ['field_1', 'field_2']]));
       ...
    }
```

With new approach I can't do that. The example below doesn't work

```php
public function validation()
    {
      ...
      $validation->add(['field_1', 'field_2'], new Uniqueness());
      ...
    }
```

**Comment by Jurigag** [comment] 2016-05-19 11:03
Well. But in new validation you need to type what you want to validate in constructor:

```php
$validation->add(['field_1', 'field_2'], new Uniqueness([
    'model'=>$this
]));
```

**Comment by Besedin86** [comment] 2016-05-19 11:30
This is not decision. When you set array as first param you will get error "Array to string conversion", because add() method or his alias rule() accepts only string-convertible variables. This is the first.

```zephir
public function add(string field, <ValidatorInterface> validator) -> <Validation>
```

The second is in Uniqueness validator class. It does not support queries with multiple fields for uniqueness.

**Comment by Jurigag** [comment] 2016-05-19 11:32
Well i guess it's not supported then. I will check it later to add support for it. It just needs to accept array, and if its an array - then do foreach on those fields. Pretty easy to fix.

**Comment by Jurigag** [comment] 2016-05-19 13:45
To be honest for me new validation is worse than old. For example in previous validation i could create validator which could validate multiple fields and have multiple message(one for field). Right now i don't know how to do this in new validation.

**Comment by Besedin86** [comment] 2016-05-19 15:25
I'm tying to fix this problem in by [branch](https://github.com/Besedin86/cphalcon/commit/ebc6039b7f597f83ed943053222e280d086e280d)

**Comment by Jurigag** [comment] 2016-05-19 15:29
Isn't better to do here for in https://github.com/Besedin86/cphalcon/commit/ebc6039b7f597f83ed943053222e280d086e280d#diff-86920296fe08950334f3b3f6d672f12cR167 and allow all validators multiple fields(as well as rest of those methods) ?

Also you could add option to allow messages as assoc array too(it will just access key which is field if message is array(this will need to edit all validators as well as change i mention above).

**Comment by Besedin86** [comment] 2016-05-19 15:55
we already have 'model' => $this in https://github.com/phalcon/cphalcon/blob/2.1.x/phalcon/mvc/model.zep#L1391

**Comment by Jurigag** [comment] 2016-05-19 15:59
Yes, we are passing this, it's setter here - https://github.com/phalcon/cphalcon/blob/2.1.x/phalcon/validation.zep#L97 But in uniquness validator we don't access it using `getEntity()` only `model` so we need right now add model=>$this when adding Uniquness validator to model.

**Comment by dschissler** [comment] 2016-05-24 14:55
Essentially a dupe of #11173

**Closed** 2016-05-24 15:06 UTC
Labels: Duplicate
