### ISSUE TITLE
PHP 7.1 segfault

### ISSUE THREAD

**Issue by romanlex** [phalcon/cphalcon#12560] opened 2017-01-20 08:43 UTC
On my system I get segfault with php.
When I remove phalcon.ini from conf.d directory - all work properly

```
20.01.17 11:38	systemd	Starting The PHP FastCGI Process Manager...
20.01.17 11:38	kernel	php-fpm[4100]: segfault at a00000001 ip 00000000006d39eb sp 00007ffd86ce7b40 error 6 in php-fpm[400000+8be000]
20.01.17 11:38	systemd	Started Process Core Dump (PID 4101/UID 0).
20.01.17 11:38	systemd	php-fpm.service: Main process exited, code=dumped, status=11/SEGV
20.01.17 11:38	systemd	Failed to start The PHP FastCGI Process Manager.
20.01.17 11:38	systemd	php-fpm.service: Unit entered failed state.
20.01.17 11:38	systemd	php-fpm.service: Failed with result 'core-dump'.
20.01.17 11:38	sudo	pam_unix(sudo:session): session closed for user root
20.01.17 11:38	systemd-coredump	Process 4100 (php-fpm) of user 0 dumped core.

Stack trace of thread 4100:
#0  0x00000000006d39eb zend_do_implement_interface (php-fpm)
#1  0x00000000006988e0 zend_class_implements (php-fpm)
#2  0x00007fe187096b8e n/a (phalcon.so)
#3  0x00007fe1870a98f3 n/a (phalcon.so)
#4  0x00000000006965fe zend_startup_module_ex (php-fpm)
#5  0x00000000006966ac n/a (php-fpm)
#6  0x00000000006a3fea zend_hash_apply (php-fpm)
#7  0x000000000069695a zend_startup_modules (php-fpm)
#8  0x000000000062eb13 php_module_startup (php-fpm)
#9  0x0000000000741105 n/a (php-fpm)
#10 0x00000000004347f2 n/a (php-fpm)
#11 0x00007fe19036c291 __libc_start_main (libc.so.6)
#12 0x0000000000435cca _start (php-fpm)

```

### Details

* Phalcon version: 3.0.3
* PHP Version: PHP 7.1.1 (cli) (built: Jan 18 2017 18:44:22) ( NTS )
* Operating System: Arch Linux
* Installation type: installing via package manager
* Server: Nginx

**Comment by Jurigag** [comment] 2017-01-20 09:29
Duplicate of https://github.com/phalcon/cphalcon/issues/12055

**Closed** 2017-01-20 15:37 UTC
