### ISSUE TITLE
Bug in Phalcon\Mvc\Model `__set()` method for array data params

### ISSUE THREAD

**Issue by sszdh** [phalcon/cphalcon#10556] opened 2015-06-27 13:38 UTC
As [this](https://forum.phalconphp.com/discussion/7321/model-set-method-for-array-params#C19977) forum post. I think there is a bug in `__set()` method and the relation alias should be checked in array assignment before fall in relation logics (or just use __isset() method):

``` php
/**
 * Magic method to assign values to the the model
 *
 * @param string property
 * @param mixed value
 */
public function __set(string property, value)
{
    var lowerProperty, related, modelName, manager, lowerKey, relation, referencedModel,
        key, item;

    /**
     * Values are probably relationships if they are objects
     */
    if typeof value == "object" {
        if value instanceof ModelInterface {
            let lowerProperty = strtolower(property),
                this->{lowerProperty} = value,
                this->_related[lowerProperty] = value,
                this->_dirtyState = self::DIRTY_STATE_TRANSIENT;
            return value;
        }
    }

    /**
     * Check if the value is an array
     */
    if typeof value == "array" {

        let lowerProperty = strtolower(property),
            modelName = get_class(this),
            manager = this->getModelsManager();

        /* check relation here */
        let relation = <RelationInterface> manager->getRelationByAlias(modelName, lowerProperty); // <-- LOGIC HERE
        if typeof relation == "object" {

            let related = [];
            for key, item in value {
                if typeof item == "object" {
                    if item instanceof ModelInterface {
                        let related[] = item;
                    }
                } else {
                    let lowerKey = strtolower(key),
                        this->{lowerKey} = item,
                        relation = <RelationInterface> manager->getRelationByAlias(modelName, lowerProperty);
                        if typeof relation == "object" {
                            let referencedModel = manager->load(relation->getReferencedModel());
                            referencedModel->writeAttribute(lowerKey, item);
                        }
                }
            }

            if count(related) > 0 {
                let this->_related[lowerProperty] = related,
                    this->_dirtyState = self::DIRTY_STATE_TRANSIENT;
            }

            return value;
        }
    }

    /**
     * Fallback assigning the value to the instance
     */
    let this->{property} = value;

    return value;
}
```

Any idea? or workaround for this bug?

Thanks

**Comment by sszdh** [comment] 2015-08-03 09:25
Any comments?

**Comment by sszdh** [comment] 2015-10-29 18:35
Still, there is no way to assign an `array` to model's property! 

I think this is a bug.

Thanks.

**Comment by sszdh** [comment] 2016-05-26 13:22
Hey,
Nothing here yet?
To assign `array` data to model's property?

**Comment by sergeyklay** [comment] 2016-05-26 13:29
Could you please explain a bit more use case?

**Comment by sszdh** [comment] 2016-05-26 13:57
@sergeyklay sure.

Consider this model:

```php
class MyModel extends \Phalcon\Mvc\Model
{
    /**
     * @var array
     */
    protected $my_prop;

    public function setMyProp(){
        $this->my_prop = serialize(array_filter($my_prop));
        return $this;
    }

    public function getMyProp(){
        return is_null($this->my_prop) ? [] : unserialize($this->my_prop);
    }
}
```
Using this model as follow does not works:

```php
$model = new MyModel();
$model->my_prop = ['Mike', 'John', 'Soheil'];
$model->save();
```

The `my_prop` does not save anymore because this falls to relation check logic.
This [line](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model.zep#L4106) 

I change my Base model class with this line of code for workaround:

```php
class Base extends \Phalcon\Mcv\Model
{
    ...

    public function __set($property, $value)
    {
        if(!is_object($value)) {
            if(!$this->getModelsManager()->getRelationByAlias(get_class($this), strtolower($property))) {
                /**
                 * Check if the property has any setter
                 */
                if ($this->_possibleSetter($property, $value)) {
                    return $value;
                }
            }
        }

        return parent::__set($property, $value);
    }
    
    ...
}
``` 

Thanks.

**Comment by Jurigag** [comment] 2016-05-26 14:33
IF you created setter why you not using it ? I don't understand the problem.

**Comment by sszdh** [comment] 2016-05-26 14:44
@Jurigag Maybe you're right but `Developers can decide which strategy is more appropriate for the application they are creating.`
See [this](https://docs.phalconphp.com/en/latest/reference/models.html#public-properties-vs-setters-getters)

Anyway, your suggestion does not match to the issue we already have here!

Thanks.

**Comment by Jurigag** [comment] 2016-05-26 14:51
But in docs is about PUBLIC PROPERTIES vs SETTERS/GETTERS, you created protected property and you trying to access it. You need setter for it(like in any other language like c# or java).

**Comment by sszdh** [comment] 2016-05-26 14:57
@Jurigag So, are you saying that the Phalcon Model's `__set` and `_possibleSetter` strategies are totally wrong decision or bad feature? Are you trying to mention that?

**Comment by Jurigag** [comment] 2016-05-26 15:01
Yes, it's wrong decission and bad feature in my opinion, basically `__set` method should be never added into php. I just don't understand - if you want to set private/protected property - just add setter and use it.

**Comment by sszdh** [comment] 2016-05-26 15:06
@Jurigag If so, I think this is another topic that we can discuss about somewhere else.

In the current state, I think this is a bug that we can not assign and `array` data to protected property with setter method in our model. see this:

```php
...
$model = new MyModel();

$model->my_prop = 'soheil'; // This works
$model->my_prop = 123; // This works too
$model->my_prop = ['Mike', 'John', 'Soheil']; // Does not work!
...
```
Isn't weird?

Thanks

**Comment by Jurigag** [comment] 2016-05-26 15:08
Yes, it's a bug. But why you want to use magic setters if YOU ALREADY ADDED SETTER ?! I don't understand it, read the phalcon docs or any language docs perhaps ?

**Comment by sszdh** [comment] 2016-05-26 15:36
@Jurigag Okey, in short use case consider this usecase:
```php
$model->save($_POST, ['name','my_prop']);
```

For record:
Actually in the above approach of saving data (passing data as argument to `save()`), the setter will be called for `array` data! (Thanks to this [line](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model.zep#L480) of code)

**Comment by Jurigag** [comment] 2016-05-26 15:39
It will work. The problem is not with `_possibleSetter` but with `__set` method.

**Comment by sszdh** [comment] 2016-05-26 15:44
@Jurigag What are you meaning "It will work" ?

Actually my last example is for this question:

> But why you want to use magic setters if YOU ALREADY ADDED SETTER ?!

**Comment by sszdh** [comment] 2016-05-26 15:50
@Jurigag This is not about just using `__set` magic method to have magic setting stuff. If you look closer, Actually The `_possibleSetter()` is a handmade magic setter, logically :)

**Comment by Jurigag** [comment] 2016-05-26 15:56
But it doesn't using magic setter in the case you wrote. It's just calling setter if there is one, if no - it's just setting value using this->{key} = value;

**Comment by sergeyklay** [comment] 2017-10-04 21:03
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Comment by sunchuo** [comment] 2017-12-26 15:22
<?php
//model content:

use Phalcon\Mvc\Model;



//params
$params = [];
$params['name'] = 'test name';
$params['status'] = ['a', 'b', 'c'];
$robots = new Robots($params);

var_dump($robots->toArray());







`
model:
class Robot extends \Phalcon\Mvc\Model
{
    public $id;
    public $name;
    public $status;
}

$params = [
    'name' => 'aaaa',
    'status' => ['a', 'b', 'c'];
];

$robot = new Robot($params);
print_r($robot->toArray());

Array
(
    [id] => 
    [name] => test name
    [status] => Array
        (
            [0] => a
            [1] => b
            [2] => c
        )
)

-------------
class Robot extends \Phalcon\Mvc\Model
{
    public $id;
    public $name;
}
$params = [
    'name' => 'aaaa',
    'status' => ['a', 'b', 'c'];
];

$robot = new Robot($params);
print_r($robot->toArray());

Array
(
    [id] => 
    [name] => test name
    [status] => 
)

`

**Comment by borisdelev** [comment] 2018-12-13 13:59
Well... i have same issue. I think @sszdh is right.

Consider this (if we follow phalcon setter docs):
```php
# MODEL
namespace Models;

class Lessons extends \Phalcon\Mvc\Model
{
    public $id;
    protected $title;

    public function setBobi($test)
    {
        echo $test;
        exit;

        $this->title = $test;
    }
```

```php
# Somewhere
$model = new MyModel();

$model->bobi = 'soheil'; // Will print 'soheil' (see model exit)
```
So this will exit on 'soheil'. But if we make setter that mus accept array- it is not possible (without logick). Example:
```php
# MODEL
namespace Models;

class Lessons extends \Phalcon\Mvc\Model
{
    public $id;
    protected $title;

    public function setBobi(array $test)
    {
        var_dump($test);
        exit;

       $this->title = implode(',', $test);
    }
```
end execute:
```php
# Somewhere
$model = new MyModel();

$model->bobi = ['some', 'other']; // Will do nothing
```
...this will not var_dump. Why?

Will work if i use setter like function ```$model->setBobi(['some']);``` but why? If i make $model->save($post) and in post i have multiple values on some property will not work with setter.

**Comment by sergeyklay** [comment] 2018-12-13 23:57
@niden Could you please take a look

**Comment by borisdelev** [comment] 2018-12-14 08:36
I am pretty sure this is same as - https://github.com/phalcon/cphalcon/issues/13661 ... and fix this should make all works fine.

**Comment by niden** [comment] 2018-12-21 22:34
This has been addressed with https://github.com/phalcon/cphalcon/pull/13677

**Closed by niden** 2018-12-21 22:34 UTC
