### ISSUE TITLE
Creation of Resourses and Roles implicity

### ISSUE THREAD

**Issue by salarmehr** [phalcon/cphalcon#2588] opened 2014-07-02 06:52 UTC
I think the `Acl::allow()` should create roles and resources implicitly when they are not defined in advance. Indeed there is no need to user `addRole` and `addRecource`. (Only when we want declare an inheritance relation the `addRole method can be useful.  )
##

**Comment by sergeyklay** [comment] 2017-06-08 19:31
I'm closing since this is a not a bug report.  No work was put towards this, contributions welcome. Also feel free to discuss on the [official forums].

**Closed by sergeyklay** 2017-06-08 19:31 UTC
Labels: New Feature Request
