### ISSUE TITLE
Syntax error, unexpected token IS in Volt

### ISSUE THREAD

**Issue by afbora** [phalcon/cphalcon#11683] opened 2016-04-17 17:04 UTC
When i use a `is()` function in Volt, like that:

```
{% if mobileDetect.is('Chrome') %} {% endif %}
```

I guess, `is` word conflicting with Volt and i get following error:

> Syntax error, unexpected token IS in themes/default/views/index/index.volt on line 78

Than tried `isMobile` function that `is` word contains, but this is working, no errors:

```
{% if mobileDetect.isMobile() %}
```

**Comment by JCMais** [comment] 2016-04-25 17:31
Not a bug, ``is`` _is_ a reserved word. https://docs.phalconphp.com/en/latest/reference/volt.html#other-operators

**Comment by afbora** [comment] 2016-04-25 18:23
@JCMais i know that `is` reserved. But could be override or ignore like that `\is`.

**Comment by sergeyklay** [comment] 2016-04-25 18:27
`$is` ?

**Comment by afbora** [comment] 2016-04-25 21:22
@sergeyklay I tried like your said as following:

    {% if !mobileDetect.$is('Chrome') %}

Getting that error:

> Scanning error before 'is('Chrome') %} ...' in themes/default/views/index/index.volt on line 78

**Comment by makerlabs** [comment] 2016-04-26 07:13
Even if "is" is a reserved word it should be ignored when called like a method. So a Bug to me

**Comment by niden** [comment] 2019-09-24 14:56
@sergeyklay Has this been addressed with https://github.com/phalcon/cphalcon/pull/14410 ? If so we can close it

**Comment by niden** [comment] 2019-09-24 14:58
Resolved in https://github.com/phalcon/cphalcon/pull/14410/files

**Closed** 2019-09-24 14:58 UTC
Labels: 4.0, Bug - Low
