### ISSUE TITLE
Console in the case of multiple modules.

### ISSUE THREAD

**Issue by zuozhehao** [phalcon/cphalcon#14206] opened 2019-06-25 09:30 UTC
phalcon 4.0

```php
$di  = new \Phalcon\Di\FactoryDefault\Cli;
$app = new \Phalcon\Cli\Console;

$di->setShared('router', function () {

    $router = new \Phalcon\Cli\Router;

    $router->setDefaultModule('task');

    return $router;

});
```
It's return Module 'task' isn't registered in the console container

```php
$di  = new \Phalcon\Di\FactoryDefault\Cli;
$app = new \Phalcon\Cli\Console;

$app->registerModules($modules);

$di->setShared('router', function () {

    $router = new \Phalcon\Cli\Router;

    $router->setDefaultModule('task');

    return $router;

});
```
Phalcon could not find the default task and action, because I didn't set the namespace.
I think it would be duplicative if set up the namespace again.

**Comment by ruudboon** [comment] 2019-07-01 14:26
I wasn't able to reproduce this behaviour based on the code you gave us. @zuozhehao Do you have a complete example for me so I can reproduce this?

**Comment by zuozhehao** [comment] 2019-07-02 02:03
You can use the official example. [https://docs.phalconphp.com/4.0/it-it/application-cli](https://docs.phalconphp.com/4.0/it-it/application-cli).
Just need to add
```php
$di->setShared('router', function () {

    $router = new \Phalcon\Cli\Router;

    $router->setDefaultModule('task');

    return $router;

});
```

**Comment by niden** [comment] 2019-07-06 00:20
I don't understand what you are trying to do @zuozhehao . Explain this to me a bit more.

So you are using the official example where the default namespace is set 

```php
$dispatcher->setDefaultNamespace("MyApp\\Tasks");
```

Now you add a router object and you specify that the `defaultModule` will be `task`. Then you get the message that `task` cannot be found?

Can you post a bit more here on what you really want to do, what you see and what the structure of your app is?

Thank you

**Comment by zuozhehao** [comment] 2019-07-11 00:51
I want Phalcon to support `setDefaultModule` in Console mode when I `registerModules` @niden

**Comment by niden** [comment] 2019-07-12 01:22
@zuozhehao I checked the code. `setDefaultModule` exists in the Cli application. Also you can register modules to it. So I am sorry I do not fully understand the issue.

Could you be so kind as to post the exact code you are using and the error you are seeing so that I can figure it out. ?

Thanks!

**Comment by zuozhehao** [comment] 2019-07-12 06:43
@niden Sorry, maybe I didn’t express my problem.

```php
<?php

$modules = [

    'cli' => [

        'namespace' => 'app\task\controller',
        'className' => 'app\task\Module',
        'path'      => 'src/module/task/Module.php'

    ],

    'mvc' => [

        'namespace' => 'app\mvc\controller',
        'className' => 'app\mvc\Module',
        'path'      => 'src/module/mvc/Module.php'

    ],

];

$app->registerModules($modules);

$di->setShared('router', function () use ($modules) {

    $router = new \Phalcon\Mvc\Router;
    // $router = new \Phalcon\Cli\Router;

    $router->setDefaults($modules['mvc']);

    return $router;

});
```
In MVC mode, I use `setDefaults ` to automatically register the namespace, but in CLI mode it doesn't, it requires me to set the namespace once using Dispatcher.
I hope that it can be unified under Mvc, Cli.

**Comment by zuozhehao** [comment] 2019-07-12 06:51
https://github.com/phalcon/cphalcon/blob/master/phalcon/Mvc/Router.zep#L918-L921

**Comment by niden** [comment] 2019-07-12 15:59
The way it is implemented you cannot do what you are asking. There are 2 routers as you see. The Mvc one and the Cli one and you need to register the modules and namespace on each of those routers. 

The reason behind this is that a MVC application will never be a CLI application and vica versa. From what I understand you are trying to mix them both so as to have potentially less code to maintain.

What you could do is have common setup code for both and then override the non common parts such as setting up the router or dispatcher services for MVC vs CLI.

Finally in order to _merge_ both routers and dispatchers, that could potentially happen in a future version of Phalcon since it will require significant refactoring.

**Comment by zuozhehao** [comment] 2019-07-16 16:09
ok, Thanks.

**Comment by niden** [comment] 2019-07-16 17:20
Closing this.

**Closed by niden** 2019-07-16 17:20 UTC
Labels: 4.0, Not a bug
