### ISSUE TITLE
Controller action with redirect sometimes called twice in chrome 

### ISSUE THREAD

**Issue by osse76** [phalcon/cphalcon#10319] opened 2015-05-11 10:38 UTC
In my application, i have a logout method with redirect to login site simliar to Vokuro application.
Additionally i set a Flash Session (You are logged out) in method logout. Sometimes the flash message was present twice by chrome.
I debugged with xdebug and yes, sometimes the method called twice. I don´t know why.

The Workflow:
1. Call login page (typed in browser - http://localhost/vokuroTest/session/login)
2. Reload page
3. Call logout page (typed in browser - http://localhost/vokuroTest/session/logout)

I tested with diffent systems, and anywhere the same. So now, i don´t have any idea to fix this.
I also take a clean Vokuro application, added FlashSession and try to reproduce this behavior. It´s the same resolution.
Chrome Version Version 42.0.2311.135 

So the question is, is this a bug in chrome, or in the framework, or anything else.
Here is the modified Vokuro application: https://github.com/osse76/VokuroTest.git

**Comment by andresgutierrez** [comment] 2015-05-13 14:52
Try to add a favicon.ico here: https://github.com/osse76/VokuroTest/tree/master/public

**Comment by osse76** [comment] 2015-05-14 17:29
Unfortunately, the same result.

**Comment by andresgutierrez** [comment] 2015-08-04 16:51
Needed script to reproduce

**Comment by sergeyklay** [comment] 2016-06-09 21:02
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Closed by sergeyklay** 2016-06-09 21:02 UTC
Labels: Need information, Need script to reproduce
