### ISSUE TITLE
Serious bug in variable binding

### ISSUE THREAD

**Issue by salarmehr** [phalcon/cphalcon#3087] opened 2014-11-29 14:46 UTC
Consider the following code:

        $query = $this->modelsManager->createBuilder()->from('User');
        $query->andWhere('sex=?0', ['f']);
        $query->andWhere('age=?0', [55]);
        $query->andWhere('name=?0', ['Tom']);

First variable will be assigned to all three place holder: `where sex='f' and age='f' and name='f'` 
This cost me two days. ◕︵◕

**Comment by salarmehr** [comment] 2015-05-10 06:41
@stanislav-web The link is broken. May you please renew the link.

**Comment by salarmehr** [comment] 2015-05-10 06:43
@phalcon each condition should be binded to its variables and should be independent from other conditions.

**Comment by andresgutierrez** [comment] 2015-08-28 21:39
Closed as not a bug

**Closed by andresgutierrez** 2015-08-28 21:39 UTC
Labels: Not a bug
