### ISSUE TITLE
[BUG] $this->dispatcher->getControllerName()  return null

### ISSUE THREAD

**Issue by bain2018** [phalcon/cphalcon#14533] opened 2019-11-14 05:49 UTC
Describe the bug

in the controller, i want to get current controller name by this method,but get null
$this->dispatcher->getControllerName()  

index.php

    $di = new \Phalcon\Di\FactoryDefault();
    // Handle the request
    $application = new \Phalcon\Mvc\Application($di);
  
    $application->registerModules([
        'api' =>[
            'className' => App\Bootstrap\Api::class,
            'path'      => ROOT_PATH.'App/Bootstrap/Api.php',
            "metadata"  => [
                "controllersNamespace"=>"\App\Controllers\Api",
            ],
        ],
    ]);
    $application->useImplicitView(false)->handle($_SERVER["REQUEST_URI"])->send();

Bootstrap/Api.php:

    public function registerServices(DiInterface $di)
    {
        // Registering a dispatcher
        $di->set('dispatcher', function (){
            $dispatcher = new Dispatcher();
            $dispatcher->setModuleName('api');
            $dispatcher->setDefaultNamespace("\\App\Controllers\\Api");
            return $dispatcher;
        });
    }

Details
Phalcon version:4.0 rc2
PHP Version: 7.3.11
Operating System: ubuntu

**Comment by ruudboon** [comment] 2019-11-30 22:24
@bain2018 I tried reproducing this issue but unable to do so. I used the modules template from the dev tools and inside the controller I get index back when running:
```
public function indexAction()
    {
        exit($this->dispatcher->getControllerName());
    }
```
Can you supply a full code example?

**Comment by ruudboon** [comment] 2019-12-08 15:39
@bain2018 We're unable to reproduce this so closing this for now. Please reopen if this issue if you have some more information how to reproduce this.

**Closed by ruudboon** 2019-12-08 15:39 UTC
Labels: 4.0, Bug - Unverified, Need information
