### ISSUE TITLE
The brand-new Phalcon/Zephir development workflow

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/cphalcon#3246] opened 2015-01-19 10:08 UTC
The brand-new Phalcon/Zephir development workflow
---------------------------------------------------------------------

Hey all!

So, we are active Phalcon/Zephir users and we want the development of these projects to be reactive. But due to some problems in organization and management of the community, as well as due to a lack of time leader of the project Andres Gutierrez has these projects are developing quite slowly and it's awful.

We propose to take an open vote on an issue of granting the status of organizations to Phalcon and Zephir and to determine major maintainers and general development principles of these projects.

There are basic needs that we are motivated by:

* Creation of non-commercial organizations for Phalcon and Zephir with making public repositories for the projects
* Transferring the projects from personal accounts of current maintainers under the guidance of appropriate organizations
* Creation of a public foundation for searching sponsors and investors and thereby providing financial backing of projects
* Reorganization of working process in acceptance of commits into the projects in such a manner as to involve more active participants in development process
* Delegation of main authorities and duties from the small group of current maintainers (Andres Gutierrez, Nikolaos (Nikos) Dimopoulos, Eduar Carvajal, Nikolay (boston) Kirsh) to active community

Please, if you are not indifferent to the development of projects, take an active part in this small survey.

We appreciate your opinion.
We want to make the world a better place.

Regards,
active Phalcon/Zephir community members.

*Russian*

Совершенно новый процесс разработки Phalcon/Zephir
--------------------------------------------------------------------------

Здравствуйте!

Мы, активные пользователи Phalcon/Zephir, хотим, чтобы развитие этих проектов стало реактивным. Но из-за некоторых проблем в организации сообщества и нехватки времени у лидера проектов Andres Gutierrez, проекты развиваются достаточно вяло.

Мы предлагаем провести открытое голосование для придания Phalcon и Zephir статуса организаций и определения основных мейнтейнеров и принципов развития проектов.

Ниже сформулированы основные идеи, которые нами движут:

* Создание некоммерческих организаций Phalcon и Zephir с созданием публичных репозиториев для проектов
* Перенос проектов с личных аккаунтов текущих мейнтейнеров под крыло соответствующих организаций
* Создание публичного фонда для финансирования проектов, в задачи которого входил бы поиск спонсоров и инвесторов
* Реорганизация рабочего процесса принятия коммитов в проекты таким образом, чтобы привлечь к процессу разработки больше активных участников
* Делегирование основных обязанностей и полномочий от небольшой группы текущих мейнтейнеров (Andres Gutierrez, Nikolaos (Nikos) Dimopoulos, Eduar Carvajal, Nikolay (boston) Kirsh) активному сообществу

Пожалуйста, если вы заинтересованы в развитии проектов, проявите свою активность в этом небольшом опросе.

Нам важно ваше мнение.
Мы хотим, чтобы мир стал лучше.

С уважением,
активные участники сообщества Phalcon/Zephir

**Comment by ovr** [comment] 2015-01-19 10:10
:+1: 

We need to get experience from Symfony organazation 
![](https://www.flickr.com/photos/21284732@N04/13734902144)

**Comment by sergeyklay** [comment] 2015-01-19 10:11
+1

**Comment by sergeyklay** [comment] 2015-01-19 10:20
![13734902144_410fbf9451_c](https://cloud.githubusercontent.com/assets/1256298/5798950/9ac10e80-9fd5-11e4-9729-e83de56e90d5.jpg)

**Comment by m1ome** [comment] 2015-01-19 11:01
:+1:

**Comment by 7thcubic** [comment] 2015-01-19 11:05
+1

**Comment by SachaMorard** [comment] 2015-01-19 11:27
:+1:

**Comment by xboston** [comment] 2015-01-19 12:05
+1

**Comment by duythien** [comment] 2015-01-19 14:38
+2

**Comment by phalcon** [comment] 2015-01-19 15:07
I appreciate your recent contributions, but seriously, I think this is nonsense.

> Creation of non-commercial organizations for Phalcon and Zephir with making public repositories for the projects

We're a non-commercial organization, why do you need new ones?

I'm regularly merging PR, however many of them add new features which is something that is not a priority currently and just make us away from the release of Phalcon 2. There are blocking and important bugs to fix on both Phalcon and Zephir and all the efforts are still focused on personal needs or believes on what Phalcon needs to be which is not thinking as an "organization". In addition, there are many things you guys can work to make the project move forward:

* Fix critical bugs
* Implement most requested new features posted in Github
* Migrate current website to the new design
* Fix and improve phalcon-devtools
* Help people out in forums/github
* Write unit-tests for any of the sub-projects in Phalcon

To be honest, none of you are near of being one of the major contributors of Phalcon, (with the exception of @ovr in Zephir). I can't believe how you expect I transfer the control of the project to anyone of you. This project doesn't need more managers, it needs more people fixing things and working on those issues that are priority.

**Comment by dschissler** [comment] 2015-01-19 18:46
@phalcon I'm thinking that phalcon could use an officially blessed sophomore/junior level repository that mirrors classes in both php and zephir.

So:

* phalcon-extra-php
* phalcon-extra-zephir

Then you could be a bit more loose with the keys there and people could gain experience in maintaining functionality between both php and zephir.  This will train up people to know how zephir is tracking php and that sort of thing.  I think that with this approach phalcon could gain a major contributor or two in time.  Giving out contributor access there wouldn't be such a big deal the standard way of installing these tools was through tagged composer packages.  Then just have a core member control the composer publishing.  Worst case if someone goes crazy with the github repo then you can boot them from it.

**Comment by sergeyklay** [comment] 2015-01-19 19:58
@dschissler Incubator has PR who had long without comments including my. What kind of activity we can discuss if PR contemplated several weeks?

**Comment by phalcon** [comment] 2015-01-19 20:05
@sergeyklay "several weeks":

13 days: https://github.com/phalcon/incubator/pull/246
10 days: https://github.com/phalcon/incubator/pull/246

**Comment by m1ome** [comment] 2015-01-19 20:07
@phalcon 10 and 13 days it's kind a huge time for a project like Phalcon

**Comment by dschissler** [comment] 2015-01-19 20:09
@phalcon I'm thinking though that the level of wait is unnecessary as there surely are more than 3-4 people in the community who are capable of merging some PHP code.  That kind of a wait is a no-go for small fixes to code.  People will just end up copying the file into their project and renaming the namespace (like I do).

Also, just doing an `composer require phalcon-incubator` doesn't currently work.  The incubator is broken and neglected.  There is certainly useful code there but its not in the right spirit IMO.

**Comment by phalcon** [comment] 2015-01-19 20:09
Why? There are just a few ones awaiting reviewing, let's take other projects you mention as example:

2 years without merge: https://github.com/symfony/symfony/pull/3842
2 years without merge: https://github.com/symfony/symfony/pull/5189

**Comment by dschissler** [comment] 2015-01-19 20:20
Right now I'm creating a Volt gettext parser based on another's Swig parser.  I knew that the author would be very responsive and so I did the work knowing that I could have a few iterations (almost guaranteed) within a weeks time.  The way that it is setup now I wouldn't contribute something to the incubator with the intention of working through it.  Its pretty much just a final code drop off point as it is now because someone would have to be crazy to expect a response suitable for a workflow.  Then if I had to wait 1-2-3 weeks to get a minor change committed then I would be pointed at my own code far more than I would be pointed at the incubator.  Plus the latest tagged release is literally broken now on composer if you are on phalcon 1.3.*.  Nobody seems to care either and this tells me that hardly anyone is using it in that way.  The incubator could be a lot more than it is now.

**Comment by trentramseyer** [comment] 2015-01-19 20:21
I'd rather have it right and take whatever time it needs, then make sure everyone's whims are answered in some unprecedented timeline.  My gripe, which has always been my own, is the non cohesive manner the docs are presented in at times. Every time I search for issues, I seem to find 100 new features hidden here and there that make it even better. When I say "hidden" I just mean they aren't initially found in the docs in a quick manner.

**Comment by sergeyklay** [comment] 2015-01-19 20:24
@dschissler 
> The incubator could be a lot more than it is now.

:+1:

**Comment by dschissler** [comment] 2015-01-19 20:27
@sergeyklay Also I just realized that I implied that you *must be crazy*.  Just an idiom really.

**Comment by sergeyklay** [comment] 2015-01-19 20:29
Incubator, it seems to me, could be a such project from where ideas can be borrowed into to the upstream.

**Comment by phalcon** [comment] 2015-01-19 20:34
@dschissler I've added a new tag to the incubator some days ago as you requested, I've successfully executed ```composer require phalcon/incubator``` and it works as expected:

```$ composer require phalcon/incubator
Using version ~1.3 for phalcon/incubator
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing phalcon/incubator (v1.3.4)
    Downloading: connection...    Downloading: 100%

Writing lock file
Generating autoload files
```

Phalcon Version:
```
$ php -r 'echo Phalcon\Version::get();'
1.3.4
```

**Comment by SachaMorard** [comment] 2015-01-19 20:51
@phalcon We would love to fix bugs, but it's not really simple to get a reliable list of issues concerning 2.0.0

https://github.com/phalcon/cphalcon/milestones/2.0.0 ?
https://github.com/phalcon/cphalcon/issues?q=is%3Aopen+is%3Aissue+2.0.0 ?

**Comment by sandeepone** [comment] 2015-01-19 20:52
:+1:

**Comment by dschissler** [comment] 2015-01-19 21:03
>  I've added a new tag to the incubator some days ago as you requested,

@phalcon I must have missed that since I was commenting on an issue that had already been closed.

**Comment by dschissler** [comment] 2015-01-19 21:24
> Incubator, it seems to me, could be a such project from where ideas can be borrowed into to the upstream.

That seems to be its purpose now but I think that there is another type of code that isn't currently being addressed.  Lets say for example that someone wanted to use Zephir and Phalcon to create some Google API code.  Then the Incubator or cphalcon would not be suitable for this since external changes could easily break previously working code.  I think that it would be nice to have a phalcon-extra-php and phalcon-extra-zephir repository that allowed for people to contribute this kind of code.  So it could be used for any very particular code.  Also it could be used as a bridge between Phalcon 1 and 2 and it could be a place for people to perfect their PHP to Zephir porting skills.

**Comment by dschissler** [comment] 2015-01-19 21:48
I'm unsure how exactly how Zephir integration works and I'm wondering if there is any difference between using a custom Zephir class that inherits from Phalcon 1.3 or Phalcon 2.0 classes.  My point is that if its the same then having the incubator code in both Zephir and PHP could be quite interesting.  It would accomplish a number of things.  1) It would let people see equivalent working PHP and Zephir, 2) It would allow people to create a development and build process around compiling custom Zephir code, 3) It wouldn't strand anyone on Phalcon 1.

Perhaps incubator could be renamed to incubator-php and a new incubator-zephir created.  I would love to be able to compile a Zephir based Incubator extension into my [Webird](https://github.com/perchlayer/webird) project.  Already Webird has a lot of integration examples (in this manner; docker, webpack, gulp, phalcon, ratchetphp) and a Zephir build process for a Hello World one would be quite nice.

**Comment by ovr** [comment] 2015-01-20 11:55
@phalcon 
1 Merge..
Before this issue, you didnt merge any code for 6 days in phalcon 2.0 branch, but after this issue
n request (3-5) was merged

Maybe you were busy or etc but you need to organize project progress without you
Try to be a good project manager, think like manager, not a good developer

You need to create active group who can merge and will contribute
When PR is not merged, it's not good news for contributor
> Sometime when I create PR and it's not merged for 1 >= days, I start think that it's not a good project and i am very angry with this fact

But we are trying to find "how to get better progress"

2 Phalcon account
Phalcon it's not 1 person, and answers may be different as I saw

3 Phalcon organization
Suggest to split Phalcon 2 to another project like Phalcon 2 and move it to organization phalcon-framework for an example

(Phalcon 2 sources without c-code) /phalcon-framework/phalcon2
(Phalcon 2 ext sources) /phalcon/cphalcon - `2.0.0 branch`

4 I am going to finish Zephir site in few weeks when I will be free
1. Can i host it on my server? (It's will be after updated by https://github.com/ovr/github-webhook-service)


good manager != good developer
And you need to be a good manager ;)

**Comment by phalcon** [comment] 2015-01-20 13:55
@ovr That is exactly what I'm talking about, accommodate the project to your own vision of how things should work, none of those ideas/complains fix the real problems or address our real priorities, they just accommodate the project to the vision of how things must work to you. Please tell me how change the framework repository name or don't use the @phalcon account fix bugs or motivate others to implement missing features, how?

This project does need good developers, developers that can fix bugs, implement features and tests, this project does not need a manager. 

If you need someone to tell you what to do, I'm going to tell you, just pick up a bug posted here on Github, ask for information about how to reproduce it, work on a fix and submit a PR to fix it. 

Just take a look at the Zephir repo, many issues are marked as [bugs](https://github.com/phalcon/zephir/issues), and they're waiting for good developers to address them, not by a manager, same here in Phalcon.

**Comment by ovr** [comment] 2015-01-20 14:24
@phalcon 
You didnt answer on my questions for the site

> 4 I am going to finish Zephir site in few weeks when I will be free
1. Can i host it on my server? (It's will be after updated by https://github.com/ovr/github-webhook-service)

refs https://github.com/phalcon/zephir/issues/706
![](https://www.dropbox.com/s/al2v277gpd4sd61/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-01-20%2023.23.03.png?dl=0)

**Comment by maxgalbu** [comment] 2015-01-20 18:21
I don't have strong opinions on these subjects (I don't agree nor disagree), what I can suggest to "enchance" development is start with little things:

- a contribution guide (or roadmap) could be useful. it's hard to see the general picture from an external POV.
 - Should we write unit-tests or php-tests?
 - Should we stop contributing to 1.3?
 - What classes are missing in phalcon 2? An issue with a checklist can show at a glance what's missing and what's done.
 - Do you accept new features on phalcon 2? A new branch could be created (2.0.future) and merged with 2.0.0 when necessary)
 - (what am I missing?)

- promote some user to work with the issues and pull request, labelling, closing them when it's necessary, and assign them if work is to be done (this is already being done in the zephir repository)

**Comment by maxgalbu** [comment] 2015-01-21 20:12
Just found the page with what's missing with phalcon 2: https://github.com/phalcon/cphalcon/wiki/Progress-2.0

Can I convert it to an issue with a checklist so it can be milestone'd for 2.0.0?

**Comment by sergeyklay** [comment] 2015-01-21 22:08
@maxgalbu 
we can create a wiki page with using github checkboxes. for example:
```
- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> are supported
- [x] list syntax is required (any unordered or ordered list supported)
- [x] this is a complete item
- [ ] this is an incomplete item
```
- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> are supported
- [x] list syntax is required (any unordered or ordered list supported)
- [x] this is a complete item
- [ ] this is an incomplete item

**Comment by sergeyklay** [comment] 2015-01-21 22:13
@maxgalbu 
author will have such page:
![selection_024](https://cloud.githubusercontent.com/assets/1256298/5846318/7939e4ba-a1cb-11e4-95ab-2a4872dab1f0.png)

**Comment by maxgalbu** [comment] 2015-01-21 22:36
yes that's exactly what I'd like to create :+1:

**Comment by maxgalbu** [comment] 2015-01-21 22:47
@sergeyklay an issue is better in my opinion because of some reasons:
- you can comment in the issue, but not in the wiki
- you can put it into a milestone so it doesn't get forgotten (like that wiki page)
- you can see the status from the issue list: https://cloud.githubusercontent.com/assets/2723/3717240/ceba5cb0-1622-11e4-82e1-9e8bab0271a4.png

**Comment by trentramseyer** [comment] 2015-01-21 23:11
Aren't their Scrum/Project managers like Scrumdo that track your github bugs for you?

**Comment by sergeyklay** [comment] 2015-01-23 22:09
Personally, I don't think that this issue is solved and should be closed.
@phalcon @andresgutierrez  Please don't close this issue, untill it's obvious that the issue is solved.

**Comment by 7thcubic** [comment] 2015-01-24 02:00
Actually, i kind of agree on one thing.
For now what ever bugs/issue we fix is just pulling directly from the issue list. So it will be great to actually know what is needed for 2.0 to be pushed out as stable asap.

I am working on a production project based of 2.0, so any time i hit a snag i make changes. Sure they might not suit the main cphalcon, but as a new user of phalcon i have no idea whether the change i made was indeed fixing any bugs in the first place.

I love the fact that phalcon is based on c, as i previously had thought of working on something similiar. With the addition of zephir, it made things even easier.

The things is piorities, and i agree we have to push out 2.0 asap, at least into stable beta or w/e.
All these workflow changes can be discussed as the community becomes more active/mature together.

Even right now i am contemplating on changing some major things in 2.0, like adding a root class, much like yii's object class, or something similar that we can start enforcing a strict param, not even sure this is where phalcon wants to go.
Also for crypt, base64_encode? shouldn't that be string helper? 

The list goes on, again priorities.

It will be nice if we have a specific list of things that is broken and that needs fix.

**Comment by serebro** [comment] 2015-01-25 12:42
+1

**Comment by nkt** [comment] 2015-01-25 18:26
Actually Symfony is not indicator of the great workflow. There are many PRs that waiting 1+ year for being to merge.
But I'm really :+1: about convert Zephir and Phalcon into it's own organizations. Maybe GitHub support could convert Phalcon as user to organization. For Zephir already exists zephir-lang organization.

**Comment by cvsguimaraes** [comment] 2015-01-25 23:25
@nkt :+1:  for organizations

**Comment by salarmehr** [comment] 2015-05-16 12:09
+10 for @sergeyklay  first post.

 Nikolaos Dimopoulos (@niden) were very active here. Did he abandoned phalcon?

**Closed** 2015-08-29 07:56 UTC

**Comment by sergeyklay** [comment] 2017-03-14 22:13
done
