### ISSUE TITLE
Phalcon 4, session manager broken with PHP 7.4 (works with PHP 7.2)

### ISSUE THREAD

**Issue by kuhma** [phalcon/cphalcon#14933] opened 2020-03-27 11:22 UTC
PHP version: 7.4.4
Phalcon version: 4.0.5
Installation method : PECL / from sources

Issue: Uncaught Phalcon\Session\Exception: The session adapter is not valid in phalcon/Session/Manager.zep:323

Phalcon\Session\Manager::getAdapter always returns null.

```
<?php

namespace Services;

use Phalcon\Session\Adapter\Libmemcached;
use Phalcon\Session\Manager;
use Phalcon\Storage\SerializerFactory;
use Phalcon\Storage\AdapterFactory;

class Session extends Manager {

	public function __construct() {
 		$serializerFactory = new SerializerFactory();
		$factory = new AdapterFactory($serializerFactory);
		$sessionAdapter = new Libmemcached($factory, [
			'servers' => [
				[
					'host' => 'memcached',
					'port' => 11211,
					'weight' => 1,
				],
			],
			'client' => [],
			'lifetime' => 3600,
		]);

		$this->setAdapter($sessionAdapter);
		// class_implements($sessionAdapter) => [ SessionHandlerInterface ]
		// $this->getAdapter() => null
	}

}
```

This code works with PHP 7.2

**Comment by ruudboon** [comment] 2020-05-31 15:34
@kuhma I'm not able to reproduce this error. Can you drop the output of php -m for me?

**Comment by Jurigag** [comment] 2020-07-29 13:56
I am able to reproduce this, have the same error on php 7.4 when using Noop adapter. Interestingly i try do do something weird like override method setAdapter in manager:

```
    public function setAdapter(\SessionHandlerInterface $adapter): ManagerInterface
    {
        var_dump($adapter instanceof \SessionHandlerInterface);
        return parent::setAdapter($adapter);
    }
```

Then it works.

**Comment by niden** [comment] 2021-04-05 18:37
@kuhma Unfortunately I cannot reproduce this. PHP  7.4.16

Have a look at this PR and files

https://github.com/phalcon/cphalcon/pull/15376/files

I have the extended class (for the manager) and I get the adapter (and set it) just fine.

**Comment by niden** [comment] 2021-04-10 16:22
I could not reproduce this so closing for now.

I have added tests for this in https://github.com/phalcon/cphalcon/pull/15376

**Closed by niden** 2021-04-10 16:22 UTC
Labels: 5.0, bug, external dependency, status: low
