### ISSUE TITLE
[2.0.2] using \Phalcon\Mvc\Model\MetaData\Apc throws exception on load

### ISSUE THREAD

**Issue by ivan-ivakic** [phalcon/cphalcon#10446] opened 2015-05-30 21:05 UTC
I'm trying to migrate working application code from 1.3.2 to 2.0.2 and using \Phalcon\Mvc\Model\MetaData\Apc throws an exception when grabbing data from apc.

Running basic php5-fpm, nginx, mysql app.

Upon entity save I get the following:

```
exception_error_handler(integer(0), string('Undefined index: 1 in phalcon/mvc/model/metadata.zep on line 288'), string('someFolder/library/Model.php'), integer(0), array(2))

Phalcon\Mvc\Model\MetaData->readMetaDataIndex(object, integer(0))
```

```
php -v
PHP 5.4.41-1~dotdeb+7.1 (cli) (built: May 15 2015 10:59:59)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.3.2, Copyright (c) 2002-2015, by Derick Rethans
```

Manually grabbing apc entry gives something like:

```php
array (size=11)
  'type' => string 'user' (length=4)
  'key' => string '$PMM$goldfishmeta-metacontentmodel-meta_content' (length=47)
  'value' => 
    array (size=11)
      0 => 
        array (size=8)
          0 => string '__id' (length=4)
          1 => string 'id' (length=2)
          2 => string 'scope' (length=5)
          3 => string 'name' (length=4)
          4 => string 'type' (length=4)
          5 => string 'content' (length=7)
          6 => string 'contentDefault' (length=14)
          7 => string 'useDefault' (length=10)
      1 => 
        array (size=1)
          0 => string '__id' (length=4)
      2 => 
        array (size=7)
          0 => string 'id' (length=2)
          1 => string 'scope' (length=5)
          2 => string 'name' (length=4)
          3 => string 'type' (length=4)
          4 => string 'content' (length=7)
          5 => string 'contentDefault' (length=14)
          6 => string 'useDefault' (length=10)
      3 => 
        array (size=8)
          0 => string '__id' (length=4)
          1 => string 'id' (length=2)
          2 => string 'scope' (length=5)
          3 => string 'name' (length=4)
          4 => string 'type' (length=4)
          5 => string 'content' (length=7)
          6 => string 'contentDefault' (length=14)
          7 => string 'useDefault' (length=10)
      4 => 
        array (size=8)
          '__id' => int 0
          'id' => int 2
          'scope' => int 2
          'name' => int 2
          'type' => int 2
          'content' => int 6
          'contentDefault' => int 6
          'useDefault' => int 0
      5 => 
        array (size=2)
          '__id' => boolean true
          'useDefault' => boolean true
      8 => string '__id' (length=4)
      9 => 
        array (size=8)
          '__id' => int 1
          'id' => int 2
          'scope' => int 2
          'name' => int 2
          'type' => int 2
          'content' => int 2
          'contentDefault' => int 2
          'useDefault' => int 1
      10 => 
        array (size=0)
          empty
      11 => 
        array (size=0)
          empty
      12 => 
        array (size=5)
          'id' => string '' (length=0)
          'scope' => string '' (length=0)
          'name' => string '' (length=0)
          'type' => string '' (length=0)
          'useDefault' => string '1' (length=1)
  'num_hits' => int 3
  'mtime' => int 1433013752
  'creation_time' => int 1433013752
  'deletion_time' => int 0
  'access_time' => int 1433014617
  'ref_count' => int 0
  'mem_size' => int 11632
  'ttl' => int 86400
```

If there is any more information that you require please ask.

Thanks!

**Comment by ivan-ivakic** [comment] 2015-05-31 09:28
I've tried to remove one table at a time in an attempt to isolate the problematic table but no luck. I've left one plain table.

Apc dump is:
```php
array (size=11)
  'type' => string 'user' (length=4)
  'key' => string '$PMM$goldfishmeta-analytics-analytics' (length=37)
  'value' => 
    array (size=11)
      0 => 
        array (size=7)
          0 => string '__id' (length=4)
          1 => string 'id' (length=2)
          2 => string 'analyticsKey' (length=12)
          3 => string 'analyticsCode' (length=13)
          4 => string 'anonymizeIp' (length=11)
          5 => string 'forceSSL' (length=8)
          6 => string 'active' (length=6)
      1 => 
        array (size=1)
          0 => string '__id' (length=4)
      2 => 
        array (size=6)
          0 => string 'id' (length=2)
          1 => string 'analyticsKey' (length=12)
          2 => string 'analyticsCode' (length=13)
          3 => string 'anonymizeIp' (length=11)
          4 => string 'forceSSL' (length=8)
          5 => string 'active' (length=6)
      3 => 
        array (size=7)
          0 => string '__id' (length=4)
          1 => string 'id' (length=2)
          2 => string 'analyticsKey' (length=12)
          3 => string 'analyticsCode' (length=13)
          4 => string 'anonymizeIp' (length=11)
          5 => string 'forceSSL' (length=8)
          6 => string 'active' (length=6)
      4 => 
        array (size=7)
          '__id' => int 0
          'id' => int 2
          'analyticsKey' => int 2
          'analyticsCode' => int 2
          'anonymizeIp' => int 0
          'forceSSL' => int 0
          'active' => int 0
      5 => 
        array (size=4)
          '__id' => boolean true
          'anonymizeIp' => boolean true
          'forceSSL' => boolean true
          'active' => boolean true
      8 => string '__id' (length=4)
      9 => 
        array (size=7)
          '__id' => int 1
          'id' => int 2
          'analyticsKey' => int 2
          'analyticsCode' => int 2
          'anonymizeIp' => int 1
          'forceSSL' => int 1
          'active' => int 1
      10 => 
        array (size=0)
          empty
      11 => 
        array (size=0)
          empty
      12 => 
        array (size=6)
          'id' => string '' (length=0)
          'analyticsKey' => string '' (length=0)
          'analyticsCode' => string '' (length=0)
          'anonymizeIp' => string '0' (length=1)
          'forceSSL' => string '0' (length=1)
          'active' => string '0' (length=1)
  'num_hits' => int 2
  'mtime' => int 1433063833
  'creation_time' => int 1433063833
  'deletion_time' => int 0
  'access_time' => int 1433063838
  'ref_count' => int 0
  'mem_size' => int 11632
  'ttl' => int 86400
array (size=11)
  'type' => string 'user' (length=4)
  'key' => string '$PMM$goldfishmap-analytics' (length=26)
  'value' => 
    array (size=2)
      0 => null
      1 => null
  'num_hits' => int 2
  'mtime' => int 1433063833
  'creation_time' => int 1433063833
  'deletion_time' => int 0
  'access_time' => int 1433063838
  'ref_count' => int 0
  'mem_size' => int 1200
  'ttl' => int 86400
```

Maybe the value for ``` 'key' => string '$PMM$goldfishmap-analytics' (length=26)``` is somehow invalid but I get the same dump when app is ran on phalcon 1.3. and it is not failing.

Table structure
```dump
+---------------+--------------+------+-----+---------+----------------+
| Field         | Type         | Null | Key | Default | Extra          |
+---------------+--------------+------+-----+---------+----------------+
| __id          | int(11)      | NO   | PRI | NULL    | auto_increment |
| id            | varchar(50)  | NO   | MUL |         |                |
| analyticsKey  | varchar(250) | NO   | MUL |         |                |
| analyticsCode | varchar(250) | NO   |     |         |                |
| anonymizeIp   | tinyint(1)   | NO   |     | 0       |                |
| forceSSL      | tinyint(1)   | NO   |     | 0       |                |
| active        | tinyint(1)   | NO   |     | 0       |                |
+---------------+--------------+------+-----+---------+----------------+
```

Class Analytics inherits \Phalcon\Mvc\Model implementing one extra method to populate the values in model, basically foreach attribute assign value from input array.

**Comment by andresgutierrez** [comment] 2015-05-31 18:21
Can you try again using Phalcon 2.0.3? Compiling from 2.0.x branch

**Comment by ivan-ivakic** [comment] 2015-05-31 19:19
No luck, still fails on https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/mvc/model/metadata.zep#L276

Are you able to reproduce the problem?

Can I help you with anything with any dumps or something?

Currently I'll use Memcached but it would be nice if APC would work :)

**Comment by andresgutierrez** [comment] 2015-06-01 13:01
Are you using database introspection?

**Comment by ivan-ivakic** [comment] 2015-06-01 14:57
Not that I'm aware of :) I've just registered a service like follows:
```php
$di->set('modelsMetadata', function () use ($di) {
  return new \Phalcon\Mvc\Model\MetaData\Apc(array(
    'lifetime' => 86400,
    'prefix'   => 'test',
  ));
});
```
Tried with ```setShared``` also, no luck.

Error message is: "The meta-data is invalid or is corrupt" (same line).

**Comment by andresgutierrez** [comment] 2015-06-02 02:27
I can't reproduce the issue, I'm using the following script:

```php
<?php

namespace Some;

use Phalcon\DI,
    Phalcon\Db\Column,
    Phalcon\Mvc\Model,
    Phalcon\Events\Manager as EventsManager,
    Phalcon\Db\Adapter\Pdo\MySQL as Connection,
    Phalcon\Mvc\Model\Manager as ModelsManager;

$eventsManager = new EventsManager();

$di = new DI();

$connection = new Connection(array(
    "host"     => "localhost",
    "username" => "root",
    "password" => "",
    "dbname"   => "phalcon_test",
));

$connection->setEventsManager($eventsManager);

$eventsManager->attach('db',
    function ($event, $connection) {
        switch ($event->getType()) {
            case 'beforeQuery':
                echo $connection->getSqlStatement(), "\n";
                break;
        }
    }
);

$modelsManager = new ModelsManager();
$modelsManager->setDi($di);

$di->set('modelsMetadata', function () use ($di) {
    return new \Phalcon\Mvc\Model\MetaData\Apc(array(
        'lifetime' => 86400,
        'prefix'   => 'test',
    ));
}, true);

$di['db'] = $connection;
$di['modelsManager'] = $modelsManager;

class Robots extends Model
{
    public function initialize()
    {
        $this->hasMany('id', 'Some\RobotsParts', 'robots_id', [
            'alias' => 'parts',
            'params' => ['conditions' => 'parts_id = 0']
        ]);
    }
}

class RobotsParts extends Model
{

}

$robot = Robots::findFirst();
foreach ($robot->parts as $robotPart) {
    echo $robotPart->id, PHP_EOL;
}

```

**Comment by andresgutierrez** [comment] 2015-08-23 23:40
@ivan-ivakic

**Comment by sakarit** [comment] 2015-10-09 09:22
I have this same problem. Using nginx, php-fpm 5.4.45, mysql and phalcon 2.0.8. After metadata is saved it can not be read the next time (page reload). Apc dump of the data looks like valid but I can not say for sure.

Also no problems running php in cli (I have apc enabled in cli).

Have you found a solution?

**Comment by ivan-ivakic** [comment] 2015-10-09 10:08
Unfortunately I haven't found a solution but I'm guessing something in my app structure is confusing the apc, note that I don't experience the issue on the latest phalcon version.

Haven't found an isolated reason so I'm unable to provide script to reproduce at this time. Will look into it the first chance I get but I don't think it will be any time soon. Sry

**Comment by sakarit** [comment] 2015-10-09 12:59
Okay I found a workaround. Seems that there is something wrong with the internal _metaData array of the Apc class. It's somehow weirdly broken.. never seen this before. If you take a row from the array with a index that is ODD id does not work. That's why it works when the first row is fetched (index = 0), but not when fetching the second (index = 1).

I think it's because the apc version in my instance is somehow broken although it's the newest available version. Anyway I googled this error and seems that it's happening to other people too.

It can be fixed just extending the the Phalcon's Apc class and casting the data from apc_fetch to an array. Somehow it rearranges the broken array to a working one.

`
<?php

namespace My\Mvc\Model\Metadata;

class Apc extends \Phalcon\Mvc\Model\MetaData\Apc
{
  public function read($key)
  {
    $data = parent::read($key);

    if (is_array($data)) {
      return (array) $data;
    }

    return $data;
  }
}
`

**Comment by dugwood** [comment] 2015-11-20 09:08
Just hit the same issue upgrading from 2.0.0 to 2.0.3 (not tested 2.0.8 because of so many SQL statements to change after the BIG change in 2.0.4).

My index missing is 13, not 1. I'm looking into the code to find out why there's a 13th element.

**Comment by dugwood** [comment] 2015-11-20 09:15
OK, my issue was that I was overriding the method getMetaData() and there was no entry for 12 and 13 (added in 2.0.3).

**Comment by booldog** [comment] 2015-11-29 20:06
got same problem after migration from 1.3 to 2.09. apc works fine except models metadata. changed to memcache and is works so far.

**Comment by dugwood** [comment] 2015-11-30 07:02
@booldog Memcached is very slow compared to APC, so you should go back to APC as soon as the issue is resolved. Memcached is great for storing a lot of data, but metadata is very little info to store, and accessed far often.

**Comment by booldog** [comment] 2015-11-30 13:12
i know that memcached is slow, but what we can do for now:)? only redis is alternative.

**Comment by sergeyklay** [comment] 2016-09-03 08:27
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Closed by sergeyklay** 2016-09-03 08:27 UTC
Labels: Need script to reproduce
