### ISSUE TITLE
[BUG]: Model - Update - Postgres Bool False/True Not Working Phalcon 4 [temp fix at the end]

### ISSUE THREAD

**Issue by tidytrax** [phalcon/cphalcon#14722] opened 2020-01-17 03:52 UTC
When I try to save a boolean value on postgresql, it does not save;

$model->getMessages() "return field1,field2,field3.... is required

Do not work If I use true/false

`$find = Model::findFirst('id='.$id);
`
> Return Bool fine
The fields area NOT NULL DEFAULT true/false;

```
["enabled"]=> | bool(true)
| ["allowed"]=> | bool(true)
["restrict"]=>|  bool(false)


```
**Do not Work**

Throw required field allowed and enabled
```
 $find->label = 'Test';
 $find->save();
```
_**Manually**_. 

**Do not Work**  If i want to change the value or auto update the column;

```
$find->enabled= false
$find->allowed= true.
$find->restrict = false
$find->save();

```
**Work**

```
$find->enabled= 0
$find->allowed= 1....
$find->restrict = 0
$find->save();
```

**Work On Create**  

Return values empty on object after create.
And i don't need to set all fields values, does not set bool field as required

```
$find= new Model(); 
$find->enabled= false
$find->allowed= true.
$find ->save();
```

`$find->assign(['test' => false])->update();`
Works if I use 0/1
`$find->assign(['test' => 0,])->update();`

Config
Phalcon 4.0.2 / PHP 7.4.1 / Postgresql 12.1/Nginx 1.16.1

**Comment by tidytrax** [comment] 2020-01-17 10:09
just that a notice, if ask the values again even with useDynamicUpdate(true)

**Comment by tidytrax** [comment] 2020-01-17 10:20
Work  $model = new Model(); 
Return values empty on object.

```
$model ->scene_nav = true;
$model ->save();
```

**Comment by tidytrax** [comment] 2020-01-22 19:28
Have some way to return all as string, something to turn around ?

**Comment by tidytrax** [comment] 2020-01-24 23:12
One more info, the fields does not appear on getChangedFields

**Comment by ruudboon** [comment] 2020-01-25 06:21
@tidytrax 
Do you have a database schema for me?

**Comment by ruudboon** [comment] 2020-01-25 16:58
I tried this on Postgres 12 but unable to reproduce this behaviour.  Can you share your model?

**Comment by tidytrax** [comment] 2020-01-25 17:58
they came with boolean type if i do a $resultset->toArray();
They came correct, they do not appear on changed fields.

Same result as before.
```
$model = UserSession::findFirst(['hydration' => Resultset::HYDRATE_RECORDS]);
var_dump($model->toArray());
```

> id: (integer) 2 
> url: (string) "/logout"
> ip: (string) "10.0.2.2"
> force_logout: (boolean) false 
> remember: (boolean) false 
> 

```
$model->id = 1;
$model->save();
var_dump($model->getMessages());
```

> Phalcon\MessagesMessage (object) [Object ID #124][5 properties]
> code:protected: (integer) 0 
> field:protected: (string) "force_logout"
> message:protected: (string) "force_logout is required"
> type:protected: (string) "PresenceOf"
> metaData:protected: 
> (array) [0 elements]
> 1: 
> Phalcon\MessagesMessage (object) [Object ID #123][5 properties]
> code:protected: (integer) 0 
> field:protected: (string) "remember"
> message:protected: (string) "remember is required"
> type:protected: (string) "PresenceOf"
> metaData:protected: 
> (array) [0 elements]



_**I didn't updated this 2 fields, they are filled, but ask again, and if i try**_
```
$model->force_logout = false/true: //**fail**
$model->force_logout = 0/1 //**works**.
```

**This is fine.**
`var_dump($model->getChangedFields());exit;`

> (array) [2 elements]
> 0: (string) "session_id"
> 1: (string) "updated"
> 

So always when i want to update a record i have to pass all boolean columns as int again, even if they are already filledup, **phalcon does not accept to save bool,**

**How i have to do to update a record on database or save.**

```
$model = UserSession::findFirst(['hydration' => Resultset::HYDRATE_RECORDS]);
$model->id = 1;
$model->force_logout = ( int) $model->force_logout(already has a value);
$model->remember = (int) $model->remember(already has a value);
$model->save();
```

**Comment by tidytrax** [comment] 2020-01-25 17:59
> I tried this on Postgres 12 but unable to reproduce this behaviour. Can you share your model?

```
CREATE TABLE "auth"."user" (
  "id" serial8 NOT NULL,
  "url" text COLLATE "pg_catalog"."default" NOT NULL,
  "ip" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "force_logout" bool NOT NULL DEFAULT false,
  "remember" bool NOT NULL DEFAULT false,
  "status" numeric(2) NOT NULL DEFAULT 1,
  "updated" timestamp(6) NOT NULL,
  "created" timestamp(6) NOT NULL
)

```

**Comment by tidytrax** [comment] 2020-01-25 18:00
Configuration of model, i already try all on options.
 ```
Model::setup([
            'forceCasting' => true,
            'castOnHydrate' => true
        ]);
```
`$this->useDynamicUpdate(true);`

**Comment by tidytrax** [comment] 2020-01-25 18:02
On phalcon 3 the last one, works fine!

**Comment by tidytrax** [comment] 2020-01-25 18:03
On phalcon 3.4.4 works fine, i'm trying to migrate an aplication to the Phalcon 4, works fine all, less postges bool

**Comment by ruudboon** [comment] 2020-01-25 18:05
The hydrate stuff is not for this issue.

**Comment by tidytrax** [comment] 2020-01-25 18:08
I know sorry only saw the wrong tab after reply

**Comment by tidytrax** [comment] 2020-01-25 18:59
You was able to reproduce the behavior?

**Comment by tidytrax** [comment] 2020-01-25 22:59
$this->modelsMetadata->getDataTypesNumeric($model);

id: (boolean) true 
force_logout: (boolean) true 
remember: (boolean) true 
status: (boolean) true 

 $this->modelsMetadata->getDataTypesNumeric($model);

> id: (integer) 14 
> url: (integer) 6 
> ip: (integer) 2 
> force_logout: (integer) 8 
> remember: (integer) 8 
> status: (integer) 3 
> created: (integer) 17 

And on cache metadata if enabled, 
they came as string on default value 'false'/'true' instead of false/true

**Comment by tidytrax** [comment] 2020-01-25 23:06
Could be on Phalcon\MVC\Model.zep

Line **4594**, value is returned as string on metadata 'false' !== false
`value !== defaultValues[field]
`
Line **4599** since the field is numeric but the value is not

```
if !is_numeric(value) {
    let isNull = true;
}
```

**Comment by tidytrax** [comment] 2020-01-25 23:15
@ruudboon  Worked if i go to meta-app_models_model.php and removed from int type

>   array (
>     'user_session_id' => true,
>     'force_logout' => true, //removed
>     'remember' => true, //removed
>     'status' => true,
>   ),

Works
```
$find = Model::findFirst();
$find-.save();
```
//Works
```
$find->remember = true;
$find->save();
```

**Comment by tidytrax** [comment] 2020-01-26 00:45
Fix for who has the same problem, must use cache on model metadata.
Must use column anotation, does not matter the column type, so can do with phalcon devtools, that does not generate column type boolean on boolean.

```
$di->setShared('modelsMetadata', function () {
    $options = [
        'metaDataDir' => PATH_CACHE_METADATA . DS
    ];
    $metadata=new \Phalcon\Mvc\Model\Metadata\Stream($options);
    $metadata->setStrategy(new Annotations()); //set here
    return $metadata;
});

```

**Comment by ruudboon** [comment] 2020-01-26 07:54
@tidytrax Thnx! This is some great research and really helpful.

**Comment by tidytrax** [comment] 2020-01-26 13:17
Thank you @ruudboon i'm using about 7 years phalcon, i will as help as i can.
And this bug, is really a killing.

**Adapter\Pdo\Postgresql.zep**
Line 207 bool is treat as smallint, so is checked as numeric.

```
 /**
* BOOL
 */
let definition["type"] = Column::TYPE_BOOLEAN,
definition["isNumeric"] = true,
definition["bindType"] = Column::BIND_PARAM_BOOL;

break;
```

So a fix, who have the same problem and want to use Without Annotation strategy(has bugs reported already on devtools)

So the fix, extends PDO, and change describe column, clear metadata cache, remove annotation.
And now you can user

```
$model->field = true
$model->field = false;
```

> Also does not annoying asking all fields again when you update, if you want to gain performance, you can rewrite all function or use parent as source and change.


```
class Postgres extends \Phalcon\Db\Adapter\Pdo\Postgresql
{

    public function describeColumns(string $table, string $schema = null) :array
    {
        $columns = parent::describeColumns($table, $schema);
        
        foreach ( $columns as $key => $column ) {
            if ( $column->isNumeric() AND $column->getType() === 8 ) {
                $columns[$key] = new Column($column->getName(), ['type' => Column::TYPE_BOOLEAN, 'default' => ($column->getDefault() === 'false') ? false : true]);
            }
        }
        return  $columns;
    }
}
```

Service should look like something...

```
$di->setShared('modelsMetadata', function () {
    $options = [
        'metaDataDir' => PATH_CACHE_METADATA . DS
    ];
    $metadata=new \Phalcon\Mvc\Model\Metadata\Stream($options);
    return $metadata;
});

$di->setShared('db', function () {
    $config = $this->getConfig();
    $dbConfig = $config->database->toArray();
    $adapter = $dbConfig['adapter'];
    unset($dbConfig['adapter']);

    $class = '\System\Postgres';
    $connection = new $class($dbConfig);
    return $connection;
});

```

**Comment by tidytrax** [comment] 2020-01-26 13:22
Another thing  $string = 'false' ( string) always true = (bool) $string 
So the default value cannot became as string.

**Comment by tidytrax** [comment] 2020-01-26 16:57
Why the problem does not occur on phalcon 3.4
No numeric type is set for smallint(tinyint) or boolean
[postgresql.zep#L209](https://github.com/phalcon/cphalcon/blob/3.4.x/phalcon/db/adapter/pdo/postgresql.zep#L209
)
```
if memstr(columnType, "smallint(1)") {
    /**
     * Smallint(1) is boolean
     */
    let definition["type"] = Column::TYPE_BOOLEAN,
    definition["bindType"] = Column::BIND_PARAM_BOOL;
} elseif memstr(columnType, "bool") {
    /**
     * Boolean
     */
    let definition["type"] = Column::TYPE_BOOLEAN,
    definition["size"] = 0,
    definition["bindType"] = Column::BIND_PARAM_BOOL;
```

**Comment by niden** [comment] 2020-01-26 19:47
Resolved in https://github.com/phalcon/cphalcon/pull/14781

Thank you again @tidytrax for the report, investigation and fix

**Closed by niden** 2020-01-26 19:47 UTC
Labels: 4.0.4, bug, status: high

**Comment by tidytrax** [comment] 2020-01-26 20:41
i will keeping test v4.

**Comment by maravenaf** [comment] 2020-04-13 20:09
excelent thahk!...
