### ISSUE TITLE
phalcon/mvc/model/manager::getRelationRecords() bug

### ISSUE THREAD

**Issue by djfd** [phalcon/cphalcon#11755] opened 2016-05-07 02:58 UTC
Hi,

please check https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/manager.zep#L1279

``` zephir
placeholders["APR" . refPosition] = record->readAttribute(field)
```

this have to be:

``` zephir
placeholders["APR" . refPosition] = record->readAttribute(fields[refPosition])
```

instead.

thanks

**UPD**
as of 2018-02-06, line numbers get changed but the bug is still here
[https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/manager.zep#L1347](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/manager.zep#L1347)

**Comment by sergeyklay** [comment] 2016-05-09 13:41
@djfd  Could you please provide a small script to reproduce the issue you have described here?

**Comment by djfd** [comment] 2016-05-09 15:02
Hi,

```
class Language extends Model {
    protected $lang;
    protected $locale;
    // ... other data fields
    function init()
    {
        hasMany(['lang', 'locale'], 'LanguageI18n', ['from_lang', 'from_locale'], ['alias'=>'Translations']);
    }
}
class LanguageI18n extends Model {
    protected $from_lang;
    protected $from_locale;
    protected $lang;
    protected $locale;
    // ... other data fields
    function init()
    {
        belongsTo(['from_lang', 'from_locale'], 'Language', ['lang', 'locale'], ['alias'=>'Origin']);
        belongsTo(['lang', 'locale'], 'Language', ['lang', 'locale'], ['alias'=>'Target']);
    }
}
```
then
```$tlist = Language->Translations;``` produces nothing using current codebase. After fixing as above all get working fine.

PS. I cannot recall exactly what the code I did use when detected that. Please let me know if example above is sufficient to reproduce.

thanks

**Comment by djfd** [comment] 2016-05-10 22:10
@sergeyklay 
May I ask you off the topic question? Are pull requests here need to be done in zephir language or plain php is suitable too?
thanks

**Comment by Jurigag** [comment] 2016-05-10 22:27
Both. Zephir for phalcon code, php for tests.

**Comment by sergeyklay** [comment] 2018-05-08 05:12
Unable to reproduce using `3.4.x` branch. See #13370. I'm closing this issue but if I have made an oversight, please do get back in touch. Thanks

**Closed by sergeyklay** 2018-05-08 05:12 UTC
Labels: Not verified
