### ISSUE TITLE
Phalcon 4 issue with TINYINT(1)

### ISSUE THREAD

**Issue by daniel18387** [phalcon/cphalcon#14708] opened 2020-01-14 15:14 UTC
I have noticed an issue when saving records to tables in MySQL. Of the tables which have field columns with the data type TINYINT(1), I can see the values in the rows default to 1 when a row gets saved, regardless of the value given.

This only occurs when the mask is set to 1.

**Comment by ruudboon** [comment] 2020-01-14 15:17
Can you give us a dump of your database structure and some basic code to reproduce this?

**Comment by daniel18387** [comment] 2020-01-14 15:27
DB table `mp_kyc_documents`:
+--------------+---------------------+------+-----+---------+-------+
| Field        | Type                | Null | Key | Default | Extra |
+--------------+---------------------+------+-----+---------+-------+
| id           | bigint(20) unsigned | NO   | PRI | NULL    |       |
| user_id      | bigint(20) unsigned | NO   | MUL | NULL    |       |
| type         | tinyint(1) unsigned | YES  |     | 1       |       |
| status       | tinyint(1) unsigned | YES  |     | 1       |       |
| file_id      | bigint(20) unsigned | YES  |     | NULL    |       |
| created_on   | datetime            | YES  |     | NULL    |       |
| processed_on | datetime            | YES  |     | NULL    |       |
+--------------+---------------------+------+-----+---------+-------+

Code used:
```
$detail = [
    'id' => 123456,
    'userId' => 1234567,
    'type' => 2,
    'status' => 3,
];

$kycDocument = (new Models\MP\KycDocuments)
    ->setId($detail['id'])
    ->setUserId($detail['userId'])
    ->setType($detail['type'])
    ->setStatus($detail['status']);

$kycDocument->save();
```
After the save, both the `type` and `status` fields will set to `1`. This has occurred since our systems upgraded to version 4 yesterday.

**Comment by ruudboon** [comment] 2020-01-14 15:37
Thnx for the info.
We will investigate this. Looks like tinyint(1) is handled as boolean. 
If you have time could try to save with value 0 for type of status?

**Comment by daniel18387** [comment] 2020-01-14 15:50
You are correct. It's being treated as a boolean value but it shouldn't be. As you've pointed out, it can go all the way up to 127 when signed and 255 when unsigned. It's worth noting that the `(1)` is only a display width. It doesn't control the width of the integer. https://dev.mysql.com/doc/refman/8.0/en/integer-types.html

This has been brought up before on Phalcon too. See https://github.com/phalcon/cphalcon/issues/2012

**Comment by daniel18387** [comment] 2020-01-14 16:02
If anyone else is experiencing this issue, remove the mask from the integer data type to solve it your end before a fix is in place. i.e. Remove `(1)` from `TINYINT(1)` to leave a data type of `TINYINT`.

**Comment by niden** [comment] 2020-01-14 22:44
Resolved in https://github.com/phalcon/cphalcon/pull/14709

Thank you @daniel18387

**Closed by niden** 2020-01-14 22:44 UTC
Labels: 4.0.3, bug, status: medium

**Comment by Ruzgfpegk** [comment] 2020-01-27 05:15
On the other hand, those who used _TINYINT(1)_ as a _BOOLEAN_ (because declaring a column as _BOOL_ in MySQL Workbench outputs a _TINYINT(1)_) may have welcomed the v4.0.0 behavior.

Wouldn't a setting to specify the wished behavior be a better option in the long run?

**Comment by daniel18387** [comment] 2020-01-27 13:29
> On the other hand, those who used _TINYINT(1)_ as a _BOOLEAN_ (because declaring a column as _BOOL_ in MySQL Workbench outputs a _TINYINT(1)_) may have welcomed the v4.0.0 behavior.
> 
> Wouldn't a setting to specify the wished behavior be a better option in the long run?

That doesn't make sense. Phalcon should work with MySQL, not necessarily MySQL Workbench (Third party product). i.e. Follow MySQLs documentation. MySQL Workbench (Which I use) should adhere to the standards, as should Phalcon. Any other suggestion is pure conjecture.

**Comment by Ruzgfpegk** [comment] 2020-01-27 16:24
[MySQL Workbench](https://www.mysql.com/products/workbench/) is made by Oracle, so it's a first-party product (relative to MySQL Server).

The [documentation for the numeric types](https://dev.mysql.com/doc/refman/8.0/en/numeric-type-attributes.html) says indeed:
> The display width does not constrain the range of values that can be stored in the column.

But it also says just above:
> This optional display width may be used by applications to display integer values having a width less than the width specified for the column by left-padding them with spaces. (That is, this width is present in the metadata returned with result sets. **Whether it is used is up to the application.**)

If you agree that "let the application do what it wants with it" is a standard, as it's what's written in the MySQL docs, then it's precisely what I'm suggesting in order to avoid said conjectures.

In the same [documentation](https://dev.mysql.com/doc/refman/8.0/en/other-vendor-data-types.html) they mention the mapping they're doing from _BOOLEAN_ to _TINYINT_, which is what their other own product Workbench does (to _TINYINT(1)_) and how the DB works: if you _INSERT_ a _TRUE_ (without '') into a _TINYINT_ column it's understood (...and stored) as a 1.
This is an unfortunate choice on their end, because if you _INSERT_ a _TRUE_ you expect to _SELECT_ a _TRUE_ as well and there's no _CAST(column AS BOOLEAN)_ available either, but this what we have to deal with, and we have a chance to "adhere to the[ir] standards" by letting that choice "up to the application".

If I can make my position more clear, the same way we have a:
`\Phalcon\Mvc\Model::setup(['castOnHydrate' => true]);`
which is not enabled by default due to certain issues, we could have something like:
`\Phalcon\Mvc\Model::setup(['tinyintAsBool' => true]);`
for those using TINYINT this way and nobody would lose any functionality.

**Comment by daniel18387** [comment] 2020-01-28 02:02
Thank you for clarifying. 

While the above sounds like a good idea to cover all bases, it's also redundant with this now in place. I use both boolean and integer values with TINYINT, which as mentioned above MySQL advocates. However, it begs the question why Phalcon should be more restrictive when it already allows the functionality for both.

In my personal opinion, I would prefer Phalcon's product to be more flexible.
