### ISSUE TITLE
Alias for current model in static query() method

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#10840] opened 2015-08-26 10:07 UTC
I just wanna use static query method from my model to join related models and select columns. Both my models have same column(id), but i dont know how to set alias for model from which i selecting data and im not sure there are a way, when i use modelsManager i can just type it like:
 ->from(array("alias"=>"Namespace"))

Also i think when using ->joins with ::query() it should automtically resolve namespaces if i setted relations - now i still have to type full namespaces of related models.

Maybe just add parameter in Model::query("Model") which will be alias for this model in SQL Query ?

**Comment by andresgutierrez** [comment] 2015-08-26 23:40
Duplicate of https://github.com/phalcon/cphalcon/issues/10479

**Closed** 2016-06-09 21:08 UTC
