### ISSUE TITLE
Phalcon ORM writeAttribute when value is an associative array

### ISSUE THREAD

**Issue by wajdijurry** [phalcon/cphalcon#14021] opened 2019-04-27 11:50 UTC
When using ```$model->writeAttribute('field', ['a'=>'apply', 'b'=>'banana'])``` to write an associative array to an attribute in the model, the result is strange.

### Expected and Actual Behavior
Expected result:
```
$model->field = ['a'=>'apply', 'b'=>'banana']
```

Actual result:
```
$model->a = 'apple';
$model->b = 'banana';
```

This behavior happening when trying to write a new attribute to a model, and the value must be an associative array.

### Details

* Phalcon version: (`3.4.2`)
* PHP Version: (`7.2.15`)
* Operating System: Ubuntu 18.10
* Installation type: Docker

**Comment by zsilbi** [comment] 2019-04-27 15:39
I also noticed this yesterday when I was working on other Model related issues.
I have a work-in-progress PR for this in the 4.0.x branch here: https://github.com/phalcon/cphalcon/pull/14018

**Comment by zsilbi** [comment] 2019-05-02 11:31
I did some testing and this bug is confirmed, but only occurs when `field` in not defined as a property in `Model` because the problem is in `Model::__set()`.

For example:
```php
class Users extends Model
{
    public $id;
    public $name;
}
```

```php
$user = new Users();
$user->writeAttribute('whatEverUndefinedProperty', ['id' => 123, 'name' => 'My Name']);
// or
$user->whatEverUndefinedProperty = ['id' => 123, 'name' => 'My Name'];

print_r($user->toArray());
```
results in:
```php
Array
(
   [id] => 123
   [name] => My Name
)
```

**Comment by sergeyklay** [comment] 2019-05-02 12:05
Actually it is important _feature_ and we can not just remove this behavior from 3.x branch because:
- This behavior is documented
- Many developers rely on this behavior
- It will break existing applications

**Comment by zsilbi** [comment] 2019-05-02 12:23
@sergeyklay, I couldn't find this anywhere in the docs

**Comment by sergeyklay** [comment] 2019-05-02 12:35
As a far as I know for 4.x this should be changed in https://github.com/phalcon/cphalcon/pull/13677

**Comment by zsilbi** [comment] 2019-05-02 12:49
> As a far as I know for 4.x this should be changed in #13677

That PR did not solve this, the code on line 359 causes this issue.
https://github.com/borisdelev/cphalcon/blob/7b6cfe807674147e5186d2680277706766d95ac7/phalcon/mvc/model.zep#L359

**Comment by sergeyklay** [comment] 2019-05-02 13:02
Well, @wajdijurry pointed current issue for 
> Phalcon version: (`3.4.2`)

The main idea is (as I said before) that we cannot change this for the 3.x branch. I personally was a part in battles long in a months, as soon as we changed something in area of Model::`__set`/`__get` because it is most used feature. So theoretically we could change this behavior for the 4.x version (until the first beta is released), however I would like to see the real rationales for this and test coverage

**Comment by zsilbi** [comment] 2019-05-02 13:12
All right, I am writing tests now to cover these functions and the open issues related to them.

**Comment by wajdijurry** [comment] 2019-05-02 13:31
@sergeyklay what issue we are talking about ? I think it's a bug in Phalcon!
Why it is needed as this ? The logic says if I assigned an attribute to a model with an associative array, it should be assigned as it, not shifted up, right ?

**Comment by sergeyklay** [comment] 2019-05-02 13:45
As a far as I remember this feature was introduced in 2.x branch. So no, it is not a bug, it is well know behavior. This is why I said we can't this change for 3.x

**Comment by zsilbi** [comment] 2019-05-02 13:45
I think this function was meant to be working this way:

```php
class RobotsParts extends Model
{
    public function initialize()
    {
        $this->belongsTo('robots_id', Robots, 'id');
    }
}
```
If we set the related record as an array:
```php
$robotPart = new Models\RobotsParts();
$robotPart->robot = ['name' => 'TestRobotName'];

$robot = $robotPart->robot;

var_dump(get_class($robot));

print_r($robot->toArray());
```
The result should be:

```php
string(6) "Robots"

Array
(
   [name] => TestRobotName
)
```

**Comment by niden** [comment] 2019-05-11 22:23
Resolved in https://github.com/phalcon/cphalcon/pull/14035

**Closed by niden** 2019-05-11 22:23 UTC
Labels: Enhancement

**Comment by wajdijurry** [comment] 2020-01-31 21:30
Good job guys! Appreciate your effor
