### ISSUE TITLE
Session not working in 3.4, not saving objects

### ISSUE THREAD

**Issue by joeyhub** [phalcon/cphalcon#13652] opened 2018-12-11 08:42 UTC
I'm also putting in an object that implements serializable and I'm getting null back out when I read the session.

**Comment by joeyhub** [comment] 2018-12-11 08:48
PHP issue not phalcon.

**Comment by joeyhub** [comment] 2018-12-11 09:22
Gah not having a 404 handler by default so it goes to the default controller which has session destroy in it for debug really helps (faveicon hits it each time). On top of that some routing tutorials might set things up so an action gets called multiple times or something, I'm not sure.

**Comment by sergeyklay** [comment] 2018-12-11 22:12
@joeyhub Provide minimal script to reproduce the issue. Also we need some additional info

* Phalcon version: (`php --ri phalcon`)
* PHP Version: (`php -v`)
* Operating System
* Installation type: Compiling from source || installing via package manager
* Zephir version (if any)
* Server: Nginx | Apache | Other
* Other related info (session adapter, adapter configuarations, etc)

**Comment by Jurigag** [comment] 2018-12-20 15:53
Are you sure you started session before putting anything to it?

**Comment by sergeyklay** [comment] 2019-02-21 09:04
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Closed by sergeyklay** 2019-02-21 09:04 UTC
Labels: Need information, Need script to reproduce
