### ISSUE TITLE
[BUG]: PHP 7.3.5 and 7.4.1 windows folder name ending with period not working

### ISSUE THREAD

**Issue by naumanjkhan** [phalcon/cphalcon#14858] opened 2020-02-18 11:53 UTC
Warning: mkdir(): Permission denied

https://github.com/phalcon/cphalcon/blob/4.0.x/phalcon/Helper/Str.zep#L210

cache file name has dots in it, e.g; `index.12321321.cache.html`

```php
$dir = 'index.12321321.cache.html';
$cache = new Phalcon\Cache($adapter);
$cache->set($dir, 'hello world', 30);
// phalcon/Helper/Str::dirFromFile(string! file)
// mkdir(directory, 0777, true);
```

**Details**
 - Phalcon version: 4.0.3 & 4.0.4
 - PHP Version: 7.4.1
 - Operating System: Windows 10

**Comment by Jeckerson** [comment] 2020-02-19 15:03
Can you try with `$recursive = true` ?

mkdir($dir, null, true);

**Comment by naumanjkhan** [comment] 2020-02-20 04:17
@Jeckerson https://github.com/phalcon/cphalcon/blob/4.0.x/phalcon/Storage/Adapter/Stream.zep#L277
```php
if !is_dir(directory) {
  mkdir(directory, 0777, true);
}
```

**Comment by ruudboon** [comment] 2020-02-20 05:24
Are you on Phalcon 4.0.4?

**Comment by naumanjkhan** [comment] 2020-02-20 05:30
@ruudboon 4.0.3

**Comment by naumanjkhan** [comment] 2020-02-20 05:38
Updated to 4.0.4 and problem persists

**Comment by ruudboon** [comment] 2020-02-20 05:59
Thnx for testing on the upgrade.  I did some fixes in 4.0.1 related in this area so wanted to be sure you’re not on 4.0.0.
I think @Jeckerson is on it.

**Comment by Jeckerson** [comment] 2020-02-25 14:36
After tests in all 3 envs (Linux and Mac) via integration tests. Meanwhile Windows tests I did manually.
So the problem is in Windows (partially) and in PHP mainly.

In Windows, if you try to create folder with dot at the end, it will remove and it and create without it.
![2020-02-25_14-32-07](https://user-images.githubusercontent.com/3289702/75256675-bab37980-57db-11ea-9b1d-b27db603b810.gif)

Same thing if create via cmd and `mkir` command.

Meanwhile in PHP it will output error and do not create and folder:
```
PHP Warning:  mkdir(): Permission denied
```

Probably make sense to report bug to PHP...

@naumanjkhan Any way, in your case, just replace `.` dots with `-` in filename and it will work.

/cc @phalcon/core-team Suggestions what to do from our side.

**Comment by naumanjkhan** [comment] 2020-02-26 10:07
@Jeckerson thank you for suggestion but that what I have already done, changed the file name. But I will have to remember it and will have to replace wherever I am using the filename with dots for cache.

Wouldn't it be possible if it is handled internally and developers don't have to remember about replacing dots on windows environment (an extra burden)

**Comment by niden** [comment] 2020-02-26 18:17
@Jeckerson I think the best approach on this would be to replace the `.` with `-` when we create the subfolders and handle it internally.

**Comment by niden** [comment] 2020-03-05 06:18
Resolved in https://github.com/phalcon/cphalcon/pull/14893

Thank you @naumanjkhan

**Closed by niden** 2020-03-05 06:18 UTC
Labels: 4.0.5, bug, status: low
