### ISSUE TITLE
Why don't you convert the account to the organization Phalcon?

### ISSUE THREAD

**Issue by KorsaR-ZN** [phalcon/cphalcon#10022] opened 2015-04-13 09:51 UTC
Why don't you convert the account to the organization Phalcon?
see https://help.github.com/articles/converting-a-user-into-an-organization/

**Comment by salarmehr** [comment] 2015-05-16 11:30
+1

**Comment by sergeyklay** [comment] 2015-05-17 10:08
Refs #3246

**Comment by andresgutierrez** [comment] 2015-08-04 16:50
Closed as duplicate of #3246

**Closed by andresgutierrez** 2015-08-04 16:50 UTC
