### ISSUE TITLE
After building, message should advise to restart phpx-fpm not webserver

### ISSUE THREAD

**Issue by ChangePlaces** [phalcon/cphalcon#12986] opened 2017-07-26 14:46 UTC
After building with the `./install` script, the message advises to restart the web server, whereas php should be restarted.

### Details

* Phalcon version: 3.2.1.
* PHP Version: (`php -v`) 7.0
* Operating System: ubuntu
* Installation type: Compiling from source
* Zephir version (if any):
* Server: nginx
* Other related info (Database, table schema):

**Comment by sergeyklay** [comment] 2017-07-26 17:05
It is reasonable for Nginx (PHP-FMP) only, but in case of Apache you have to restart web server. 
I want to close this issue because I don't want a bunch of these lying around an this is not a bug report (enhancement). If anyone wants to improve this, I'd love that. 

Refs: https://github.com/phalcon/cphalcon/blob/master/build/install#L146

**Closed by sergeyklay** 2017-07-26 17:05 UTC

**Comment by ChangePlaces** [comment] 2017-07-26 18:10
Could a simple change be like "Build succeeded: Please restart your webserver, or If using php-fpm restart the php-fpm service."

Also, note the "succeed" / "succeeded" typo currently in at the moment!

**Comment by sergeyklay** [comment] 2017-07-26 19:30
@ChangePlaces Could you please send a PR? Also take a look at the README.md
