### ISSUE TITLE
[2.0.8] The record doesn't have a valid data snapshot

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#11207] opened 2015-12-08 15:46 UTC
In the afterSave of the model I try to check if a value has changed using $this->hasChanged("column")
I get: The record doesn't have a valid data snapshot

In the initialize() I'm having
```
public function initialize()
    {
        $this->useDynamicUpdate(true); 
        $this->keepSnapshots(true);
    }
``` 
In the afterSave $this->di->getShared("modelsManager")->isKeepingSnapshots($this) I returning true.
In the afterSave $this->getSnapshotData() is giving back NULL

I assume this is related to #1867

**Comment by andresgutierrez** [comment] 2015-12-09 02:23
Closing as duplicate of #1867

**Closed by andresgutierrez** 2015-12-09 02:23 UTC
