### ISSUE TITLE
Fatal error: Method Phalcon\Forms\Element\Text::__toString() must not throw an exception when using "value" as field name

### ISSUE THREAD

**Issue by tokict** [phalcon/cphalcon#10907] opened 2015-09-08 09:08 UTC
I have noticed that on 2.0.7 when I try to create an form element  with name "value",  it throws a fatal error "Fatal error: Method Phalcon\Forms\Element\Text::__toString() must not throw an exception".

Note: The code was written for 1.3.0 originally and we ported it to 2.0.7.

If I name the field "val", the error goes away.
I'm guessing its a reserved word or similar. I might have missed something in the docs. Anyway, it took me some time to find the issue as no debug info was visible about the position of the error.

**Comment by andresgutierrez** [comment] 2015-09-08 13:04
Duplicate of #10874

**Closed by andresgutierrez** 2015-09-08 13:04 UTC
Labels: Need script to reproduce
