### ISSUE TITLE
[BUG]: Query Builder parsing NOT expression in column name

### ISSUE THREAD

**Issue by palcoder** [phalcon/cphalcon#16099] opened 2022-09-16 16:37 UTC
Hello,

I have an issue with Phalcon\Mvc\Model\Query\Builder  as it parsing **NOT** expression in the column name.

I got this exception:

`
Column 'es' doesn't belong to any of the selected models (1), when preparing: SELECT id, notes FROM [Leaves] ORDER BY id ASC
`

To reproduce:
You may create a table and naming any column with note or anything else starts with **not**

`
$queryBuilder = new \Phalcon\Mvc\Model\Query\Builder([
            'models' => [
                'Leaves'
            ],
            'columns' => ['id', 'notes']
        ]);
`

PHQL:
`SELECT id, notes FROM [Leaves] ORDER BY id ASC`

**Comment by niden** [comment] 2022-09-16 16:47
This has already been reported here: https://github.com/phalcon/cphalcon/issues/15741

It is pretty much the same issue. The parser cannot distinguish between the word `NOT` that is a valid SQL term and words that start with `not`. The same thing happens with a field called `notifications` for instance.

I am not sure if this will be fixed. In the meantime, you could restructure your code and enclose the field name in `[]`

```sql
SELECT id, [notes] FROM [Leaves].....
```

**Comment by niden** [comment] 2022-09-20 14:16
Duplicate of: https://github.com/phalcon/cphalcon/issues/14641

Closing this one

**Closed by niden** 2022-09-20 14:16 UTC
