### ISSUE TITLE
AssetsManager collection join() method is not working without filters

### ISSUE THREAD

**Issue by 6562680** [phalcon/cphalcon#13344] opened 2018-04-11 08:37 UTC
AssetsManager collection join() method is not working without filters. You must create dummyFilter class without action to make non-minified JS in output (for DEBUG if you will not use Gulp/Grunt/Webpack/Sourcemaps of course)

```php
$collection = $this->collection('collection')
  ->addCss('file.css')
  ->addCss('file2.css')
  ->join(true); // will not work if no filters defined before

$collection->outputCss();
```

* Phalcon version: 3.3.2
* PHP Version: 7.2 TS
* Operating System: Win10
* Installation type: DLL
* Server: Nginx/Apache

**Comment by niden** [comment] 2019-02-14 00:28
This actually is not a bug. This is how the component was designed - you need a filter when you are to join assets (as well as a target location).

To get just the contents joined (no minification) all you need is to add the `None` filter

```php
use Phalcon\Assets\Manager;
use Phalcon\Assets\Filters\None;

$manager = new Manager()
$manager
    ->collection('collection')
    ->addFilter(new None())
    ->addCss('file.css')
    ->addCss('file2.css')
    ->join(true);

echo $manager->outputCss();
```

**Comment by niden** [comment] 2019-02-14 00:30
Closing - if there is a need for the functionality above i.e. to not have to use the filter when you want to "join" stuff we can discuss that as a NFR at a later stage

**Closed by niden** 2019-02-14 00:30 UTC
Labels: Not a bug
