### ISSUE TITLE
DI router

### ISSUE THREAD

**Issue by tidytrax** [phalcon/cphalcon#10740] opened 2015-07-30 01:08 UTC
The problem 
https://forum.phalconphp.com/discussion/7849/router-mount#C21343

di->set('router') has not autoloader class 

https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/application.zep

Linha 210
let router = <RouterInterface> dependencyInjector->getShared("router");

Linha 280
moduleObject->registerAutoloaders(dependencyInjector);

**Comment by andresgutierrez** [comment] 2015-07-30 01:16
To submit a bug you need to provide a single PHP with all the necessary code to reproduce the issue.

**Comment by tidytrax** [comment] 2015-07-31 11:48
/configs/services.php

$di->set('router', function () {

    $router = new Router();

    include __DIR__.'/../library/System/Routes/Loja.php';
    include __DIR__.'/../library/System/Routes/Admin.php';
    include __DIR__.'/../library/System/Routes/Frontend.php';
    $router->mount(new \System\Routes\Frontend);
    $router->mount(new \System\Routes\Loja);
    $router->mount(new \System\Routes\Admin);
    
    $router->notFound(array(
        "controller" => "index",
        "action" => "notfound"
    ));
    
    return $router;
});
$di->set('router', function () {

    $router = new Router();

    include __DIR__.'/../library/System/Routes/Loja.php';
    include __DIR__.'/../library/System/Routes/Admin.php';
    include __DIR__.'/../library/System/Routes/Frontend.php';
    $router->mount(new \System\Routes\Frontend);
    $router->mount(new \System\Routes\Loja);
    $router->mount(new \System\Routes\Admin);
    
    $router->notFound(array(
        "controller" => "index",
        "action" => "notfound"
    ));
    
    return $router;
});

**Comment by andresgutierrez** [comment] 2015-07-31 15:05
After running your test:

```php
Notice: Undefined variable: di in /Users/phalcon/cphalcon/a.php on line 3
PHP Fatal error:  Call to a member function set() on null in /Users/phalcon/cphalcon/a.php on line 3
```

**Comment by tidytrax** [comment] 2015-08-01 07:56
This is a shortcode, and all another works here the full code
All other di-set in the same file works
problem is only in router.

http://pastebin.com/QRq6A5FZ

**Comment by tidytrax** [comment] 2015-08-01 08:28
Looks to me that router are not able to call class, can you make a test in your router
calling any class from library!

**Comment by goqihoo** [comment] 2015-08-01 08:47
services.php line 3
Phalcon\DI\FactoryDefault

should modified to Phalcon\DI\FactoryDefault as FactoryDefault

becase you create an instance by FactoryDefault, not Phalcon\DI\FactoryDefault in line 22

**Comment by tidytrax** [comment] 2015-08-01 08:59
Is the same, because as is just to set an alias.
and in others di->set all works fine,

**Comment by tidytrax** [comment] 2015-08-01 09:00
$di->set dispatcher if you look i use 3 \System\ Class

**Comment by sergeyklay** [comment] 2016-09-30 10:12
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises and providing a minimal script to reproduce.

**Closed by sergeyklay** 2016-09-30 10:12 UTC
Labels: Need script to reproduce
