### ISSUE TITLE
[NFR] Microsoft SQL Server Support

### ISSUE THREAD

**Issue by chesney** [phalcon/cphalcon#2137] opened 2014-03-07 11:18 UTC
It would be great to have MSSQL Server support.

eg.

'database' => array(
        'adapter'     => 'sqlsrv',
        ....

**Comment by chesney** [comment] 2015-04-15 13:30
I hope this will still be considered.

**Comment by Green-Cat** [comment] 2015-05-25 23:07
@andresgutierrez duplicate of #1184

**Comment by ruudboon** [comment] 2015-10-24 07:43
+1

**Comment by Green-Cat** [comment] 2016-04-02 21:20
@sergeyklay duplicate of #1184

**Closed** 2016-04-02 21:34 UTC
Labels: New Feature Request

**Comment by brunomdev** [comment] 2016-08-01 12:47
+1
