### ISSUE TITLE
win10 php7.1 Unable to load dynamic library php_phalcon.dll 

### ISSUE THREAD

**Issue by wolinyy** [phalcon/cphalcon#14266] opened 2019-07-29 08:09 UTC
I tried multiple versions of the dll file and found that the latest available version is 3.3.2. 

3.4.x cannot be used. 

The number of files in the 3.3.2 and 3.4.x zip package is different. 
Has the compiled environment changed?

![image](https://user-images.githubusercontent.com/10389509/62032021-3d129580-b21b-11e9-933a-09a4f56d8d86.png)

**Comment by ruudboon** [comment] 2019-07-29 08:50
@wolinyy Can you tell me the exact version you took? I only see zip files with a php_phalcon.dll and a LICENSE.txt
I assume you need Phalcon for PHP 7.1 & NTS. Do you need x86 or x64?

**Comment by wolinyy** [comment] 2019-07-29 09:09
> @wolinyy Can you tell me the exact version you took? I only see zip files with a php_phalcon.dll and a LICENSE.txt
> I assume you need Phalcon for PHP 7.1 & NTS. Do you need x86 or x64?

Yes I need PHP 7.1 & NTS & x86 for win10

phalcon_x86_vc14_php7.1.0_3.3.2_nts.zip has 2 files
phalcon_x86_vc14_php7.0_3.4.0-1656_nts.zip has 16 files

I test 3.3.2 and 3.2.0, is OK。
but 3.4.0， 3.4.1，3.4.2,3.4.4，can not work：php -m Unable to load dynamic library ，but phpinfo can find phalcon module。

I guess the php_phalcon.dll build environment has changed since 3.4.0.

![image](https://user-images.githubusercontent.com/10389509/62035702-f163ea00-b222-11e9-83c0-97048a098a60.png)

**Comment by ruudboon** [comment] 2019-07-29 09:22
Looks like you took the wrong php version. You downloaded 7.0 instead of 7.1.
Can you try https://github.com/phalcon/cphalcon/releases/download/v3.4.4/phalcon_x86_vc14_php7.1_3.4.4_nts.zip

**Comment by wolinyy** [comment] 2019-07-30 02:31
> Looks like you took the wrong php version. You downloaded 7.0 instead of 7.1.
> Can you try https://github.com/phalcon/cphalcon/releases/download/v3.4.4/phalcon_x86_vc14_php7.1_3.4.4_nts.zip

Sorry, I have cut the wrong picture. 
In fact, I can switch the version of php locally,
I tried both 7.1 and 7.0, 3.4.x will not work, 
and later I tried php7.1 3.2.0 and 3.3.2.
There is no problem with the version of php

![image](https://user-images.githubusercontent.com/10389509/62096071-025d3b80-b2b5-11e9-9216-7114625e8bdf.png)

**Comment by wolinyy** [comment] 2019-07-30 02:43
![image](https://user-images.githubusercontent.com/10389509/62096193-6849c300-b2b5-11e9-9ba4-3c59b258ca4d.png)

![image](https://user-images.githubusercontent.com/10389509/62096638-e490d600-b2b6-11e9-9e42-55f0066486e9.png)

**Comment by wolinyy** [comment] 2019-07-30 02:47
![image](https://user-images.githubusercontent.com/10389509/62096763-5cf79700-b2b7-11e9-9245-db4f3bb5856f.png)

When reporting an error, the version of php_phalcon.dll is 3.4.2.

**Comment by CameronHall** [comment] 2019-07-30 05:28
Can you delete the zip files you've already downloaded and any of the extracted contents. Then remove any existing php_phalcon.dll (except your backup of 3.3.2) from the `ext` directory and reinstall using ones of the links below?

- PHP 7.1 x86 NTS [use this version](https://github.com/phalcon/cphalcon/releases/download/v3.4.4/phalcon_x86_vc14_php7.1_3.4.4_nts.zip)
- PHP 7.0 x86 NTS [use this version](https://github.com/phalcon/cphalcon/releases/download/v3.4.4/phalcon_x86_vc14_php7.0_3.4.4_nts.zip)

What does the entry in your `php.ini` look like?

If you're still having trouble, we'll need to confirm the windows installs ourselves.

**Comment by wolinyy** [comment] 2019-07-30 11:13
> Can you delete the zip files you've already downloaded and any of the extracted contents. Then remove any existing php_phalcon.dll (except your backup of 3.3.2) from the `ext` directory and reinstall using ones of the links below?
> 
> * PHP 7.1 x86 NTS [use this version](https://github.com/phalcon/cphalcon/releases/download/v3.4.4/phalcon_x86_vc14_php7.1_3.4.4_nts.zip)
> * PHP 7.0 x86 NTS [use this version](https://github.com/phalcon/cphalcon/releases/download/v3.4.4/phalcon_x86_vc14_php7.0_3.4.4_nts.zip)
> 
> What does the entry in your `php.ini` look like?
> 
> If you're still having trouble, we'll need to confirm the windows installs ourselves.

![image](https://user-images.githubusercontent.com/10389509/62124470-e7161e80-b2fc-11e9-8b24-0ec4a9c7ab62.png)

My configuration is definitely no problem.
As shown, the cli mode php_phalcon can't be found, but nginx+php prints phpinfo() but can see it.

I was using the win10 system for the first time. This system is installed on a remote virtual system. I suspect there are certain reasons for this.

3.3.2 Can be used ok, my home win7 can use 3.4.x series

**Comment by CameronHall** [comment] 2019-07-30 22:49
> but nginx+php prints phpinfo() but can see it.
> my home win7 can use 3.4.x series
Sounds like it's working on Windows

> My configuration is definitely no problem.
Help us, help you. Do what I've asked, then report back.

Thanks :)

**Comment by wolinyy** [comment] 2019-07-31 00:39
> Help us, help you. Do what I've asked, then report back.

win10 PHP 7.1.13 (cli) (built: Jan  3 2018 20:14:59) ( NTS MSVC14 (Visual C++ 2015) x86 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

PHP 7.0 x86 NTS not work.
PHP 7.1 x86 NTS php cli not work，nginx+php work Ok. Just like the screenshot above.

Win10 is my working environment, The screenshots above are all in win10.

![image](https://user-images.githubusercontent.com/10389509/62175051-c5557f80-b36e-11e9-8114-0df2f1293529.png)

**Comment by CameronHall** [comment] 2019-07-31 13:54
I've just tested this on my own Windows PC. I can't reproduce the issue, I downloaded a fresh copy of PHP 7.1.31 (x86) NTS and installed the extension. 

I did have an issue where PHP was trying to read the extensions from another directory which can be seen in my console output below. This was remedied by updating the `php.ini` entry to;

```
extension=C:\Users\Cam\Documents\php\7.1.31\ext\php_phalcon.dll
```

```
Cam@CAMPC C:\Users\Cam\Documents\php\7.1.31
$ php --ri phalcon
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\php\ext\php_phalcon.dll' - The specified module could not be found.
 in Unknown on line 0
Extension 'phalcon' not present.

Cam@CAMPC C:\Users\Cam\Documents\php\7.1.31
$ php --ri phalcon

phalcon


Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.4.4
Build Date => Jun 30 2019 15:42:44
Powered by Zephir => Version 0.10.15

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.disable_assign_setters => Off => Off
```

I'm very confident this is a configuration issue. I hope you manage to work it out, but I don't think there is anything further we can do for you here.

**Comment by diplopito** [comment] 2019-08-02 06:40
I use Xampp and I always install the thread safe version. Running 3.4.4 without any issues. Have you given it a try?

**Comment by diplopito** [comment] 2019-08-02 11:14
Just tested PHP 7.3 nts x64 with Phalcon 3.4.4:

```

D:\php73>php --ri phalcon

phalcon


Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.4.4
Build Date => Jun 30 2019 16:17:31
Powered by Zephir => Version 0.10.15

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.disable_assign_setters => Off => Off

D:\php73>php -v
PHP 7.3.8 (cli) (built: Jul 30 2019 12:44:08) ( NTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.8, Copyright (c) 1998-2018 Zend Technologies

D:\php73>
```

Please check your `extension_dir` in php.ini and see that it is properly configured with the ext path where you installed Phalcon.

**Comment by diplopito** [comment] 2019-08-02 11:22
And with 7.1 x64 NTS:

```
Microsoft Windows [Version 10.0.17134.829]
(c) 2018 Microsoft Corporation. All rights reserved.

D:\>cd php71

D:\php71>php -v
PHP 7.1.31 (cli) (built: Jul 31 2019 08:43:22) ( NTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies

D:\php71>php --ri phalcon

phalcon


Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.4.4
Build Date => Jun 30 2019 15:48:39
Powered by Zephir => Version 0.10.15

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.disable_assign_setters => Off => Off

D:\php71>
```

With `extension_dir = "d:\php71\ext"` and `extension=php_phalcon` in `php.ini`

**Comment by ruudboon** [comment] 2019-08-03 06:32
@wolinyy Did you make any progress with the examples above? If this is solved please close the issue.

**Closed** 2019-08-19 10:17 UTC
Labels: Not a bug
