### ISSUE TITLE
[BUG]: Attribute 'checked' in Check element

### ISSUE THREAD

**Issue by bakos** [phalcon/cphalcon#15959] opened 2022-05-13 07:34 UTC
**Describe the bug**

In Phalcon 5.0.x Check field clears 'checked' attribute on render.

**To Reproduce**

```php
$checkField = new \Phalcon\Forms\Element\Check('checkField');
$checkField->setAttribute('checked', 'checked');
var_dump($checkField->getAttributes());
echo $checkField;
```

**Expected behavior**

It should render html with attribute 'checked'. It works in phalcon 4.x, 3.x

**Screenshots**

Phalcon 4

![image](https://user-images.githubusercontent.com/3259232/168233572-2d2eccb6-0c06-4fa5-95bb-d7b370e8e337.png)

Phalcon 5

![image](https://user-images.githubusercontent.com/3259232/168233634-30a8f18c-d680-454c-9f99-00017aa6929c.png)

**Details**
 - Phalcon version: 5.0.0beta3
 - PHP Version: 7.4.28
 - Operating System: Debian
 - Installation type: pecl
 - Server: Apache 
 
**Additional context**

I tried this on attribute 'disabled' and it was working, so the bug is not about setting any attribute

**Comment by niden** [comment] 2022-05-23 16:47
Can you try setting the `checked` with the same value as `value`?

```
$checkField = new \Phalcon\Forms\Element\Check('checkField');
$checkField
    ->setAttribute('value', 'one-two-three')
    ->setAttribute('checked', 'one-two-three')
;

echo $checkField;
```

**Comment by bakos** [comment] 2022-05-24 05:09
It works in that configuration

**Comment by niden** [comment] 2022-05-24 13:31
I am closing this but will tag it as documentation so as to update the documents accordingly

**Comment by bakos** [comment] 2022-07-21 08:35
@niden this solution seems to be workaround and not real solution. There can be checkboxes without value created just to represent actual state.

**Comment by niden** [comment] 2022-07-21 18:02
> @niden this solution seems to be workaround and not real solution. There can be checkboxes without value created just to represent actual state.

Can you give me an example please?

**Comment by bakos** [comment] 2022-07-22 06:30
@niden I have a big project with many forms where i have checkboxes. Now in every checkbox that is only used for preview and that worked on v2, v3 and v4 (yes its old project mvp was building on v1) i have to modify code like this:

```
$checkField = new \Phalcon\Forms\Element\Check('checkField');
$checkField->setAttribute('checked', 'checked');

```
into this:

```
$checkField->setAttribute('value', 'workaround');
$checkField->setAttribute('checked', 'workaround');
```

because this value has no other meaning than to make "checked" worked. I thought maybe this could work:

```
$checkField->setAttribute('checked',$checkField->getAttribute('value'));
```

but it is not. I have to add value to checkboxes just to make it work. I can and probably do that but it`s workaround not a solution and potencialy a source of problems couse its easy to forget that $checkField->setAttribute('xyz', 'xyz'); will work and set attribute on field, but $checkField->setAttribute('checked', 'checked') will not work and will not set attribute on the field becouse in 'checked' you have to add value before and set this value to checked. Sounds like a bug.
.

**Comment by punneke** [comment] 2022-08-19 10:01
Yes, setAttribute() is definately not the solution. In Phalcon 3/4 the checked attribute was true of false when the Entities property value was the same as the default value attribute.

For example:

```php
        $status = new Check('status ', [
            'value' => '1',
        ]);
        $status ->setLabel('Status');
        $this->add($status );
```

Worked out of the box when `$entity->status = '1'`

```php
$form->render('status');
```

```html
<input type="checkbox" id="status" name="status" value="1" checked="checked">
```

In Phalcon 5 the checked attribute is not automatically set anymore.

```html
<input type="checkbox" id="status" name="status" value="1">
```

This is my current workaround:
```php
        $status = new Check('status ', [
            'value' => '1',
        ]);
        if (!is_null($entity) && $entity->active == '1') {
            $active->setAttribute('checked', '1');
        }
        $status ->setLabel('Status');
        $this->add($status );
```

**Comment by punneke** [comment] 2022-08-19 12:22
@niden I was looking further into the issue. 

I think the issue lies in the fact that the value in $entity->active is 1 as an integer and not '1' a string.
This probably changed in Phalcon 5 because all database integers used to be returned as a string and now they are integers.

So the check on line 127 in https://github.com/phalcon/cphalcon/blob/master/phalcon/Html/Helper/Input/Checkbox.zep#L127 fails because is strict with ===.

**Comment by mikx33** [comment] 2022-10-25 06:53
I also have a similar problem, because of which I can not upgrade to version 5

**Comment by sitchi** [comment] 2022-11-14 09:49
Temporary solution https://github.com/sitchi/cphalcon/commit/00e0015322e746166a5f76e2886af40849d55476#diff-e2fe7a00cec84d040337697de69c6a33b8849bdd44b9155e9c015554f5ff2233

**Comment by amujib** [comment] 2022-11-17 10:29
I found another bug related to checkbox when using '0' as unchecked value.
**To Reproduce**
```
$checkField = new \Phalcon\Forms\Element\Check('checkField');
$checkField
    ->setAttribute('value', '1')
    ->setAttribute('unchecked', '0')
;

echo $checkField;
```

**Expected Result**
`<hidden name="checkField" value="0"><input type="checkbox" id="checkField" name="checkField" value="1" />`

**Actual Result**
`0<input type="checkbox" id="checkField" name="checkField" value="1" />`

**Comment by SliceOfLife** [comment] 2023-01-31 07:12
I got another vector for this issue.
The "checked" attribute is gone after the form validation fails when we re-render Form with _POST values.
This behavour works with the legacy Tag renderer, but might be relevant for the new TagFactory.

For now I use this temporary fix:
```php
$this->tag->set('inputCheckbox', CheckboxRendererFix::class);
```

```php
class CheckboxRendererFix extends \Phalcon\Html\Helper\Input\Checkbox
{
	private function processChecked(): void
	{
		$attributes = $this->attributes;

		if (empty($attributes['checked'])) {
			if (!empty($attributes['value'])) {
				$attributes['checked'] = 'checked';
			}
		}

		$this->attributes = $attributes;
	}
}
```

**Comment by dugwood** [comment] 2023-06-15 14:38
The main issue here is the test of `checked` value. It should use `empty()` for the test:
https://github.com/phalcon/cphalcon/blob/bf4e73cb50caa420ab0c38800e3a275fbc7b45c5/phalcon/Html/Helper/Input/Checkbox.zep#L123

As @amujib stated, testing `0` or `(empty string)` should be a valid option. It was working with Phalcon 4.

Can you fix this? Or should I open another bug report @niden?

**Comment by dugwood** [comment] 2023-06-15 14:41
@niden something like:

```
    /**
     * Processes the checked value
     */
    private function processChecked() -> void
    {
        var checked, value;
        array attributes;

        let attributes = this->attributes;
        if !fetch checked, attributes["checked"] {
            let checked = null;
        }

        unset attributes["checked"];

        if checked !== null {
            if !fetch value, attributes["value"] {
                let value = null;
            }
            if checked === value {
                let attributes["checked"] = "checked";
            }
        }

        let this->attributes = attributes;
    }

```

**Comment by niden** [comment] 2023-06-15 15:18
> The main issue here is the test of `checked` value. It should use `empty()` for the test:
> 
> https://github.com/phalcon/cphalcon/blob/bf4e73cb50caa420ab0c38800e3a275fbc7b45c5/phalcon/Html/Helper/Input/Checkbox.zep#L123
> 
> As @amujib stated, testing `0` or `(empty string)` should be a valid option. It was working with Phalcon 4.
> 
> So instead of `empty()` there should only be a `isset()`. And we can assume that `null` is not a valid value.
> 
> Can you fix this? Or should I open another bug report @niden?

If you don't mind please add an issue and reference this discussion/tag me.

Sorry guys, too busy at work to remember all these discussions :/

**Comment by niden** [comment] 2023-06-15 21:58
Resolved in https://github.com/phalcon/cphalcon/pull/16358

Thank you again @dugwood

**Closed by niden** 2023-06-15 21:58 UTC
Labels: documentation, bug, status: low, 5.0

**Comment by dugwood** [comment] 2023-06-16 06:27
@bakos regarding your initial report: checkboxes always have a value. If you POST a checkbox, you'll see that PHP considers its value to be `on` when checked. So it has a default value of `on`.

Radio fields are different as it should be considered as a `<select>` (I mean you have to choose one value among all the values). So there must be a `value` too. If empty, it should be set as empty with `value=""`.

@niden there's another issue with this, as `radio_field()` in Volt doesn't work like this at all. I've kept my old Phalcon v4 code (with `set_default()`) and it works, but setting `checked` doesn't work as expected, it checks every radio field. I think it would be good to fix it one day, but that's a lot of changes for Phalcon users.

**Comment by HalitYesil** [comment] 2024-01-20 11:18
What!

Is selected if the value property value and the checked property value are the same. 

` 
/**
     * Processes the checked value
     */
    private function processChecked() -> void
    {
        var checked, value;
        array attributes;

        let attributes = this->attributes;
        if !fetch checked, attributes["checked"] {
            let checked = null;
        }

        unset attributes["checked"];

        if checked !== null {
            if !fetch value, attributes["value"] {
                let value = null;
            }
            if checked === value { // Is selected if the value property value and the checked property value are the same. . <<<<======
                let attributes["checked"] = "checked"; 
            }
        }

        let this->attributes = attributes;
    }
`


I did it as follows and it worked.

`
$input = new \Phalcon\Forms\Element\Radio('radio1', [
   'name'  => 'radiogroup',
   'value'  => 'one-two-three'
]);
$input->setDefault('one-two-three');
$input->setAttribute('checked',  $input->getValue()); // <<<< Set the input value property value for the checked property.
`


I think the team was a little confused while writing
