### ISSUE TITLE
Fatal error: Uncaught SoapFault exception: [VersionMismatch] Wrong Version

### ISSUE THREAD

**Issue by ArekSBC** [phalcon/cphalcon#12149] opened 2016-08-17 04:55 UTC
After upgrade Phalcon from 2.0.10 to 3.0.0 SoapClient stop working.

```php
Fatal error: Uncaught SoapFault exception: [VersionMismatch] Wrong Version in ....Service.php:267 Stack trace: 
#0 .....Service.php(267): SoapClient->__soapCall('.....', Array) 
```
> Provide minimal script to reproduce the issue

```php
  /**
     * @param $method
     * @param $params
     * @return mixed
     */
    protected function executeCall($method, $params)
    {
        $client = new \SoapClient(
            __DIR__ . "/" . $this->wsdlDir . "/" . $method . ".wsdl",
            $this->options
        );

       $response = $client->__soapCall($method, $params);

        return $response;
    }
```
### Details

* Phalcon version: (
```
phalcon
Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.0.0
Build Date => Aug 14 2016 19:16:28
Powered by Zephir => Version 0.9.3a-dev-e716dbe641

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
```
)
* PHP Version: (
```
PHP 5.6.24-0+deb8u1 (cli) (built: Jul 26 2016 08:17:07)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```
)
* Operating System: Debian 8 (Jessie) AMD64
* Installation type: Compiling from source
* Zephir version (if any):
* Server: Nginx 1.11.3
* Other related info (Database, table schema): MySQL

**Comment by sergeyklay** [comment] 2016-08-17 05:14
@ArekSBC Could you please provide a bit more script to reproduce and full backtrace?

**Comment by sergeyklay** [comment] 2016-10-16 15:57
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Closed** 2016-10-16 15:56 UTC
Labels: Need information, Need script to reproduce
