### ISSUE TITLE
ERROR FOR UPDATE

### ISSUE THREAD

**Issue by nekulin** [phalcon/cphalcon#3292] opened 2015-01-28 07:21 UTC
Syntax error, unexpected token IDENTIFIER(FOR), near to ' UPDATE', when parsing: SELECT [App\Models\Users].* FROM [App\Models\Users] WHERE id=?0 LIMIT 1 FOR UPDATE

        $criteria = new Criteria();
        $criteria->andWhere('id=?0', [$this->id]);
        $criteria->limit(1);
        $criteria->forUpdate(true);
        return self::findFirst($criteria->getParams());

**Comment by nekulin** [comment] 2015-01-28 07:27
It is necessary to solve the problem so

    /**
     * @return \Phalcon\Mvc\Model
     */
    public function getForUpdate()
    {
        $strClass = get_called_class();
        /** @var \Phalcon\Mvc\Model $strClass */
        $strClass = new $strClass();
        $sql = "SELECT * FROM ".$strClass->getSource()." WHERE id=:id LIMIT 1 FOR UPDATE";
        $result = $strClass->getReadConnection()
            ->query($sql, ['id'=>$this->id])
            ->fetch();
        foreach ($result as $strKey=>$strVal) {
            $strClass->$strKey = $strVal;
        }
        return $strClass;
    }

**Comment by olivier-monaco** [comment] 2015-01-28 11:37
Which version of phalcon?

**Comment by olivier-monaco** [comment] 2015-01-28 11:41
I think for update is not supported.

**Comment by DestinyMKas** [comment] 2015-02-06 08:52
shared lock don't works too on 1.3.4 version

**Comment by andresgutierrez** [comment] 2015-06-16 21:02
Duplicate of #2811

**Closed by andresgutierrez** 2015-06-16 21:02 UTC
