### ISSUE TITLE
Consider purging ancient ext/ directory data

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#13727] opened 2019-01-03 14:03 UTC
@niden @sergeyklay 

Cloning the repo downloads quite a lot of ancient ext data.  I'm seeing it as 216M on my file system for the 4.0.x branch.  I propose having the ext directory history purged for anything pre-3.0 to make this easier to work with.

Does anyone else think that 216M of data is crazy?  If not then please write your crazy line in the sand number down so we'll know when we get there.

**Comment by jturbide** [comment] 2019-01-05 02:18
If I understand your issue, this is a job for GIT. I've had to work with way heavier projects in the past, simply use the `--depth` or `--single-branch` option parameter to avoid cloning the entire repository.

```
#git clone --depth 1 https://github.com/phalcon/cphalcon.git
remote: Enumerating objects: 6203, done.
remote: Counting objects: 100% (6203/6203), done.
remote: Compressing objects: 100% (2588/2588), done.
remote: Total 6203 (delta 4469), reused 4347 (delta 3507), pack-reused 0
Receiving objects: 100% (6203/6203), 3.88 MiB | 0 bytes/s, done.
Resolving deltas: 100% (4469/4469), done.
Checking out files: 100% (5662/5662), done.

# du -hs cphalcon/
60M     total
```

> --depth <depth>
>            Create a shallow clone with a history truncated to the specified number of revisions. A shallow repository has a number of limitations (you cannot clone or fetch from it, nor push from nor into it), but is adequate if you are only interested in the recent history of a large project with a long history, and would want to send in fixes as patches.

> --[no-]single-branch
>            Clone only the history leading to the tip of a single branch, either specified by the --branch option or the primary branch remote’s HEAD points at. When creating a shallow clone with the --depth option, this is the default, unless --no-single-branch is given to fetch the histories near the tips of all branches. Further fetches into the resulting repository will only update the remote-tracking branch for the branch this option was used for the initial cloning. If the HEAD at the remote did not point at any branch when --single-branch clone was made, no remote-tracking branch is created.

**Comment by dschissler** [comment] 2019-01-05 04:47
So the project will just continue to grow its repo in multiples so that a cute little 49M becomes 300M, then 400M.  Is half a gig too much for a vanilla clone?  That is why I'm asking for the batshit insane number limit so that we know when we'll get there.  Can you stake your reputation on a hard number?  I'll do it it, what the hell.  200M is too much for a 50M project and with no reprieve in sight.

As someone who has put enormous amounts of time into educating people about Phalcon and for basically zero pay I have to say that I'm resentful of the constant "just do this" approach of this project.  For a long time now.  IMO there is about 10x too much geek smart guy stuff in Phalcon.  So if you are just getting into programming and are a badass in other areas of life so want to use the best tech then you also suddenly have to learn all kinds of other arcane related knowledge before you can be effective.  Its utter crap.  Its too many google searches, too many forum posts.

**Comment by niden** [comment] 2019-01-05 16:41
@dschissler This has already been discussed because it is a PITA for us to maintain also i.e. someone makes the wrong commit and the `ext/` is unusable and cannot build the extension.

The issue is that there is C code in the `ext` folder that is required to build the extension. For now we have to leave it as is. The plan however is to create another folder (say `external`) and put all the "external" C code (i.e. not generated by Zephir) so that we can pretty much ignore the ext folder and have it only as a compilation source. At that time we can remove it from git and shrink the repo.

Loads of work to do :)

**Comment by dschissler** [comment] 2019-01-05 22:02
I'm referring to deleting the history of that directory past a certain point.  I think that you can just delete much of it while still keeping the same approach as now.

**Comment by dschissler** [comment] 2019-01-06 06:18
@niden Take a look at some of the possible ways to clean out the history of a directory: https://stackoverflow.com/questions/10067848/remove-folder-and-its-contents-from-git-githubs-history

**Comment by dschissler** [comment] 2019-02-17 01:00
@niden @sergeyklay I'm currently in a piece of shit black ghetto in Cali, Colombia and its taking me forever to download the `cphalcon` repository even with depth 1.  I get that you guys are living the life on your gigabit fiber in McMansions and Oligarch palaces but some of us are out in the world in real conditions of the downtrodden.  True story, years ago I couldn't even git clone phalcon from behind the Chinese firewall with a VPN because it kept breaking the download.  So I just said outright "FUCK IT I'll download the Phalcon repo in a month when I have solid access".  That is the real world cost for having a huge bloated repo.

To the point now I'm working on Phalcon issues now and the longer that it takes me to download that shit `build` directory from my crap connection each time is less time for productivity.  It would be just amazing if the Phalcon repo didn't have to carry that shit around at all.  `build/` is like 20M and tests are blowing up to something like 26M.  Then the `ext` is like 12MB and I think some of it is necessary for special C stuff and others is just compiled crap that IMO shouldn't be there.

To me this repo feels like playing a networked game and its obvious that the nerds never stepped outside of their redundant fiber LAN because it keeps crashing non-stop.  Get the size of this repo under control so that you can recruit some African boy genius working off of a One Laptop Per Child type of shit.  Get in touch with the real world!  This is some serious bourgeois shit.

**Comment by niden** [comment] 2019-02-23 23:15
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.

**Closed by niden** 2019-02-23 23:15 UTC
