### ISSUE TITLE
SIGILL on Phalcon 3.4.0 and PHP 7.2

### ISSUE THREAD

**Issue by erickskrauch** [phalcon/cphalcon#13454] opened 2018-07-27 20:31 UTC
Hi there.

Recently I moved project building from production server to the CI to use full power of Docker Images and *CI things*. The problem is built images from the CI server not working on the production server. I've found issue https://github.com/phalcon/cphalcon/issues/1385. It's tells, that the problem can be in CPU architecture. And it really looks like the truth. Just compare it:

<details><summary>Production /proc/cpuinfo</summary><p>

```bash
# cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 95
model name	: Intel(R) Atom(TM) CPU C3955 @ 2.10GHz
stepping	: 1
microcode	: 0x1
cpu MHz		: 2100.000
cache size	: 4096 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl eagerfpu pni pclmulqdq vmx ssse3 cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave rdrand hypervisor lahf_lm 3dnowprefetch ibrs ibpb kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust smep erms mpx rdseed smap clflushopt xsaveopt xsavec xgetbv1 arat
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 4200.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:
```
</p></details>

<details><summary>CI server /proc/cpuinfo</summary><p>

```bash
# cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model name	: Intel(R) Xeon(R) CPU E3-1246 v3 @ 3.50GHz
stepping	: 3
microcode	: 0x22
cpu MHz		: 3791.595
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts
bugs		:
bogomips	: 7000.15
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
```
</p></details>

Dockerfile used to build:

```dockerfile
FROM php:7.2.8-fpm-alpine3.7

ENV PHALCON_VERSION=3.4.0
ENV COMPOSER_ALLOW_SUPERUSER 1

# bash needed to support wait-for-it script
RUN apk add --update --no-cache \
    git \
    bash \
    openssh \
    dcron \
    # zip extension
    zlib-dev \
    # intl extension
    icu-dev \
    libintl \
    # gd extension
    freetype-dev \
    libjpeg-turbo-dev \
    libpng-dev \
 && docker-php-ext-configure gd \
    --with-freetype-dir=/usr/include/ \
    --with-jpeg-dir=/usr/include/ \
 && docker-php-ext-install -j$(nproc) gd zip pdo_mysql intl pcntl bcmath sockets opcache \
 && apk add --no-cache --virtual ".phpize-deps" $PHPIZE_DEPS \
 # Phalcon compilation
 && curl -sSL "https://codeload.github.com/phalcon/cphalcon/tar.gz/v${PHALCON_VERSION}" | tar -xz \
 && cd cphalcon-${PHALCON_VERSION}/build \
 && ./install \
 && cp ../tests/_ci/phalcon.ini ${PHP_INI_DIR}/conf.d/ \
 && cd ../../ \
 && rm -r cphalcon-${PHALCON_VERSION} \
 # End Phalcon compilation
 && yes | pecl install mongodb \
 && docker-php-ext-enable mongodb \
 && yes | pecl install xdebug-2.6.0 \
 && apk del ".phpize-deps" \
 && rm -rf /usr/share/man \
 && rm -rf /tmp/* \
 && mkdir /etc/cron.d

# other instructions ...
```

strace:

```                                                                                                                                      
fcntl(3, F_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=1, l_len=1}) = 0
brk(0x5562602c4000)                     = 0x5562602c4000
access("/var/www/html/app/config/constants-local.php", F_OK) = -1 ENOENT (No such file or directory)
access("/var/www/html/common/config/config-prod.php", F_OK) = 0
access("/var/www/html/common/config/config-local.php", F_OK) = -1 ENOENT (No such file or directory)
access("/var/www/html/common/config/../../app/config/config.php", F_OK) = 0
access("/var/www/html/common/config/../../app/config/config-prod.php", F_OK) = -1 ENOENT (No such file or directory)
access("/var/www/html/common/config/../../app/config/config-local.php", F_OK) = -1 ENOENT (No such file or directory)
lstat("/var/www/html/app", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/var/www/html/app", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/var/www/html/vendor/yiisoft/extensions.php", {st_mode=S_IFREG|0644, st_size=2918, ...}) = 0
socket(PF_INET6, SOCK_DGRAM, IPPROTO_IP) = 6
close(6)                                = 0
open("/etc/hosts", O_RDONLY|O_CLOEXEC)  = 6
fcntl(6, F_SETFD, FD_CLOEXEC)           = 0
readv(6, [{"", 0}, {"127.0.0.1\tlocalhost\n::1\tlocalhos"..., 1024}], 2) = 174
readv(6, [{"", 0}, {"127.0.0.1\tlocalhost\n::1\tlocalhos"..., 1024}], 2) = 0
close(6)                                = 0
open("/etc/resolv.conf", O_RDONLY|O_CLOEXEC) = 6
fcntl(6, F_SETFD, FD_CLOEXEC)           = 0
readv(6, [{"", 0}, {"search cloud.online.net\nnameserv"..., 248}], 2) = 62
readv(6, [{"", 0}, {"search cloud.online.net\nnameserv"..., 248}], 2) = 0
close(6)                                = 0
socket(PF_INET, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 6
bind(6, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
sendto(6, "\27\240\1\0\0\1\0\0\0\0\0\0\5redis\0\0\1\0\1", 23, MSG_NOSIGNAL, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.11")}, 16) = 23
sendto(6, "\31,\1\0\0\1\0\0\0\0\0\0\5redis\0\0\34\0\1", 23, MSG_NOSIGNAL, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.11")}, 16) = 23
poll([{fd=6, events=POLLIN}], 1, 2500)  = 1 ([{fd=6, revents=POLLIN}])
recvfrom(6, "\27\240\201\200\0\1\0\1\0\0\0\0\5redis\0\0\1\0\1\5redis\0\0\1"..., 512, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.11")}, [16]) = 44
recvfrom(6, "\31,\201\200\0\1\0\0\0\0\0\0\5redis\0\0\34\0\1", 512, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.11")}, [16]) = 23
close(6)                                = 0
socket(PF_INET, SOCK_STREAM, IPPROTO_IP) = 6
fcntl(6, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(6, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
connect(6, {sa_family=AF_INET, sin_port=htons(6379), sin_addr=inet_addr("172.21.0.2")}, 16) = -1 EINPROGRESS (Operation now in progress)
poll([{fd=6, events=POLLIN|POLLOUT|POLLERR|POLLHUP}], 1, 60000) = 1 ([{fd=6, revents=POLLOUT}])
getsockopt(6, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
fcntl(6, F_SETFL, O_RDWR)               = 0
sendto(6, "*2\r\n$6\r\nSELECT\r\n$1\r\n0\r\n", 23, MSG_DONTWAIT, NULL, 0) = 23
poll([{fd=6, events=POLLIN|POLLERR|POLLHUP}], 1, 60000) = 1 ([{fd=6, revents=POLLIN}])
recvfrom(6, "+OK\r\n", 8192, MSG_DONTWAIT, NULL, NULL) = 5
sendto(6, "*2\r\n$3\r\nGET\r\n$41\r\n_session_a8b5b"..., 61, MSG_DONTWAIT, NULL, 0) = 61
poll([{fd=6, events=POLLIN|POLLERR|POLLHUP}], 1, 60000) = 1 ([{fd=6, revents=POLLIN}])
recvfrom(6, "$-1\r\n", 8192, MSG_DONTWAIT, NULL, NULL) = 5
getpid()                                = 36
access("/var/www/html/app/config/../runtime/metadata/map-authcookie.php", F_OK) = 0
--- SIGILL {si_signo=SIGILL, si_code=ILL_ILLOPN, si_addr=0x7f279d98e63d} ---
+++ killed by SIGILL +++                                                                                                                                
```

I want to ask you for some updated instruction about how to compile phalcon inside a container to make it works on the both of servers.

**Comment by sergeyklay** [comment] 2018-08-05 07:38
@erickskrauch There is [an example](https://github.com/sergeyklay/mkimage) demonstrates how to compile Phalcon in [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/).

**Comment by sergeyklay** [comment] 2018-08-05 07:39
I want to close this issue because I don't want a bunch of these lying around and since this is a not a bug report. Feel free to discuss on the [official forums](https://forum.phalconphp.com), and/or the internals repo.

**Closed by sergeyklay** 2018-08-05 07:39 UTC

**Comment by erickskrauch** [comment] 2018-08-05 13:29
@sergeyklay thanks for your response. Actually, the problem was not related to PHP or Docker itself. It was related to gcc and CPU architecture. My current solution is the next:

```sh
FROM php:7.2.8-fpm-alpine3.7

ENV PHALCON_VERSION=3.4.0
ENV COMPOSER_ALLOW_SUPERUSER 1

# https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html
ARG gcc_arch=native
# https://gcc.gnu.org/onlinedocs/gcc-4.5.3/gcc/i386-and-x86_002d64-Options.html
ARG gcc_tune=native

# bash needed to support wait-for-it script
RUN apk add --update --no-cache \
    git \
    bash \
    openssh \
    dcron \
    # zip extension
    zlib-dev \
    # intl extension
    icu-dev \
    libintl \
    # gd extension
    freetype-dev \
    libjpeg-turbo-dev \
    libpng-dev \
 && docker-php-ext-configure gd \
    --with-freetype-dir=/usr/include/ \
    --with-jpeg-dir=/usr/include/ \
 && docker-php-ext-install -j$(nproc) gd zip pdo_mysql intl pcntl bcmath sockets opcache \
 && apk add --no-cache --virtual ".phpize-deps" $PHPIZE_DEPS \
 # Phalcon compilation
 && curl -sSL "https://codeload.github.com/phalcon/cphalcon/tar.gz/v${PHALCON_VERSION}" | tar -xz \
 && cd cphalcon-${PHALCON_VERSION}/build \
 && sed -i'' 's/-march=native/-march=${gcc_arch}/' install \
 && sed -i'' 's/-mtune=native/-mtune=${gcc_tune}/' install \
 && ./install \
 && cp ../tests/_ci/phalcon.ini ${PHP_INI_DIR}/conf.d/ \
 && cd ../../ \
 && rm -r cphalcon-${PHALCON_VERSION} \
 # End Phalcon compilation
 && yes | pecl install mongodb \
 && docker-php-ext-enable mongodb \
 && yes | pecl install xdebug-2.6.0 \
 && apk del ".phpize-deps" \
 && rm -rf /usr/share/man \
 && rm -rf /tmp/* \
 && mkdir /etc/cron.d
```

And CI step:

```yml
build:production:
  image: docker:18.02
  stage: build
  before_script:
    - docker login -u gitlab-ci -p $CI_BUILD_TOKEN registry.ely.by
    - export VERSION="${CI_COMMIT_TAG:-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA:0:7}}"
    - sed -i"" -e "s/{{PLACE_VERSION_HERE}}/$VERSION/g" common/config/config.php
  script:
    - export IMAGE_NAME="$CONTAINER_IMAGE:latest"
    - >
      docker build
      --pull
      --build-arg "build_env=prod"
      --build-arg "gcc_arch=${GCC_ARCH:-x86-64}"
      --build-arg "gcc_tune=${GCC_TUNE:-general}"
      -t $IMAGE_NAME .
  only:
    - develop
    - tags
```

It's okay, while we have a consistent production environment, but it'll become a problem if we begin using servers in data centers with different CPUs. Currently I see only one possible solution: compile multiple versions of Phalcon extension (per CPU arch), put them all in the container and let bootstrap script detect CPU arch and enable corresponding extension.

-------------

Anyway. I also want to ask: why PHP extensions don't require per-arch compilation and Phalcon do?

**Comment by sergeyklay** [comment] 2018-08-05 21:33
It is a part of optimization. You are free to use any compilation flags or even disable CPU optimization at all.

Using `-mtune=native` will produce code optimized for the local machine under the constraints of the selected instruction set.  Using `-march=native` will enable all instruction subsets supported by the local machine (hence the result might not run on different machines). 

Try to [play with default compiler flags](https://github.com/phalcon/cphalcon/blob/master/build/install#L27), to produce code optimized for the most common processors.

Usually I use something like this co install Phalcon from the `build` dir:
```shell
 ./install --phpize /usr/local/bin/phpize --php-config /usr/local/bin/php-config --arch 64bits
```

Also as I know [we use the same script](https://github.com/phalcongelist/packagecloud/blob/master/debian/rules#L54-L73) to build `*.deb` and `*.rmp` packages for all users. _Note: to build packages we don't use `install` script._
