### ISSUE TITLE
Find/FindFirst with related tables

### ISSUE THREAD

**Issue by williamokano** [phalcon/cphalcon#10586] opened 2015-07-02 15:54 UTC
Hi, I was playing a llittle bit with Phalcon and I faced the following "issue":

Imagine that I have 2 related tables

Employee -> belongsTo(Company)
Company -> hasMany(Employees)

Using the Table/Model Employee I would like to query the following, all Employees that works for a company A.

I don't like to do comparison but, on EntityFramework from .net I can do something like that

Employee.where(e => e.Company == "Company A").ToList() and this is very practical beucase I don't have to do a lot of join (as the model already knows how that table is related to another and vice-versa).

So my suggestion is, implement on Phalcon something like that:

Employees::Find('Company.Name = "Company A"');

I know that I can achieve the same results with the query builder doing joins, but I think that this way is easier and more elegant, don't you think?

PS.: I looked on Phalcon documentation (and also tried coding this snippet) and this doesn't work, it accuse that I have a DOT where it should not be. Also, as I the hasOne, hasMany, belongsTo or hasManyToMany is already defined, could use this "property" to use on my queries.

Suggestion: https://gist.github.com/williamokano/e23f67e65cdfab273d7a

**Comment by KorsaR-ZN** [comment] 2015-07-02 17:33
You can do so
```php
$company = Company::FindFirst('Name = "Company XPTO"');
$employees = $company->getEmployees();
```

**Comment by williamokano** [comment] 2015-07-02 17:37
Yeah, I know, but I think that the proposed syntax is more "logical" as I'm
looking for Employees I should use Employee model. Well, it's a suggestion
:)

**Comment by KorsaR-ZN** [comment] 2015-07-02 17:49
@williamokano I'm doing a similar functionality "request with the condition through a relationship". 
Like how YII `with()`, [see](https://github.com/yiisoft/yii2/blob/master/docs/guide/db-active-record.md#joining-with-relations-)

**Comment by williamokano** [comment] 2015-07-02 17:50
Yeah, I know but looks unnecessary to fetch a company to only then i can get the employees.

Also, in my case I'm building a rest api that request a resource, in that case an Employee.

On my rest I can send the query via querystring, so if I want to search for Empolyees that works on a campony I'll have to add if's and another conditionals for exceptions. (Sorry for deleting the previous comment, it was by e-mail)


Example: http://resturl/api/resource/employee?access_code=blahblah&q=(Company.Name='XPTO')


I'll check your link.

**Comment by KorsaR-ZN** [comment] 2015-07-02 17:53
@phalcon Please mark as `New Feature Request`

**Comment by carvajaldiazeduar** [comment] 2015-07-02 18:03
Duplicate of #1117

**Closed by carvajaldiazeduar** 2015-07-02 18:03 UTC
