### ISSUE TITLE
PHP7.0 + postgresql  = Get 502 Bad Gateway 

### ISSUE THREAD

**Issue by Doncode** [phalcon/cphalcon#11788] opened 2016-05-14 15:18 UTC
2016/05/14 10:51:29 [error] 3817#3817: *51950 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: ********, server: ********, request: "GET /index/show HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "****" 

When try this 
$users = Users::find();

**Comment by Jurigag** [comment] 2016-05-14 18:46
Are you using latest phalcon 2.1.x and zephir ?

**Comment by Doncode** [comment] 2016-05-14 20:22
Yes. I use  2.1.x
git status
On branch 2.1.x
Your branch is up-to-date with 'origin/2.1.x'.
commit 0a5b157f03452ec09bd032a217abfbc62cbebd53

**Comment by Doncode** [comment] 2016-05-14 21:07
save problem with mysql

**Comment by sergeyklay** [comment] 2016-05-14 21:19
Provide please php logs

**Comment by Jurigag** [comment] 2016-05-14 21:28
If you have 502 bad gateway while using php-fpm it bascially means that there are probably seg fault(if you sure you have right nginx config).

You should have crash generated. If don't then read this here https://bugs.php.net/bugs-generating-backtrace.php. First two points how to generate crash(ulimit and echo). Then you will get seg fault from php-fpm. Install gdb and run gdb php-fpm /path/to/crash and then post from gdb here.

**Comment by Doncode** [comment] 2016-05-14 21:36
nginx config is right
This works if the comment
//Users::find();

**Comment by sergeyklay** [comment] 2016-05-14 21:47
https://github.com/phalcon/cphalcon/wiki/Generating-a-backtrace

**Comment by stamster** [comment] 2016-05-15 11:42
Do you have info that PHP7 and latest PhalconPHP are still not married? So, this kind of errors are expected.

**Comment by Jurigag** [comment] 2016-05-15 12:07
As i wrote - generate backtrace and post it here. Right now we know NOTHING from you wrote here.

**Comment by tembem** [comment] 2016-05-24 10:23
Check your nginx configuration again. If you were using default installation, I think it should be:

```
fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
```

**Comment by Jurigag** [comment] 2016-05-24 10:26
But he is telling that without ```Users::find()``` everything works. So like for 99% he has seg fault and we need backtrace.

**Comment by stefanchiriac** [comment] 2016-06-09 07:35
@Jurigag I hope you realize that by asking of a core dump you're sending people to the C world. A common php developer just seeing that page will just give up. Even following that guide step by step is still confusing. I tried once, got nothing and I gave up.

To solve these kind of problems, a solution would be to try to replicated it yourself, or maybe write an example how it should be done.

These seg faults might be a real deal and not just some bad configs and if are not solved might pose a stability problem.

**Comment by sergeyklay** [comment] 2016-06-09 07:41
@Doncode I can't reproduce. Could you please provide more information: your Nginx config, script to reproduce, current PHP version, current Phalcon version, DB name and version an OS

**Comment by Jurigag** [comment] 2016-06-09 07:58
@stefanchiriac How to c world ? How did you get nothing ? I always on my servers/vps etc doing it step by step i always got core dump and result from gdb.

**Comment by stefanchiriac** [comment] 2016-06-09 08:50
GDB is a C/C++ debugger. I tried to use it for seg fault on cphalcon compiling with zephir and I find it quite confusing what paths I should put for that. Tried once, got nothing and gave up since is not a priority and my free time is very short these days.

**Comment by Jurigag** [comment] 2016-06-09 08:54
Yes it is, but you have everything in tutorial stated above.

**Comment by tembem** [comment] 2016-07-29 13:23
@Doncode Is it solved by branch 3.0.x?

**Comment by Jurigag** [comment] 2016-07-29 13:25
Just like for 99% it's happening beacause of this - https://github.com/phalcon/cphalcon/issues/11919

**Comment by sergeyklay** [comment] 2016-08-02 19:33
Fixed in the `3.0.x` branch.

**Closed by sergeyklay** 2016-08-02 19:33 UTC
Labels: Need information, Need script to reproduce, PHP 7
