### ISSUE TITLE
update failed when column contain reserved keyword

### ISSUE THREAD

**Issue by xiaochong0302** [phalcon/cphalcon#14560] opened 2019-11-29 03:01 UTC
```
// ORM style success
$order = Order::findFirstById(1);
$order->source= 'desktop';
$order->update();

// array style failed
$order = Order::findFirstById(1);
$order->update(['source' => 'desktop']);
```

**Comment by ruudboon** [comment] 2019-11-29 06:30
@xiaochong0302 what version of Phalcon are you running?

**Comment by xiaochong0302** [comment] 2019-11-29 10:15
> @xiaochong0302 what version of Phalcon are you running?

Version 3.4.4

**Comment by xiaochong0302** [comment] 2019-11-29 10:17
@ruudboon Version 3.4.4

**Comment by niden** [comment] 2019-11-30 00:44
@ruudboon I think this is a duplicate of #14538 which was resolved in https://github.com/phalcon/cphalcon/pull/14542 for v4.

We might be able to cherry pick the commit for v3

**Comment by ruudboon** [comment] 2019-11-30 16:14
@xiaochong0302 Closing this issue since it has been fixed in the 4 branch. Currently we don't have plans to release a new 3.4.x version.

**Closed by ruudboon** 2019-11-30 16:14 UTC
Labels: Duplicate, Fixed in 4.x
