### ISSUE TITLE
[2.0.4] Unable to use closure in filter

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#10632] opened 2015-07-09 20:23 UTC
I used a closure in a filter to do some simple filtering.
After upgrading I get the following error: Object of class Closure could not be converted to string in ..

```
$oPostcode = new Text('postcode', array(
            'placeholder' => 'Postcode'
));
$oPostcode->addFilter(function($vValue) {
            return strtoupper(str_replace(" ", "", $vValue));
});
```

**Comment by andresgutierrez** [comment] 2015-07-09 20:25
Was this supported before?

**Comment by ruudboon** [comment] 2015-07-09 20:29
It was working so I assumed it was supported. I think there is a thread somewhere regarding this functionality. Let me check..

**Comment by olivier-monaco** [comment] 2015-07-10 06:43
The argument of addFilter is the name of one filter in Phalcon\Filter. You can add closure un Phalcon\Filter using:

<pre>
$filter = $di->getShared('filter');
$filter->add('xxxx', function() { ... });

$oPostcode = new Text('postcode', array(
            'placeholder' => 'Postcode'
));
$oPostcode->addFilter('xxxx');
</pre>

**Comment by ruudboon** [comment] 2015-07-10 07:00
Thnx @olivier-monaco

**Comment by andresgutierrez** [comment] 2015-07-12 13:27
Closed as not a bug

**Closed by andresgutierrez** 2015-07-12 13:27 UTC
