### ISSUE TITLE
[NFR]: Update Phalcon Documentation Before New Phalcon Releases

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#14498] opened 2019-10-29 23:16 UTC
**Please do not remove or change anything that breaks phalcon from older version without properly commenting code, providing example code or at least updating phalcon documentation. Phalcon documentation should be updated before new version of phalcon is released. This is why there is too many people confused on GitHub submitting duplicated bugs.**

**Comment by niden** [comment] 2019-10-29 23:17
Do you have any examples of that happening right now?

**Comment by v00v** [comment] 2019-10-29 23:19
@niden Yes, I do actually. The newest ``$di->setShared('view')`` https://github.com/phalcon/cphalcon/issues/14496

**Comment by niden** [comment] 2019-10-29 23:26
You are jumping the gun here without waiting for us to react and honestly it is not fair for everyone. Some information:

https://github.com/phalcon/docs/issues/2322

This tracks our current update list of the v4 documentation. As you can see there are a bit short of 20 documents to review/revise. `Di` is one of them so the documentation for that has not been updated yet. You can check the status of the document being red here:

https://docs.phalcon.io/4.0/en/di

For documents that we have worked on and revised, they look like this:

https://docs.phalcon.io/4.0/en/cache

and also there is the upgrade document here:

https://docs.phalcon.io/4.0/en/upgrade#cache

(the above link shows directly what one needs to do for the `Cache` component in particular)

For the issue you outlined #14496 , it was a duplicate of #14491 and there is work underway for it in this PR: https://github.com/phalcon/cphalcon/pull/14497

I applaud your enthusiasm and thank you for diligence. Just check the issues and PRs just in case something is already being addressed or is duplicate.

**Comment by v00v** [comment] 2019-10-29 23:26
@niden okay, its just that it worked fine in RC1 and in RC2 it broke some code. All I'm saying is that if something breaks / changes / removed from version to version to properly comment, document or at least provide example code in phalcon changelog. This will eliminate anyone from submitting duplicate bugs or new related issues completely. Correct me if I'm wrong, but at the time RC2 was released there were no hint about ``$di->setShared`` for views and documentation was not updated. Not all people can read / code in zephir to figure out all this changes.

**Comment by v00v** [comment] 2019-10-29 23:28
@niden okay thank you!

**Comment by niden** [comment] 2019-10-29 23:30
That is my point exactly. It happened after we released the code, our tests did not pick that up. A user reported it and we are working to fix it. Nothing else to it really. It is just like any other bug that has been found. The fact that all these are being reported now is great.

Honestly I don't know why you thought that this was an intended/design change - it was not in the `upgrade` doc. But either way. We are on it.

Thank you again for keeping a close eye out :)

**Comment by v00v** [comment] 2019-10-29 23:31
Why do you do RC versions instead of beta. As I understand from wikipedia;

Release candidate - **A release candidate (RC), also known as "going silver", is a beta version with potential to be a final product, which is ready to release unless significant bugs emerge.**

RC version should NOT have any removals or changes that break version from previous version.

Source: https://en.wikipedia.org/wiki/Software_release_life_cycle#Release_candidate

**Comment by niden** [comment] 2019-10-29 23:33
As with any software, bugs can and will appear. alpha, beta, RC or even stable versions suffer from those. This was not a change that was intended. Just a change that brought unintended consequences. We just need to add a few more tests to our suite so that the particular bug is caught if it appears again. 

That was it really.

**Comment by v00v** [comment] 2019-10-29 23:34
@niden Thank you for explaining. Keep up the great work you guys do!

**Closed** 2019-10-30 08:45 UTC
Labels: Feature - NFR
