### ISSUE TITLE
Why did array changes after calling a "partial" in the views?

### ISSUE THREAD

**Issue by yesworld** [phalcon/cphalcon#13551] opened 2018-10-24 13:01 UTC
### I updated my project from Phalcon3.3.1+php5.6 to 3.4.1+php7.2.
[https://github.com/yesworld/simple-example-phalcon](https://github.com/yesworld/simple-example-phalcon)

```php
/* /var/www/phalcon4.3.1/app/views/index/index.phtml:5: */
array (size=4)
  0 => 
    array (size=3)
      0 => int 0
      1 => int 1
      2 => int 2
  1 => 
    array (size=3)
      3 => int 3
      4 => int 4
      5 => int 5

additional pattern... // call $this->partial('partials/text');

/* /var/www/phalcon4.3.1/app/views/index/index.phtml:9: */
array (size=11)
  0 => int 0
  1 => int 1
  2 => int 2
  3 => int 3
  4 => int 4
  5 => int 5
  6 => int 6
```
> Provide minimal script to reproduce the issue

```php
/* in the IndexController */
class IndexController extends \Phalcon\Mvc\Controller
{
    public function indexAction()
    {
        $this->view->setVar('testArray', range(0, 10));
        $this->view->pick('index/index');
    }
}

/* in the view */
$testArray = array_chunk($testArray, 3, TRUE);
var_dump($testArray);

$this->partial('partials/text');  //<b>additional pattern... </b>

var_dump($testArray);
```

### Details

* Phalcon version: (`php --ri phalcon`)
> Web framework delivered as a C-extension for PHP
> phalcon => enabled
> Author => Phalcon Team and contributors
> Version => 3.4.1
> Build Date => Aug  6 2018 05:47:21
> Powered by Zephir => Version 0.10.10-d1b4cc68d9
> 
> Directive => Local Value => Master Value
> phalcon.db.escape_identifiers => On => On
> phalcon.db.force_casting => Off => Off
> phalcon.orm.events => On => On
> phalcon.orm.virtual_foreign_keys => On => On
> phalcon.orm.column_renaming => On => On
> phalcon.orm.not_null_validations => On => On
> phalcon.orm.exception_on_failed_save => Off => Off
> phalcon.orm.enable_literals => On => On
> phalcon.orm.late_state_binding => Off => Off
> phalcon.orm.enable_implicit_joins => On => On
> phalcon.orm.cast_on_hydrate => Off => Off
> phalcon.orm.ignore_unknown_columns => Off => Off
> phalcon.orm.update_snapshot_on_save => On => On
> phalcon.orm.disable_assign_setters => Off => Off

* PHP Version: (`php -v`)
> PHP 7.2.11-2+ubuntu14.04.1+deb.sury.org+1 (cli) (built: Oct 15 2018 12:49:02) ( NTS )
> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
>     with Zend OPcache v7.2.11-2+ubuntu14.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
>     with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans

* Operating System: ubuntu14.04.1
* Installation type: installing via package manager
* Zephir version (if any): none
* Server: Nginx
* Other related info (Database, table schema):  none

**Comment by Jurigag** [comment] 2018-10-25 16:05
This is a known bug, you need to user other name for partial parameter than variable. Duplicate of https://github.com/phalcon/cphalcon/issues/12176

**Closed by Jurigag** 2018-10-25 16:05 UTC
