### ISSUE TITLE
Phalcon 2.0 Controller action return false -> view blank

### ISSUE THREAD

**Issue by kimthangatm** [phalcon/cphalcon#10352] opened 2015-05-14 17:30 UTC
Phalcon 2.0 Controller action return false -> view blank
```php
public function newAction()
    {
        $this->_toolbar->addBreadcrumb(['title' => 'm_admin_menu_slide']);
        $this->_toolbar->addBreadcrumb(['title' => 'm_admin_manage_slide']);
        $this->_toolbar->addBreadcrumb(['title' => 'm_admin_manage_slide_new_slide']);
        $this->_toolbar->addHeaderPrimary('m_admin_manage_slide_new_slide');
        $this->_toolbar->addSaveButton('slide|index|new');
        $this->_toolbar->addCancelButton('slide|index|index', '/admin/slide/');
        $form = new SlideShowForm();
        $this->view->setVar('form', $form);

        if ($this->request->isPost()) {
            $slideShow = new SlideShows();
            if ($form->isValid($_POST, $slideShow)) {
                if ($slideShow->save()) {
                    $imageStatus = ZImageHelper::uploadImages($this->request->getUploadedFiles(), self::SLIDE_SHOW_FOLDER_UPLOAD . '/' . $slideShow->id, 'image');
                    if ($imageStatus['status']) {
                        $slideShow->image = $imageStatus['imageUrl'];
                        $slideShow->save();
                    } else {
                        if ($imageStatus['message']) {
                            $this->flashSession->notice($imageStatus['message']);
                        }
                        if ($imageStatus['bugMessage']) {
                            $this->flashSession->notice($imageStatus['bugMessage']);
                        }
                    }
                    $this->flashSession->success('Add new slide show successfully');
                    return $this->response->redirect('/admin/slide/index/edit/' . $slideShow->id . '/');
                } else {
                    $this->setFlashSession($slideShow->getMessages(), 'notice');
                }
            }
        }
        return false; //RETURN FALSE -> VIEW BLANK
    }
```

**Comment by Green-Cat** [comment] 2015-05-14 17:57
That seems to be expected behaviour to me?

**Comment by andresgutierrez** [comment] 2015-08-23 03:11
Closed as this is the expected behavior

**Closed by andresgutierrez** 2015-08-23 03:11 UTC
