### ISSUE TITLE
Add more options to Volt configurations

### ISSUE THREAD

**Issue by Kachit** [phalcon/cphalcon#9984] opened 2015-04-08 12:39 UTC
Add more options to Volt configurations like a twig. for example:
[
   'tag_variable_start' =>'{{', 
   'tag_variable_end' =>'}}'
] 
Maybe this options solve problem with volt and angularjs binds

**Comment by sergeyklay** [comment] 2015-04-09 18:45
+1

**Comment by andresgutierrez** [comment] 2015-04-09 19:51
Duplicate of #2290

**Closed by andresgutierrez** 2015-04-09 19:51 UTC
