### ISSUE TITLE
Potential memory leak in DI

### ISSUE THREAD

**Issue by Mechzeit** [phalcon/cphalcon#10731] opened 2015-07-28 01:41 UTC
Hi guys,

I'm not sure if anyone can explain this or not, but to me this should not be happening.
To put it shortly, every time I call getShared() from the DI container my memory will increase by < 1024 bytes each call.

I've created an example script that has a service of a class that uses 1mB of memory when instantiated - So you can tell it's definitely not the class being instantiated over and over.

```php
<?php
use Phalcon\DI;
echo sprintf("Point #1: %s kB\n", memory_get_usage () / 1024);

$di = new DI();
echo sprintf("Point #2: %s kB\n", memory_get_usage () / 1024);

class TestClass
{
	public $data;
	public function __construct()
	{
		$this->data = openssl_random_pseudo_bytes (1024 * 1024);
	}
}

$di->setShared('testservice', function(){ return new TestClass(); });

echo sprintf("Point #3: %s kB\n", memory_get_usage () / 1024);

/**
* Copy + Paste the below line 100 times for example
* and you'll see overall memory usage increase a tiny bit
**/
$di->getShared('testservice');
$di->getShared('testservice');
$di->getShared('testservice');


echo sprintf("Point #4: %s kB\n", memory_get_usage () / 1024);
```

Output for that script should be around 

```
Point #1: 225.3671875 kB
Point #2: 236.640625 kB
Point #3: 237.40625 kB
Point #4: 1261.828125 kB
```

However if you replace those 3 getShared lines with 25 of them, you'll find memory has increased a little

```
Point #1: 233.9140625 kB
Point #2: 245.203125 kB
Point #3: 245.96875 kB
Point #4: 1270.390625 kB
```

The weird thing is, if you place the `$di->getShared()` inside a loop, it will not increase memory more than once.
eg:

```php
$di->getShared('testservice');
$di->getShared('testservice');
$di->getShared('testservice');
$di->getShared('testservice');
// will use the same amount of memory as...
for($i=0;$i<100;$i++){
    $di->getShared('testservice');
    $di->getShared('testservice');
    $di->getShared('testservice');
    $di->getShared('testservice');
}
```

*Please note I've tried managing the memory myself with setting getShared() against a variable, then unsetting it but it makes no difference.*

Is this a bug or am I going crazy?

**Comment by andresgutierrez** [comment] 2015-07-28 16:05
I'm running your example in PHP 5.6 compiled in debug mode:

```php
$ php -v
PHP 5.6.7 (cli) (built: Jun 18 2015 15:50:10) (DEBUG)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
```

```cli
$ php  t.php 
Point #1: 254.4296875 kB
Point #2: 255.140625 kB
Point #3: 256.71875 kB
Point #4: 1282.03125 kB
```

No memory leaks are reported. PHP allocates memory in chunks of 256kb. So it looks that in Point #4 it's increasing the memory to 1024kb+256kb as it does not have any free pages available. A different story seems to happen in the loop where some temporary variable seems to be recycled properly.

**Comment by Mechzeit** [comment] 2015-07-28 23:39
I just found it odd that each call to `    $di->getShared('testservice');` would increase the overall used memory by 0.6~ kB despite no references existing. But you're saying it's expected behaviour?

**Comment by andresgutierrez** [comment] 2015-07-29 00:34
Given that PHP in debug mode is not reporting any memory leaks after executing the example, I'm not sure how this can be classified like that.  Shared services keep internal references to created objects as they work as singletons. What version of PHP are you using?

**Comment by Mechzeit** [comment] 2015-07-29 01:01
It's not the example that is leaking memory though, it's each call to `    $di->getShared('testservice');`

I'm using Phalcon 2.0.5 on PHP 5.5 VC11 TS

**Comment by ovr** [comment] 2015-07-30 06:17
It's not a bug

```php
<?php
use Phalcon\DI;
echo sprintf("Point #1: %s kB\n", memory_get_usage () / 1024);

$di = new DI();
echo sprintf("Point #2: %s kB\n", memory_get_usage () / 1024);

class TestClass
{
    public $data;
    public function __construct()
    {
        $this->data = openssl_random_pseudo_bytes (1024 * 1024);
    }
}

$di->setShared('testservice', function(){ return new TestClass(); });

var_dump(spl_object_hash($di->getShared('testservice')));
var_dump(spl_object_hash($di->getShared('testservice')));
var_dump(spl_object_hash($di->getShared('testservice')));
var_dump(spl_object_hash($di->getShared('testservice')));
var_dump(spl_object_hash($di->getShared('testservice')));
var_dump(spl_object_hash($di->getShared('testservice')));
var_dump(spl_object_hash($di->getShared('testservice')));
var_dump(spl_object_hash($di->getShared('testservice')));
var_dump(spl_object_hash($di->getShared('testservice')));
var_dump(spl_object_hash($di->getShared('testservice')));

echo sprintf("Point #4: %s kB\n", memory_get_usage () / 1024);

var_dump(spl_object_hash($di->getShared('testservice')));
var_dump(spl_object_hash($di->getShared('testservice')));
var_dump(spl_object_hash($di->getShared('testservice')));
var_dump(spl_object_hash($di->getShared('testservice')));
var_dump(spl_object_hash($di->getShared('testservice')));
var_dump(spl_object_hash($di->getShared('testservice')));
var_dump(spl_object_hash($di->getShared('testservice')));
var_dump(spl_object_hash($di->getShared('testservice')));
var_dump(spl_object_hash($di->getShared('testservice')));

echo sprintf("Point #5: %s kB\n", memory_get_usage () / 1024);
```

```sh
php 1.phph 
Point #1: 255.40625 kB
Point #2: 255.71875 kB
string(32) "000000001ae06e82000000003dfcd154"
string(32) "000000001ae06e82000000003dfcd154"
string(32) "000000001ae06e82000000003dfcd154"
string(32) "000000001ae06e82000000003dfcd154"
string(32) "000000001ae06e82000000003dfcd154"
string(32) "000000001ae06e82000000003dfcd154"
string(32) "000000001ae06e82000000003dfcd154"
string(32) "000000001ae06e82000000003dfcd154"
string(32) "000000001ae06e82000000003dfcd154"
string(32) "000000001ae06e82000000003dfcd154"
Point #4: 1281.15625 kB
string(32) "000000001ae06e82000000003dfcd154"
string(32) "000000001ae06e82000000003dfcd154"
string(32) "000000001ae06e82000000003dfcd154"
string(32) "000000001ae06e82000000003dfcd154"
string(32) "000000001ae06e82000000003dfcd154"
string(32) "000000001ae06e82000000003dfcd154"
string(32) "000000001ae06e82000000003dfcd154"
string(32) "000000001ae06e82000000003dfcd154"
string(32) "000000001ae06e82000000003dfcd154"
Point #5: 1281.15625 kB
```

**Comment by sergeyklay** [comment] 2015-07-30 08:01
Confirm.

```php
<?php
use Phalcon\DI;
echo sprintf("Point #1: %s kB\n", memory_get_usage () / 1024);

$di = new DI();
echo sprintf("Point #2: %s kB\n", memory_get_usage () / 1024);

class TestClass
{
    public $data;
    public function __construct()
    {
        $this->data = openssl_random_pseudo_bytes (1024 * 1024);
    }
}

$di->setShared('testservice', function(){ return new TestClass(); });

for ($i = 4; $i <= 1004; $i++) {
	$di->getShared('testservice');
	$di->getShared('testservice');
	$di->getShared('testservice');
	$di->getShared('testservice');
	$di->getShared('testservice');
	$di->getShared('testservice');
	$di->getShared('testservice');
	$di->getShared('testservice');
	$di->getShared('testservice');
	$di->getShared('testservice');
	$di->getShared('testservice');

	if (!mt_rand(0, 100)) {
		echo sprintf("Point #%s: %s kB\n", $i, memory_get_usage () / 1024);	
	}
}
```

Output:
```
$ php di_test.php 
Point #1: 241.3046875 kB
Point #2: 241.6015625 kB
Point #4: 1267.2578125 kB
Point #527: 1267.2578125 kB
Point #652: 1267.2578125 kB
Point #865: 1267.2578125 kB
Point #909: 1267.2578125 kB
```

**Comment by andresgutierrez** [comment] 2015-08-28 21:32
Closed as not a bug

**Closed by andresgutierrez** 2015-08-28 21:32 UTC
Labels: Not a bug
