### ISSUE TITLE
Volt tag spaceless

### ISSUE THREAD

**Issue by kniaz-tolya** [phalcon/cphalcon#10952] opened 2015-09-16 15:26 UTC
Please add to volt tag spaceless

``` HTML
{% spaceless %}
    <div>
        <strong>foo</strong>
    </div>
{% endspaceless %}
```

``` HTML
{# output will be <div><strong>foo</strong></div> #}
```

**Comment by andresgutierrez** [comment] 2015-09-16 15:27
Duplicate of #2668

**Comment by kniaz-tolya** [comment] 2015-09-16 16:02
I have seen. But this past year. If not how to write, for example, in volt only function and filters

**Closed** 2018-01-01 09:12 UTC
Labels: Volt
