### ISSUE TITLE
Failure installing phalcon 3.2.1 extension on php 7.1.7 with phpbrew

### ISSUE THREAD

**Issue by StaymanHou** [phalcon/cphalcon#12976] opened 2017-07-21 21:45 UTC
Installing phalcon 3.2.1 extension on php 7.1.7 with phpbrew throws error

* Phalcon version: 3.2.1
* PHP Version: 7.1.7
* Operating System: Ubuntu 16.04
* Installation type: installing via phpbrew extension

Installation cmd and output

```bash
$ phpbrew ext install github:phalcon/cphalcon@phalcon-v3.2.1
Downloading https://github.com/phalcon/cphalcon/archive/master.tar.gz via curl extension
Redirecting to https://codeload.github.com/phalcon/cphalcon/tar.gz/master
[==================================================================] 6.26/6.26MB 100%
===> Extracting to /home/stayman/.phpbrew/build/php-7.1.7/ext...
===> Rename source directory to /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon...
===> Installing phalcon extension...
Log stored at: /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/build.log
Changing directory to /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext
===> Phpize...
===> Configuring...
===> Building...
===> Running make all: /usr/bin/make -C '/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext' 'all'  >> '/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/build.log' 2>&1
Error: Command failed: /usr/bin/make -C '/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext' 'all'  >> '/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/build.log' 2>&1 returns:
The last 5 lines in the log file:
 ZEND_API void _zval_ptr_dtor(zval *zval_ptr ZEND_FILE_LINE_DC);

               ^

Makefile:194: recipe for target 'phalcon.lo' failed

make: *** [phalcon.lo] Error 1

make: Leaving directory '/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext'

Please checkout the build log file for more details:
	 tail /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/build.log
```

```
# /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/build.log
Configuring for:
PHP Api Version:         20160303
Zend Module Api No:      20160303
Zend Extension Api No:   320160303
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /home/stayman/.phpbrew/php/php-7.1.7
checking for PHP includes... -I/home/stayman/.phpbrew/php/php-7.1.7/include/php -I/home/stayman/.phpbrew/php/php-7.1.7/include/php/main -I/home/stayman/.phpbrew/php/php-7.1.7/include/php/TSRM -I/home/stayman/.phpbrew/php/php-7.1.7/include/php/Zend -I/home/stayman/.phpbrew/php/php-7.1.7/include/php/ext -I/home/stayman/.phpbrew/php/php-7.1.7/include/php/ext/date/lib
checking for PHP extension directory... /home/stayman/.phpbrew/php/php-7.1.7/lib/php/extensions/no-debug-non-zts-20160303
checking for PHP installed headers prefix... /home/stayman/.phpbrew/php/php-7.1.7/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.16 (ok)
checking for gawk... gawk
checking whether to enable phalcon... yes, shared
checking whether HAVE_BUNDLED_PCRE is declared... yes
checking for ext/pcre/php_pcre.h... yes
checking whether HAVE_JSON is declared... yes
checking for ext/json/php_json.h... yes
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 1572864
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
make: Entering directory '/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext'
/bin/bash /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/libtool --mode=compile cc  -I. -I/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext -DPHP_ATOM_INC -I/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/include -I/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/main -I/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext -I/home/stayman/.phpbrew/php/php-7.1.7/include/php -I/home/stayman/.phpbrew/php/php-7.1.7/include/php/main -I/home/stayman/.phpbrew/php/php-7.1.7/include/php/TSRM -I/home/stayman/.phpbrew/php/php-7.1.7/include/php/Zend -I/home/stayman/.phpbrew/php/php-7.1.7/include/php/ext -I/home/stayman/.phpbrew/php/php-7.1.7/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c -o phalcon.lo 
mkdir .libs
 cc -I. -I/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext -DPHP_ATOM_INC -I/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/include -I/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/main -I/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext -I/home/stayman/.phpbrew/php/php-7.1.7/include/php -I/home/stayman/.phpbrew/php/php-7.1.7/include/php/main -I/home/stayman/.phpbrew/php/php-7.1.7/include/php/TSRM -I/home/stayman/.phpbrew/php/php-7.1.7/include/php/Zend -I/home/stayman/.phpbrew/php/php-7.1.7/include/php/ext -I/home/stayman/.phpbrew/php/php-7.1.7/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c  -fPIC -DPIC -o .libs/phalcon.o
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/php_phalcon.h:11:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/php_ext.h:4,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:14:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/kernel/globals.h:64:2: error: unknown type name ‘zend_uint’
  zend_uint times;
  ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:14:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/forms/element.zep.h:38:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Forms_Element(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:19:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/mvc/model/validator.zep.h:12:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Mvc_Model_Validator(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:33:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/db/adapter.zep.h:63:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Db_Adapter(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:35:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/logger/adapter.zep.h:22:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Logger_Adapter(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:56:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/application.zep.h:15:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Application(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:62:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/dispatcher.zep.h:41:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Dispatcher(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:112:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/mvc/router.zep.h:47:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Mvc_Router(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:140:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/assets/collection.zep.h:44:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Assets_Collection(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:169:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/cli/console.zep.h:9:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Cli_Console(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:171:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/cli/dispatcher.zep.h:19:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Cli_Dispatcher(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:173:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/cli/router.zep.h:25:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Cli_Router(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:205:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/debug/dump.zep.h:17:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Debug_Dump(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:237:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/forms/form.zep.h:38:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Forms_Form(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:247:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/http/response/headers.zep.h:14:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Http_Response_Headers(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:254:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/loader.zep.h:25:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Loader(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:271:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/mvc/collection.zep.h:55:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Mvc_Collection(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:282:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/mvc/micro.zep.h:41:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Mvc_Micro(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:287:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/mvc/model.zep.h:101:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Mvc_Model(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:290:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/mvc/model/binder.zep.h:15:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Mvc_Model_Binder(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:293:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/mvc/model/manager.zep.h:71:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Mvc_Model_Manager(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:295:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/mvc/model/metadata/apc.zep.h:9:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Mvc_Model_MetaData_Apc(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:296:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/mvc/model/metadata/files.zep.h:9:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Mvc_Model_MetaData_Files(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:297:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/mvc/model/metadata/libmemcached.zep.h:10:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Mvc_Model_MetaData_Libmemcached(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:298:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/mvc/model/metadata/memcache.zep.h:10:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Mvc_Model_MetaData_Memcache(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:299:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/mvc/model/metadata/memory.zep.h:9:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Mvc_Model_MetaData_Memory(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:300:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/mvc/model/metadata/redis.zep.h:10:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Mvc_Model_MetaData_Redis(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:304:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/mvc/model/metadata/xcache.zep.h:9:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Mvc_Model_MetaData_Xcache(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:328:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/mvc/router/annotations.zep.h:14:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Mvc_Router_Annotations(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:337:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/mvc/view.zep.h:63:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Mvc_View(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:367:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/translate/adapter/csv.zep.h:10:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Translate_Adapter_Csv(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:374:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/validation.zep.h:27:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Validation(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.h:377:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:15:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon/validation/message/group.zep.h:21:1: error: unknown type name ‘zend_object_value’
 zend_object_value zephir_init_properties_Phalcon_Validation_Message_Group(zend_class_entry *class_type TSRMLS_DC);
 ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/kernel/main.h:27:0,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:24:
./kernel/exception.h:60:67: error: unknown type name ‘zend_uint’
 void zephir_throw_exception_debug(zval *object, const char *file, zend_uint line TSRMLS_DC);
                                                                   ^
./kernel/exception.h:61:85: error: unknown type name ‘zend_uint’
 void zephir_throw_exception_string_debug(zend_class_entry *ce, const char *message, zend_uint message_len, const char *file, zend_uint line TSRMLS_DC);
                                                                                     ^
./kernel/exception.h:61:126: error: unknown type name ‘zend_uint’
 void zephir_throw_exception_string_debug(zend_class_entry *ce, const char *message, zend_uint message_len, const char *file, zend_uint line TSRMLS_DC);
                                                                                                                              ^
./kernel/exception.h:62:79: error: unknown type name ‘zend_uint’
 void zephir_throw_exception_string(zend_class_entry *ce, const char *message, zend_uint message_len TSRMLS_DC);
                                                                               ^
./kernel/exception.h:64:95: error: unknown type name ‘zend_uint’
 void zephir_throw_exception_zval_debug(zend_class_entry *ce, zval *message, const char *file, zend_uint line TSRMLS_DC);
                                                                                               ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:24:0:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/kernel/main.h: In function ‘zephir_maybe_separate_zval’:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/kernel/main.h:113:6: warning: implicit declaration of function ‘Z_REFCOUNT_PP’ [-Wimplicit-function-declaration]
  if (Z_REFCOUNT_PP(z) > 1 && !Z_ISREF_PP(z)) {
      ^
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/kernel/main.h:113:31: warning: implicit declaration of function ‘Z_ISREF_PP’ [-Wimplicit-function-declaration]
  if (Z_REFCOUNT_PP(z) > 1 && !Z_ISREF_PP(z)) {
                               ^
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/kernel/main.h:116:3: warning: implicit declaration of function ‘ALLOC_ZVAL’ [-Wimplicit-function-declaration]
   ALLOC_ZVAL(new_zv);
   ^
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/kernel/main.h:83:3: warning: implicit declaration of function ‘Z_UNSET_ISREF_P’ [-Wimplicit-function-declaration]
   Z_UNSET_ISREF_P(z);
   ^
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/kernel/main.h:117:3: note: in expansion of macro ‘INIT_PZVAL_COPY’
   INIT_PZVAL_COPY(new_zv, *z);
   ^
In file included from /home/stayman/.phpbrew/php/php-7.1.7/include/php/Zend/zend.h:39:0,
                 from /home/stayman/.phpbrew/php/php-7.1.7/include/php/main/php.h:35,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:8:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/kernel/fcall.h: In function ‘zephir_return_call_function’:
/home/stayman/.phpbrew/php/php-7.1.7/include/php/Zend/zend_variables.h:110:48: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type [-Wincompatible-pointer-types]
 #define zval_ptr_dtor(zval_ptr) _zval_ptr_dtor((zval_ptr) ZEND_FILE_LINE_CC)
                                                ^
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/kernel/fcall.h:518:3: note: in expansion of macro ‘zval_ptr_dtor’
   zval_ptr_dtor(return_value_ptr);
   ^
/home/stayman/.phpbrew/php/php-7.1.7/include/php/Zend/zend_variables.h:100:15: note: expected ‘zval * {aka struct _zval_struct *}’ but argument is of type ‘zval ** {aka struct _zval_struct **}’
 ZEND_API void _zval_ptr_dtor(zval *zval_ptr ZEND_FILE_LINE_DC);
               ^
In file included from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:25:0:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/kernel/fcall.h:526:4: warning: implicit declaration of function ‘ALLOC_INIT_ZVAL’ [-Wimplicit-function-declaration]
    ALLOC_INIT_ZVAL(*return_value_ptr);
    ^
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/kernel/fcall.h:533:3: warning: implicit declaration of function ‘COPY_PZVAL_TO_ZVAL’ [-Wimplicit-function-declaration]
   COPY_PZVAL_TO_ZVAL(*return_value, rv);
   ^
In file included from /home/stayman/.phpbrew/php/php-7.1.7/include/php/Zend/zend.h:39:0,
                 from /home/stayman/.phpbrew/php/php-7.1.7/include/php/main/php.h:35,
                 from /home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/phalcon.c:8:
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/kernel/fcall.h: In function ‘zephir_return_call_zval_function’:
/home/stayman/.phpbrew/php/php-7.1.7/include/php/Zend/zend_variables.h:110:48: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type [-Wincompatible-pointer-types]
 #define zval_ptr_dtor(zval_ptr) _zval_ptr_dtor((zval_ptr) ZEND_FILE_LINE_CC)
                                                ^
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/kernel/fcall.h:555:3: note: in expansion of macro ‘zval_ptr_dtor’
   zval_ptr_dtor(return_value_ptr);
   ^
/home/stayman/.phpbrew/php/php-7.1.7/include/php/Zend/zend_variables.h:100:15: note: expected ‘zval * {aka struct _zval_struct *}’ but argument is of type ‘zval ** {aka struct _zval_struct **}’
 ZEND_API void _zval_ptr_dtor(zval *zval_ptr ZEND_FILE_LINE_DC);
               ^
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/kernel/fcall.h: In function ‘zephir_return_call_class_method’:
/home/stayman/.phpbrew/php/php-7.1.7/include/php/Zend/zend_variables.h:110:48: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type [-Wincompatible-pointer-types]
 #define zval_ptr_dtor(zval_ptr) _zval_ptr_dtor((zval_ptr) ZEND_FILE_LINE_CC)
                                                ^
/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext/kernel/fcall.h:596:3: note: in expansion of macro ‘zval_ptr_dtor’
   zval_ptr_dtor(return_value_ptr);
   ^
/home/stayman/.phpbrew/php/php-7.1.7/include/php/Zend/zend_variables.h:100:15: note: expected ‘zval * {aka struct _zval_struct *}’ but argument is of type ‘zval ** {aka struct _zval_struct **}’
 ZEND_API void _zval_ptr_dtor(zval *zval_ptr ZEND_FILE_LINE_DC);
               ^
Makefile:194: recipe for target 'phalcon.lo' failed
make: *** [phalcon.lo] Error 1
make: Leaving directory '/home/stayman/.phpbrew/build/php-7.1.7/ext/phalcon/ext'
```

I've checked issue #12062. My machine has 16G memory, so it should be enough.

**Comment by StaymanHou** [comment] 2017-07-21 22:02
Figured out a workaround myself. Use the following command to install it manually instead of the `phpbrew ext install` command.

`./install --phpize /home/stayman/.phpbrew/php/php-7.1.7/bin/phpize --php-config /home/stayman/.phpbrew/php/php-7.1.7/bin/php-config` (Remember to replace the home path)

It would still be nice if the `phpbrew ext install` command works.

**Comment by sergeyklay** [comment] 2017-07-22 06:41
I'm closing since this is a not a bug report (at least it is not related to the Phalcon ). Feel free to discuss this on the [official forums](https://forum.phalconphp.com), and/or the internals repo. Thank you for contributing.

**Closed by sergeyklay** 2017-07-22 06:41 UTC
