### ISSUE TITLE
[BUG] 1.3.3 & 1.3.2 Redirect Infinite Loop

### ISSUE THREAD

**Issue by gunesahmet** [phalcon/cphalcon#2825] opened 2014-09-20 13:17 UTC
This code working.
define('base_url','index.php?url_=/');
return  $this->response->redirect(base_url.'dashboard');

When i change with this starting infinite loop
define('base_url','index.php/');
return  $this->response->redirect(base_url.'dashboard');

I read all logs and i try everything but I could not stop it.

Btw i using Debian 7.2 on Apache and lighttpd with php 5.4.

**Comment by andresgutierrez** [comment] 2015-06-25 02:40
Closed as not a bug

**Closed by andresgutierrez** 2015-06-25 02:40 UTC
Labels: Not a bug
