### ISSUE TITLE
Volt variables aren't available in the child views

### ISSUE THREAD

**Issue by dedalozzo** [phalcon/cphalcon#2660] opened 2014-08-01 00:51 UTC
This might not be a bug, maybe it's just the way you implemented it. Anyway, when I define a variable in index.volt, the same variable is not available in layouts/index.volt. Only a variable declared in the controller is global

`IndexController`
```php
$this->view->setVar('bar', 'Hi');
```

`index.volt`
```
{% set foo = 'Hello' %}
```

In `layouts/index.volt` the variable `foo` is not defined, instead `bar` is defined.

I think it will be helpful add a parameter to the setVar() method to define it `global`.

**Comment by andresgutierrez** [comment] 2015-08-23 01:44
Could you please try again using Phalcon 2 or provide a full script to reproduce the issue?

**Comment by sergeyklay** [comment] 2016-06-09 21:00
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Closed by sergeyklay** 2016-06-09 21:00 UTC
Labels: Need information
