### ISSUE TITLE
Module Routing Not Working as Expected

### ISSUE THREAD

**Issue by dasfisch** [phalcon/cphalcon#11257] opened 2015-12-23 00:22 UTC
I'm writing an API app, complete with a versioning strategy. I found something really weird happening in the routing of modules.

Here's the problem:

/v1 | /v1/ - Doesn't work
/v1/users | /v1/users/ - Works fine
/v1/users/1 | /v1/users/1/ - Works fine
/v1/users/1/permissions | /v1/users/1/permissions - Works fine
Here's the router itself:

```
$di->set('router', function () {
    $router = new Router(false);

    $router->setDefaultAction('index');
    $router->setDefaultController('index');

    $router->add('/:module/:controller/:params', array(
        'module' => 1,
        'controller' => 2,
        'params' => 3
    ));

    $router->removeExtraSlashes(true);

    return $router;
});
```

I posted to StackOverflow and to the forums on phalconphp.com. Generally, there are possibilities to get around this issue, but I was hoping we could get a fix in. I don't see the point in having hacks, when there is an issue. 

I'm on Phalcon v2.0.8. 

Let me know what you guys think!

Thanks! Happy Holidays!

**Comment by Jurigag** [comment] 2015-12-23 00:41
There is indexcontroller in v1 module ?

**Comment by dasfisch** [comment] 2015-12-23 01:21
Yes, the index controller does exist, and the router does work if I do /v1/index/. Just /v1/ does not work.

**Comment by Myrai** [comment] 2016-01-24 15:28
with $router->removeExtraSlashes(true); not one with slash in end not work,
if you want optional slash use [/].
and with own module without controller - route not work. 
    $router->setDefaultAction('index');
    $router->setDefaultController('index');
this not help you.

**Comment by sergeyklay** [comment] 2017-07-29 08:59
Completely impossible to reproduce bug, could be web server rewrite issues (or anything really, who knows). I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Closed by sergeyklay** 2017-07-29 08:59 UTC
