### ISSUE TITLE
Occasionally can't get value from memcache.

### ISSUE THREAD

**Issue by gotoin** [phalcon/cphalcon#13092] opened 2017-09-26 07:51 UTC
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**

> Provide output if related. Provide coredump if any. Use https://github.com/phalcon/cphalcon/wiki/Generating-a-backtrace as reference

```
Occasionally can't get value from memcache.

For example: 
$this->set('test', 'this is a test');
$this->get('test'); // this is a test
$this->get('test'); // false
$this->get('test'); // this is a test

Sometimes get value
Sometimes cat't get value

thank you

```
> Provide minimal script to reproduce the issue

```php
// paste code
```
### Details

* Phalcon version: 3.1.2
* PHP Version: 7.0
* Operating System: mac os | centos7
* Installation type: installing via package manager
* Zephir version (if any): 
* Server: Nginx 
* Other related info (Database, table schema): mysql5.6

**Comment by gotoin** [comment] 2017-09-26 07:53
php5.6 phalcon2 no problem, this problem arises after the upgrade

**Comment by sergeyklay** [comment] 2017-10-02 22:19
Closing, I can't reproduce this. As you can see the tests passed: #13105. Did you check memcached (for example via telnet) in cases where Phalcon can't receive data? Did you diagnosed a Memcache server with a high cache miss rate? I'm not sure that there is any Phalcon related issue. Please in future issues use a bit more related info e.g. Memcached Server version, used adapter (`Libmemcached`, `Memcache`), PHP extension to work with memcached protocol, etc. And feel free to discuss on the [official forums](https://forum.phalconphp.com), and/or the internals resources.

**Closed by sergeyklay** 2017-10-02 22:19 UTC
