### ISSUE TITLE
Query Builder

### ISSUE THREAD

**Issue by sp3c1** [phalcon/cphalcon#2477] opened 2014-05-27 16:09 UTC
Have a bit of a problem with Query builder from Models Manager

We are creating query for listing, and everything works fine, till we get to the WHERE

```
SELECT 
    u.id AS id, 
    u.email AS email, 
    u.username AS username,
    u.active AS active, 
    u.first_name AS name,
    u.last_name AS surname, 
    ur.name AS role_id 
FROM 
     [Fml\Models\Entities\User] AS [u] JOIN 
     [Fml\Models\Entities\UserRole] AS [ur] ON u.role_id = ur.id 
WHERE  
      u.id = 43 
```
we get the
```
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous
```
But in the same query ORDER BY  u.id works just fine. Am I schizophrenic or is it a bug? ;]

And yes, it was passed as  
```
->where(" u.id = 43 "); 
```
just for test

----

Now we found workaround, but the problem remains. I guess alias that is created in SELECT building take some part in building the WHERE which is  A VERY BAD IDEA imo. 

So when in SELECT 
```
u.id as id
```
Is changed to 
```
u.id as uid
```
It starts to work magically.

Also u.id works now on WHERE and GROUP BY

**Comment by xicond** [comment] 2015-03-12 13:16
yup, it happened to me too, and this solution helped me

**Comment by andresgutierrez** [comment] 2015-08-28 21:45
Closed as not a bug

**Closed by andresgutierrez** 2015-08-28 21:45 UTC
Labels: Not a bug
