### ISSUE TITLE
V4: save() does not work if there are tinyint(1)

### ISSUE THREAD

**Issue by maxttor** [phalcon/cphalcon#14355] opened 2019-09-04 12:06 UTC
There is a mysql table with a tinyint (1) field. 
I'm trying to create a new entry in it through ORM

```php
$item = new Model();
$item->tinyint1 = 0;
$item->save();
```

### Details

* Phalcon version: 4.0.0-beta.2
* PHP Version: 7.2.18-1
* Operating System: ubuntu16.04.1
* Installation type: installing via package manager
* Zephir version (if any):
* Server: Nginx
* Other related info (Database, table schema): MariaDB-10.2.24

**Comment by ruudboon** [comment] 2019-09-04 12:13
Can you share your DB schema?

**Comment by maxttor** [comment] 2019-09-04 12:58
$item->save() return true

DB schema:
```
CREATE TABLE `habit` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `schedule_pack` varchar(255) NOT NULL,
  `duration` smallint(6) unsigned NOT NULL,
  `start_habit_date` date NOT NULL,
  `start_attempt_date` date NOT NULL,
  `end_attempt_date` date NOT NULL,
  `next_mark_date` date NOT NULL,
  `last_mark_date` date DEFAULT NULL,
  `count_fails` smallint(6) unsigned NOT NULL DEFAULT 0,
  `count_completed` smallint(6) unsigned NOT NULL DEFAULT 0,
  `second_chance` tinyint(1) NOT NULL,
  `second_chance_use` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**Comment by ruudboon** [comment] 2019-09-04 13:04
Your're setting a column that isn't part of your schema. Can you try this:
```
$item = new Model();
$item->second_chance = 0;
if (!$item->save()) {
   print_r($item->getMessages()):
}
```

**Comment by maxttor** [comment] 2019-09-04 13:07
```php
$item = new Temp();
$item->test = 0;
if (!$item->save()) {
    exit($item->getMessages());
}
exit('OK');
```

output: 

> OK

**Comment by ruudboon** [comment] 2019-09-04 13:17
@maxttor I tried this locally and I'm unable to reproduce this. A new row is added to the DB with the correct data.
Do you have something going on in your model?

**Comment by maxttor** [comment] 2019-09-04 13:33
@ruudboon, no, nothing. Created just such a test empty model. I’m trying to save. that is all i doing.

**Comment by ruudboon** [comment] 2019-09-04 14:19
And this only occurs with a tinyint(1)?

**Comment by maxttor** [comment] 2019-09-04 14:20
@ruudboon exactly

**Comment by ruudboon** [comment] 2019-09-04 14:23
I'm testing under php 7.3.7 so maybe it's version related. @niden Any other ideas how to reproduce this?

**Comment by ruudboon** [comment] 2019-09-04 17:01
@maxttor Added some unit test but can't reproduce this. Can you double check if you are looking at the correct DB?

**Comment by cottton** [comment] 2019-09-04 19:39
> These were just an example.
> 
> ```sql
> CREATE TABLE `temp` (
>   `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
>   `test` tinyint(1) unsigned DEFAULT NULL,
>   PRIMARY KEY (`id`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
> ```
> 
> ```
> $item = new Temp();
> $item->test = 0;
> if (!$item->save()) {
>     exit($item->getMessages());
> }
> exit('OK');
> ```
> 
> output:
> 
> > OK

Works here on PHP 7.2.19, cPhalcon 3.4.3

    select * from temp;
    +----+------+
    | id | test |
    +----+------+
    |  1 |    0 |
    +----+------+

**Comment by maxttor** [comment] 2019-09-04 20:19
@cottton, try please with cPhalcon  4.0.0-beta.2

**Comment by sergeyklay** [comment] 2019-09-04 22:42
@maxttor Could you test this in MySQL by any chance?

**Comment by ruudboon** [comment] 2019-09-05 05:33
@sergeyklay I tested this with MariaDB

**Comment by maxttor** [comment] 2019-09-05 15:02
Tested everything again. The result is the same. When tinyint(2) - successfully recorded. With tinyint(1) - no.
If the error no longer appears to anyone. Then we can assume that this is a mistake in my environment. For myself, I solved this issue by establishing tinyint (3)

**Comment by cottton** [comment] 2019-09-05 17:36
A query log would be interesting.

    SET global general_log = 1;
    SET global log_output = 'table';
    truncate mysql.general_log;

Run test ...
and look into logged queries 

    select * from mysql.general_log;

---
after tests disable query log (!)
    SET global general_log = 0;
    truncate mysql.general_log;

**Comment by sergeyklay** [comment] 2019-09-05 18:29
I'm closing this issue but if I have made an oversight, please do get back in touch. Thanks

**Closed by sergeyklay** 2019-09-05 18:29 UTC
Labels: 4.0, Bug - Medium, Need script to reproduce

**Comment by maxttor** [comment] 2019-09-06 16:05
I did it.
When the field has type is tinyint(2) the log shows:

> 019-09-06 16:00:15.821581 | dbuser[dbuser] @ localhost [] | 68 | 1 | Prepare | INSERT INTO `temp` (`test`) VALUES (?)
> 2019-09-06 16:00:15.827772 | dbuser[dbuser] @ localhost [] | 68 | 1 | Execute | INSERT INTO `temp` (`test`) VALUES (0)

When the field has type tinyint(1) the log shows:
> 2019-09-06 15:58:56.203857 | dbuser[dbuser] @ localhost [] | 60 | 1 | Prepare | INSERT INTO `temp` (`test`) VALUES (?)
No have Execute query
