### ISSUE TITLE
[BUG] Phalcon\Mvc\Micro\Collection::map returns NULL instead of Phalcon\Mvc\Router\RouteInterface

### ISSUE THREAD

**Issue by jeffreycahyono** [phalcon/cphalcon#1037] opened 2013-08-08 15:35 UTC
```php
$upload = new MicroCollection();
$upload->setHandler('UploadController',true);
$upload->setPrefix('/upload');
$x = $upload->map('/', 'execUpload');

print_r($x); //The output is NULL!!
```

**Comment by Green-Cat** [comment] 2015-04-08 19:51
@phalcon This should probably be closed as not a bug.

**Closed** 2015-04-08 19:51 UTC
Labels: Bug - Medium
