### ISSUE TITLE
It is not possible to install phalcon on MAC environment with PHP 7.0, phalcon/devtools 3.2.0

### ISSUE THREAD

**Issue by ismailatkurt** [phalcon/cphalcon#14287] opened 2019-08-06 11:54 UTC
hi there

I am trying to install phalcon/devtools 3.2.0 on MAC with PHP 7.0. Brew is not supporting it for a while so I dont have that option anymore. Macports is not helping neither. Now there is something else; new homebrew repo under "tigerstrikemedia/homebrew-phalconphp" which again not helping. For god sake can someone please add a phrase saying you cannot use phalcon on mac :)) or someone help me if managed to install it on MAC, PHP 7.0, phalcon/devtools 3.2.0 tell me if I am missing something.
"not helping": meaning they install some other specific versions, or they fail at all.

Building from binary already fails.

**Comment by AlexNDRmac** [comment] 2019-08-06 20:11
Hi @ismailatkurt, I'll try to write instruction with detailed installation steps. But I need some time for this. Can you wait for this guide?

**Comment by CameronHall** [comment] 2019-08-07 02:06
@ismailatkurt while @AlexNDRmac is writing a guide I suggest you use something like [Devilbox](http://devilbox.org/) it's a pre-configured docker environment which has Phalcon pre-installed. It also saves you bloating your host with all the dependencies. If you decide to use it and have any issues, ping me on Discord.

**Comment by ismailatkurt** [comment] 2019-08-07 08:15
hey, thanks for your support! I will check Devilbox meanwhile. We (company, I work for) are using Phalcon in 2 of our projects and these 2 projects have heavy load traffic. So we can wait for the guide since it is crucial for us but not crazy urgent. I believe we will have no problem if we would upgrade php version on our servers but that's not up to me. Anyway thanks for fast responses!

**Comment by sergeyklay** [comment] 2019-08-07 19:18
Let me a try:

Is it works for you (?):

```shell
# Install Zephir Parser

$ cd /tmp
$ git clone https://github.com/phalcon/php-zephir-parser.git
$ cd php-zephir-parser
$ git checkout development # optional
$ phpize
$ ./configure
$ make

# Install Zephir

$ cd /tmp
$ git clone https://github.com/phalcon/zephir.git
$ cd zephir
$ git checkout development # optional
$ composer install

# Install Phalcon

$ cd /tmp
$ git clone https://github.com/phalcon/cphalcon.git
$ cd cphalcon
$ git checkout 3.4.x # optional
$ php -d extension=/tmp/php-zephir-parser/modules/zephir_parser.so /tmp/zephir/zephir fullclean
$ php -d extension=/tmp/php-zephir-parser/modules/zephir_parser.so /tmp/zephir/zephir generate
$ cd build
$ php gen-build.php
```

**Comment by AlexNDRmac** [comment] 2019-08-12 12:05
# Pre-checks

First, check if you already have Zephir Parser extension
```bash
$ php -m | grep Zephir
$ Zephir Parser
```

Install Required tools to build Zephir parser from sources:
Mac OSX already have `make` and `gcc`, so we should install only `re2c`, `autoconf`, `automake` with Brew
```bash
$ brew install re2c autoconf automake
```

Lets test it into separate directory, for example: ~/phalcon_32x, create this dir or use another path.

## Install Zephir Parser, if you don't have it
```bash
$ cd ~/phalcon_32x
$ git clone https://github.com/phalcon/php-zephir-parser.git
$ cd ./php-zephir-parser
$ phpize
$ ./configure
$ make
```

And, you need to have Zephir, just download PHAR
```
$ cd ~/phalcon_32x
$ curl -OL https://github.com/phalcon/zephir/releases/download/0.12.2/zephir.phar
$ cmod +x ./zephir.phar

## Lets Install Phalcon 3.2.x or any other...
$ cd ~/phalcon_32x
$ git clone https://github.com/phalcon/cphalcon.git
$ cd ./cphalcon
$ git checkout 3.2.x
$ php -d extension=~/phalcon_32x/php-zephir-parser/modules/zephir_parser.so ~/phalcon_32x/zephir.phar fullclean
$ php -d extension=~/phalcon_32x/php-zephir-parser/modules/zephir_parser.so ~/phalcon_32x/zephir.phar generate
$ cd ./build
$ php ./gen-build.php
$ sudo ./install

After these steps you'll have compilied extension, check next path:
```bash
$ ~/phalcon_32x/phalcon/cphalcon/build/php7/64bits/modules/phalcon.la
$ ~/phalcon_32x/phalcon/cphalcon/build/php7/64bits/modules/phalcon.so
```

@ismailatkurt - try please... This instruction tested on Mac OS X 10.14.5

**Comment by ruudboon** [comment] 2019-08-19 05:03
@ismailatkurt did the comments above helped you out?

**Comment by Fenikkusu** [comment] 2019-08-29 02:18
Just my two cents: I pretty much exclusively use docker for development on all my macs, both home and work. I've docker image on the hub called twistersfury/phalcon and another called twistersfury/zephir:phalcon that are both made to work with phalcon. For items like running the devtools, I use a Makefile that allows me easy access to running them using a simple `make tool-name` that automatically builds the appropriate docker command for me.

**Comment by sergeyklay** [comment] 2019-08-29 20:21
I'm closing this since this is a not a bug report and due to the lack of any activity. I'll open it again if the need arises. But if I have made an oversight, please do get back in touch. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com). Thanks.

**Closed by sergeyklay** 2019-08-29 20:21 UTC
Labels: Not a bug
