### ISSUE TITLE
¿how set model instance on controller contructor?

### ISSUE THREAD

**Issue by incubux** [phalcon/cphalcon#12863] opened 2017-05-26 20:02 UTC
class IndexController extends \Phalcon\Mvc\Controller
{

    public $m_index;
    public function onConstruct()
    {
        $this->$m_index = new M_index;
    }
    
    public function indexAction()
    {
        $this->view->render("", "login");
    }
    
        public function consultaAction()
    {
        $this->$m_index->m_consulta();
    }
}

show this message:
Notice: Undefined variable: m_index in C:\xampp\htdocs\phalconOne\app\controllers\IndexController.php on line 9

Notice: Undefined variable: m_index in C:\xampp\htdocs\phalconOne\app\controllers\IndexController.php on line 19

Please help

**Comment by Ultimater** [comment] 2017-05-26 20:03
`$this->$m_index` != `$this->m_index`

**Comment by Jurigag** [comment] 2017-05-26 20:04
Use forum for questions. @sergeyklay close it

**Comment by incubux** [comment] 2017-05-26 20:04
correction:
$this->$m_index = new M_index();
show same error

**Comment by incubux** [comment] 2017-05-26 20:06
Every step that I give as insignificant as it is, I delay until one day in solving it, it is a very sturdy framework, but it is difficult to get it going.

**Comment by Jurigag** [comment] 2017-05-26 20:07
But the problem is not framework, the problem is that you don't even use basic php standards, first learn php, then start using framework

http://www.phptherightway.com
http://php.net/manual/en/

**Comment by incubux** [comment] 2017-05-26 20:09
In php always instantiates models from the constructor, even in other frameworks, but phalcon does not allow it

**Comment by Jurigag** [comment] 2017-05-26 20:11
Phalcon allow it too, the problem is you don't even know what this error mean and what's your problem, just toally forgot about framework for now, go to basics, php doc and phptherightway, read it, and go to some basic code, like defining variables, creating your own classes etc without any framework.

**Comment by david-duncan** [comment] 2017-05-26 20:11
@incubux your problem is bad php syntax, not the framework. You are using a variable variable..

**Comment by incubux** [comment] 2017-05-26 20:22
¿how set model instance on controller contructor?

**Comment by incubux** [comment] 2017-05-26 20:30
I will look for another framework, as I see, forums and tutorials are more than 2 years and many questions just like stupid to mine, maybe because of that the community activity in this framework is smaller compared to other frameworks, I think You have to be an incredibly intelligent being like Jurigag to use phalcon, there are few privileged ones, thanks for your time and sorry for the inconvenience, bye.

**Comment by Jurigag** [comment] 2017-05-26 20:34
You know you will do same mistake in other framework, right?

**Comment by niden** [comment] 2017-05-26 20:37
@incubux change your code like this:

```
class IndexController extends \Phalcon\Mvc\Controller
{
    public $m_index;
    public function onConstruct()
    {
        $this->m_index = new M_index();
    }
    
    public function indexAction()
    {
        $this->view->render("", "login");
    }
    
        public function consultaAction()
    {
        $this->m_index->m_consulta();
    }
}
```

**Comment by Jurigag** [comment] 2017-05-26 20:39
If you would ask this question on stackoverflow or forum i would really answer it, but i guess on stack it would get like -10 points instantly.

**Closed** 2017-05-26 20:44 UTC
