### ISSUE TITLE
better volt support for javascript files

### ISSUE THREAD

**Issue by tyurderi** [phalcon/cphalcon#11169] opened 2015-11-29 16:37 UTC
I throw my javascript files through the volt template engine and I would glad to see that I can comment out the volt commands by // or /**/ so that my IDE doesn't count the volt expressions as errors.

Currently volt throws errors, instead of just accept these "comment out"-chars.

If neccessary, currently I am using Phalcon 2.0.7.

**Comment by sergeyklay** [comment] 2017-06-25 12:23
Volt already has commenting. I'm closing since this is a not a bug report. Feel free to discuss on the [official forums](https://forum.phalconphp.com), and/or the internals repo.

**Closed by sergeyklay** 2017-06-25 12:23 UTC
