### ISSUE TITLE
session use redis Adapter can't to destroy the data in php7

### ISSUE THREAD

**Issue by bain2018** [phalcon/cphalcon#12326] opened 2016-10-16 11:03 UTC
when i use the redis as the session Adapter;
i can't  destroy all of the session data
phalcon 3.0.1
php 7

**Comment by lujunjie521** [comment] 2016-11-04 07:10
did u finish this bug?

**Comment by Yurist-85** [comment] 2016-11-24 10:50
This is a **BUG**.
Faced with such problem on Phalcon v2 + PHP 5.6.
Look in source code. Incorrect behaviour of this Adapter is from the beginning.
Just compare original Adapter and Redis Adapter. 
No need in any row of script "to reproduce" it. It simply works **wrong**.

**Comment by Jurigag** [comment] 2016-11-24 10:52
What you mean no script to reproduce ? Then how to recreate this issue without any code ?

**Comment by Yurist-85** [comment] 2016-11-24 11:01
There's no need to recreate it. Look in source code. If your brain works fine I'll see that there're absolutely different behaviours of `->destroy()` methods in original Adapter and Redis Adapter.

**Comment by sergeyklay** [comment] 2016-12-24 12:13
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Comment by gamalan** [comment] 2017-05-01 01:44
I also happen to facing this, i think this is because the implementation of destroy between Adapter and RedisAdapter when destroying is totally different.
in adapter.zep
`public function destroy(boolean removeData = false) -> boolean`
but in redis.zep
`public function destroy(string sessionId = null) -> boolean`
and yet in the php stub,
`public function destroy($removeData = false)`
Can you tell what kind of script you need to reproduce? I'd like to help to help if possible.
The only way to destroy the session is by remove one by one, or using session_destroy. Which is problematic i think.

**Comment by gamalan** [comment] 2017-05-01 01:48
also, in both adapter.zep and libmemcached.zep, this is implemented in destroy function.

```
for key, _ in _SESSION {
			unset _SESSION[key];
}
```

yet in memcache.zep and redis.zep, this is not implemented.

**Comment by sergeyklay** [comment] 2017-05-01 21:08
@gamalan I'll try to sort out asap

**Comment by sergeyklay** [comment] 2017-05-02 07:46
@gamalan https://github.com/phalcon/cphalcon/issues/12833

**Comment by sergeyklay** [comment] 2017-06-01 14:46
[Fixed](https://github.com/phalcon/cphalcon/pull/12838) in the `3.2.x` branch. Feel free to open new issue if the problem appears again. Thank you for contributing.

**Closed by sergeyklay** 2017-06-01 14:46 UTC
Labels: Bug - Low
