### ISSUE TITLE
php7.1.0 not support

### ISSUE THREAD

**Issue by kangtao10000** [phalcon/cphalcon#12461] opened 2016-12-08 12:03 UTC
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**

> Provide output if related. Provide coredump if any. Use https://github.com/phalcon/cphalcon/wiki/Generating-a-backtrace as reference

```php
// paste output here
```
> Provide minimal script to reproduce the issue

```php
// paste code
```
### Details

* Phalcon version: (`php --ri phalcon`)
* PHP Version: (`php -v`)
* Operating System:
* Installation type: Compiling from source || installing via package manager
* Zephir version (if any):
* Server: Nginx | Apache | Other
* Other related info (Database, table schema):

**Comment by Jurigag** [comment] 2016-12-08 12:08
Duplicate of #12055

**Comment by kangtao10000** [comment] 2016-12-08 12:14
php7.1.0  cphalcon3.0.2  Error info: Segmentation fault

**Comment by Jurigag** [comment] 2016-12-08 12:20
AS I WROTE - duplicae of #12055

**Closed** 2016-12-08 13:58 UTC
Labels: Duplicate
