### ISSUE TITLE
NFR: BindParam Array 'Phalcon\Db' 

### ISSUE THREAD

**Issue by xerron** [phalcon/cphalcon#12225] opened 2016-09-16 10:36 UTC
Can I bind an array to an IN() condition?

**now:**

http://stackoverflow.com/questions/920353/can-i-bind-an-array-to-an-in-condition
https://forum.phalconphp.com/discussion/125/select-where-id-in-1-2-3-

``` php
$userModel->getReadConnection()->query('UPDATE users SET last_online = :online WHERE id IN :ids', [
    'online' => time(),
    'ids'    => '(' .  implode(', ', $ids) . ')'
])->execute();
```

or

``` php
$sql = strtr("UPDATE `users` SET `last_online` = ':online' WHERE `id` IN (':ids')", [
    ':online' => $lastOnline,
    ':ids'    => implode("', '", $ids)
]);

$userModel->getReadConnection()->query($sql)->execute();
```

**but this is better:**

``` php
$names = ['user.role.administrator', 'user.role.anonymous', 'user.role.authenticated'];

$result = $connection->query(
    'SELECT name, data FROM config WHERE collection = :collection AND name IN ( :names[] )',
     [
            'collection' => '',
            'names[]' => $names
     ]
);
```

This can be done by converting the query string:

from:

``` sql
SELECT name, data FROM config WHERE collection = :collection AND name IN ( :names[] )
```

to:

``` sql
SELECT name, data FROM config WHERE collection = :collection AND name IN ( :names__0, :names__1, :names__2 )
```

and BindParams:

from:

``` php
[
       'collection' => '',
       'names[]' => $names
]
```

to:

``` php
[
    'collection' => "",
    'names__0' =>  "user.role.administrator",
    'names__1' =>  "user.role.anonymous",
    'names__2' => "user.role.authenticated"
]
```

This function makes magic:

``` php
function expandArguments(&$query, &$args)
{
    $modified = false;

    // If the placeholder indicated the value to use is an array,  we need to
    // expand it out into a comma-delimited set of placeholders.
    foreach ($args as $key => $data) {
        $is_bracket_placeholder = substr($key, -2) === '[]';
        $is_array_data = is_array($data);
        if ($is_bracket_placeholder && !$is_array_data) {
            throw new \InvalidArgumentException('Placeholders with a trailing [] can only be expanded with an array of values.');
        } elseif (!$is_bracket_placeholder) {
            if ($is_array_data) {
                throw new \InvalidArgumentException('Placeholders must have a trailing [] if they are to be expanded with an array of values.');
            }
            // Scalar placeholder - does not need to be expanded.
            continue;
        }
        // Handle expansion of arrays.
        $key_name = str_replace('[]', '__', $key);
        $new_keys = array();
        // We require placeholders to have trailing brackets if the developer
        // intends them to be expanded to an array to make the intent explicit.
        foreach (array_values($data) as $i => $value) {
            // This assumes that there are no other placeholders that use the same
            // name.  For example, if the array placeholder is defined as :example[]
            // and there is already an :example_2 placeholder, this will generate
            // a duplicate key.  We do not account for that as the calling code
            // is already broken if that happens.
            $new_keys[$key_name . $i] = $value;
        }

        // Update the query with the new placeholders.
        $query = str_replace($key, implode(', :', array_keys($new_keys)), $query);

        // Update the args array with the new placeholders.
        unset($args[$key]);
        $args += $new_keys;

        $modified = true;
    }

    return $modified;
}
```

**Comment by Jurigag** [comment] 2016-09-16 10:40
If you want to add this then do PR with this.

**Comment by xerron** [comment] 2016-09-16 10:50
First I want to have feedback

**Comment by Jurigag** [comment] 2016-09-16 10:52
Find with me i guess, but keep in mind that Phalcon\Db is just wrapper on PDO. If pdo doesn't have things like this, then im not sure if we should add it in Phalcon\Db neither. What's a problem with PHQL ? I know that phql just first fetch all those results and then it's firing all events etc stuff. 

Better just would be to make PHQL possible to do queries like this, without fetching all models, events etc. Like some flag in update or something.

**Comment by xerron** [comment] 2016-09-16 14:57
You mean the model manager, it sounds good. But the trouble is that it can not change the connection to a custom.

``` php
// 'SELECT Robots.* FROM Robots WHERE id NOT IN (1, 2, 3)';
$builder->from("Robots")
        ->notInWhere("id", [1, 2, 3]);
```

**Comment by xerron** [comment] 2016-09-16 15:03
https://docs.phalconphp.com/en/latest/api/Phalcon_Mvc_Model_Manager.html
Yes you can:
```php
public setConnectionService (Phalcon\Mvc\ModelInterface $model, mixed $connectionService)
```
But what worries me, this is good when models are used, and for those occasions you have only one connection ?, I think this feature 'names []' is useful and will implement.

**Comment by Jurigag** [comment] 2016-09-16 15:06
No im not meaning notInWhere. I mean this:

```php
$builder->from("Robots")
->where('id NOT IN ({ids:array})', ['ids' => $ids);
```

You can have other connection for read and other for write. No problem here.

**Comment by xerron** [comment] 2016-09-16 15:27
As I say it's good when you use models.
But if you have only conneccion, it would be good to have BindParam array.

``` sql
SELECT name, data FROM config WHERE collection = :collection AND name IN ( :names[] )
```

very clean.

**Comment by Jurigag** [comment] 2016-09-16 15:29
So why not use models then ?

**Comment by xerron** [comment] 2016-09-16 15:32
because I do not need, when I need if I use it.

**Comment by Jurigag** [comment] 2016-09-16 15:33
For me it looks like you need it, then you can just bind array :)

**Comment by xerron** [comment] 2016-09-16 16:41
only need  expandArguments function in Zephir :+1:

**Comment by Jurigag** [comment] 2016-09-16 17:00
Just add it directly to db adapter if we use syntax which you propose it will be done out of box.

**Comment by xerron** [comment] 2016-09-21 00:08
I dont know zephir.
I took a whole day to learn, and I need to be able to contribute much good code. try to pass the function but does not compile me.

**Comment by Jurigag** [comment] 2016-09-21 05:06
Just check some code on repository and that's it. It's very easy and similar to php, just no `$` and to set variable value use let keyword and it's basically it.

**Comment by dschissler** [comment] 2016-11-19 03:49
I believe that Phalcon already has this functionality with a different syntax but it is currently broken in version 3.  This bug is probably a dupe of #11605

**Comment by dschissler** [comment] 2016-11-19 03:52
I'm looking into fixing this myself but I can't identify where the code is being done in Zephir.  I don't know if this portion of Phalcon is implemented in C or not.

**Comment by dschissler** [comment] 2016-11-19 08:50
@sergeyklay @xerron Can we close this?  This functionality already exists using `IN ({variable:array}) syntax.

**Comment by Jurigag** [comment] 2016-11-19 09:28
But he wants this functionallity not in PHQL.

**Comment by sergeyklay** [comment] 2017-02-03 20:58
This works for now in PHQL. For parsing, binding raw SQL you have to extend PDO.

**Closed by sergeyklay** 2017-02-03 20:58 UTC
Labels: New Feature Request
