### ISSUE TITLE
[BUG]: Phalcon\Config\Adapter\Ini parse error 

### ISSUE THREAD

**Issue by zuozhehao** [phalcon/cphalcon#14501] opened 2019-10-31 10:14 UTC
```php
[test]
a  = 01
b  = '01'
c  = "01"
```
output:

```php
Array
(
    [a] => 1
    [b] => '01'
    [c] => 1
)

```
phalcon 3.4.x 
php7.3.4

**Comment by zsilbi** [comment] 2019-10-31 16:23
The parser uses the native `parse_ini_file()` function.
`INI_SCANNER_RAW` is the default mode, which produces the result you got.

https://github.com/phalcon/cphalcon/blob/3c5b00053f29bae16d6c7265cff4b4324cc3a6f3/phalcon/config/adapter/ini.zep#L78-L83

You can change this to `INI_SCANNER_NORMAL` in the constructor of the config adapter.

For example:
```php
new \Phalcn\Config\Adapter\Ini(
   '/my/config.ini',
   INI_SCANNER_NORMAL
);
```

**Comment by ruudboon** [comment] 2019-10-31 17:57
Thnx @zsilbi. @zuozhehao can you confirm this and close the issue if this works for you?

**Comment by zuozhehao** [comment] 2019-11-01 00:27
@ruudboon 
I tried to add `INI_SCANNER_RAW `, but the result was the same

**Comment by sergeyklay** [comment] 2019-11-01 09:33
@zuozhehao What result do you expect?

**Comment by zsilbi** [comment] 2019-11-02 18:52
The built-in `cast()` function makes integers from your numeric strings. 
This is a feature, not a bug.

You can use your own adapter and disable this function like this:
```php
<?php
namespace My\Config\Adapter;

class Ini extends \Phalcon\Config\Adapter\Ini 
{
   
   /**
    * @param mixed $ini
    */
   protected function cast($ini) 
   {
      // Disable casting for numeric strings
      if (typeof $ini === "string" && is_numeric($ini)) {
         return $ini;
      }

      return parent::cast($ini);
   }
}
```

**Comment by zuozhehao** [comment] 2019-11-04 00:42
I don't think it can be forced to change to int type here
https://github.com/phalcon/cphalcon/blob/master/phalcon/Config/Adapter/Ini.zep#L146

**Comment by niden** [comment] 2019-11-18 02:15
@zuozhehao The problem is what to you do with the `is_numeric`. It will return `true` even if the actual value is a numeric string. The `cast` method that @zsilbi posted here https://github.com/phalcon/cphalcon/issues/14501#issuecomment-549070880 can be used to change the behavior if you need it to.

I am going to close this because this is intended behavior.

**Closed by niden** 2019-11-18 02:15 UTC
Labels: 4.0, Bug - Unverified
