### ISSUE TITLE
[BUG]: volt upper filter does not work on special local characters

### ISSUE THREAD

**Issue by kowach** [phalcon/cphalcon#16543] opened 2024-03-12 12:34 UTC
After upgrading from Phalcon 4 to Phalcon 5.5 upper filter in volt does not work on utf8 characters.

1. In volt template file:
```html 
{{ 'abc čžé'|upper }}
```
Results `ABC čžé` (only english letters are changed)

2. Doing the same thing in PHP:
```php
echo (new \Phalcon\Filter\Sanitize\Upper())->__invoke('abc čžé');
```
Outputs is OK `ABC ČŽÉ`

The function is pretty simple [Upper.zep](https://github.com/phalcon/cphalcon/blob/master/phalcon/Filter/Sanitize/Upper.zep)
This could only happen if  function_exists("mb_convert_case") returns false, but I don't see how.

**Details**
 - Phalcon version: 5.5
 - PHP Version: 8.1.27
 - Operating System: Ubuntu/RockyLinux
 - Installation type: Compiling from source
 - Zephir version: 0.17.0-9f99da6
 - Server: Nginx

**Comment by s-ohnishi** [comment] 2024-03-12 15:52
Volt's compiler seems to directly rewrite `{{ 'abc čžé'|upper }}` to `strtoupper()` instead of using `Phalcon\Filter\Sanitize\Upper()`.
[Compiler.zep](https://github.com/phalcon/cphalcon/blob/master/phalcon/Mvc/View/Engine/Volt/Compiler.zep#L2571)

It seems that v4 calls `Phalcon\Text::upper()`.
[Compiler.zep(v4.1.0)](https://github.com/phalcon/cphalcon/blob/4.1.x/phalcon/Mvc/View/Engine/Volt/Compiler.zep#L2483)

I'm not sure which is preferable.
Just as Tag has been migrated to TagFactory, this is also in the middle of migration, so I'm not sure if it's temporary or not.
And which is generally expected when you want to change to uppercase? `ABC čžé` or `ABC ČŽÉ`?

**Comment by niden** [comment] 2024-03-12 16:48
The `Text` component was removed in favor of the helper/tag factories.

You can achieve what you want by doing this:

```twig
{{ helper.upper('abc čžé') }}
```

I know this might not be ideal because you might have similar code all around the place, but this is the way to get the UTF-8 functions to help you there (vs. the `strtoupper()`)

This assumes you have the mbstring extension loaded and in your container you have a service called `helper` which points to the `Phalcon\Support\HelperFactory`. If you are using the `FactoryDefault` container it is already in there.

**Comment by s-ohnishi** [comment] 2024-03-13 15:55
So this is not a bug and we can now choose according to our needs, right?

**Comment by niden** [comment] 2024-03-13 16:01
Actually it is a bug, since it changes the behavior from v4 to v5. What I posted above is a workaround.

I will make the necessary adjustments for this and have it use the `helper` if available and fall back to `strtoupper` if not

**Comment by niden** [comment] 2024-03-13 18:31
This has been resolved with https://github.com/phalcon/cphalcon/pull/16545

Thank you @kowach and @s-ohnishi

**Closed by niden** 2024-03-13 18:31 UTC
Labels: bug, status: medium, 5.0
