### ISSUE TITLE
[2.0.4] Url Generation Now Breaks Relative Redirects 

### ISSUE THREAD

**Issue by virgofx** [phalcon/cphalcon#10610] opened 2015-07-07 19:56 UTC
Redirection using relative paths no longer works in 2.0.4. The Url detection now seems to think relative paths are external and it is adding http which breaks redirection.

```php
$this->response->redirect('/my-local-path');
```
Will return a 301 with `http://my-local-path` which is incorrect.  Should be `/my-local-path`.

**Comment by andresgutierrez** [comment] 2015-07-08 01:09
I'm not able to reproduce this:

```php
<?php

use Phalcon\Di;
use Phalcon\Mvc\Url;
use Phalcon\Http\Response;

$di = new Di;

$di['url'] = function() {
    $url = new Url;
    $url->setBaseUri('http://localhost/invo');
    return $url;
};

$http = new Response;
$http->redirect('/data');
$http->send();
```

Produces the correct redirection to http://localhost/invo/data

**Comment by alitalaghat** [comment] 2015-07-09 10:34
Please try with this:
```$url->setBaseUri('/');```
Now you can reproduce the problem.

**Comment by andresgutierrez** [comment] 2015-07-09 12:22
@alitalaghat But the generated URLs are //data which in fact are relative URLs

**Comment by virgofx** [comment] 2015-07-09 13:33
@andresgutierrez   nope ... "//" is interpreted as a schemaless root url.

**Comment by virgofx** [comment] 2015-07-09 13:33
Thats the problem exactly, the default base uri is "/" (which is the case when it's not set) and therefore redirects will now use "//data" which is incorrect  --> as this will redirect to "http://data" or https://data" depending on the scheme.

**Comment by virgofx** [comment] 2015-07-09 13:35
I __believe__ you may be able to reproduce problem if you add an extra '/' on your example (although not tested). The original documentation had the base uri always ending with a trailing slash.

**Comment by virgofx** [comment] 2015-07-11 17:53
I can confirm this problem exists in all applications without explicitly specifying a baseUri for the URL. The default has been always "/". And now any redirect's with `/location` will turn into '//location` which is incorrect.

This is extremely high priority.

**Comment by andresgutierrez** [comment] 2015-07-12 13:41
If the default URI is / why do you have to prepend another /? It will result, for instance in `//data`.

**Comment by virgofx** [comment] 2015-07-12 18:43
@andresgutierrez  Intuitively that would make sense ... no problem with that. The issue is that the behavior has changed from defaults prior to 2.0.4 in a very core part of the framework (URL generation is huge for applications -- breaking production for my entire stacks)

The current default has always been "/" for the base URI. I guess more clarification could exist on this. For example, lets talk about applications that are serving single instances only (e.g. www.mydomain.com). They are running phalcon but want all URLs to be relative. Relative because the url is accessed via https://www.mydomain.com, www.mydomain.com, ip-10.10.10.10:80.

So is 2.0.4 intended to change default behavior? The URL commit has broken functionality, applications in production, additionally the Invo application.

Is the new URL change intended to no longer use a trailing slash? The current pre-2.0.4 default was `/`. Invo was `/invo/` ... other applications always included a trailing slash, yet responses and urls were always started with a slash ... e.g. `/redirect-locally`.

So either way .. there needs to exist through documentation on for base URI / base URL / static URLs and explicitly with slashes.

Alternatively, a quick fix would be to assume that base URIs always end in a trailing slash and handle the case where you have a leading slash plus trailing slash.

Or just revert the last URL commit as this breaks functionality.

**Comment by olivier-monaco** [comment] 2015-07-15 20:34
Change was https://github.com/phalcon/cphalcon/commit/1f74b2614524eee918f9e94b74fe712500209a03#diff-d20931d7bcb77f0986c66ce50e774c7eL230

@andresgutierrez Do you remember why you change the behavior? What was the problem?

**Comment by andresgutierrez** [comment] 2015-07-15 20:39
@olivier-monaco Not sure why it was initially there: https://github.com/phalcon/cphalcon/commit/c73502ea827c473003934b71a7ad13f904d1d86d

**Comment by olivier-monaco** [comment] 2015-07-15 20:46
It was to handle this kind of issue (see #3222).

**Comment by olivier-monaco** [comment] 2015-07-15 21:09
index.php
<pre>
<?php

use Phalcon\Mvc\View;
use Phalcon\Mvc\Application;
use Phalcon\DI\FactoryDefault;

try {
    $di = new FactoryDefault();

    $di->set('view', function(){
        $view = new View();
        $view->setViewsDir('../app/views/');
        return $view;
    });

	$router = new Phalcon\Mvc\Router(true);
	$di->set('router', $router, true);

    $application = new Application($di);
    echo $application->handle()->getContent();

}
catch (\Exception $e) {
     echo "PhalconException: ", $e->getMessage();
}
</pre>

.htaccess
<pre>
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ index.php?_url=/$1 [QSA,L]
</IfModule>
</pre>

**Comment by andresgutierrez** [comment] 2015-07-15 21:10
@olivier-monaco I can't see any URL generation in your test

**Comment by olivier-monaco** [comment] 2015-07-15 21:15
@andresgutierrez wrong issue...sorry...

**Comment by olivier-monaco** [comment] 2015-07-15 22:16
```php
$u = new \Phalcon\Mvc\Url();
$s = $u->get('/path').PHP_EOL;
```

@andresgutierrez What must be the value of $s?

**Comment by andresgutierrez** [comment] 2015-07-15 22:16
@olivier-monaco it must be baseUri + uri

**Comment by olivier-monaco** [comment] 2015-07-15 22:17
So, in this case, "//path". It's not what I may expected and I think many developers too.

**Comment by andresgutierrez** [comment] 2015-07-15 22:18
@olivier-monaco If you didn't expect //path why did you pass '/path' instead of just 'path'?

**Comment by olivier-monaco** [comment] 2015-07-15 22:26
Because I'm expected the baseURI to be "root" of the web site, so to be empty. Maybe the default must be the empty string.

When I see this code:
```php
$this->response->redirect($url);
```

I'm expecting:
1) $url to contains a full URL to redirect to (http://....). It's an external absolute URL
2) $url to begin with "/" ("/path"). It's an internal absolute URL.
3) $url to not begin with "/" ("path"). It's a relative URL to the current URL.

For the thrid case, if the current URL is "/some/place", asking for "path" must be "/some/place/path".

Them, the baseURI is like a "chroot", a way to force some path at the beginning of any path.

Here is what I have in mind.

**Comment by andresgutierrez** [comment] 2015-07-15 22:45
But not all URLs that begin with / are absolute URLs, you also have protocol-relative URLs: http://tools.ietf.org/html/rfc3986#section-4.2

**Comment by olivier-monaco** [comment] 2015-07-15 22:53
Yes, we can add something between 1 and 2 called "external relative URL".

**Comment by fonshua** [comment] 2015-07-17 04:56
I also can confirm that this issue is reproducible:

$this->response->redirect("/my/profile"); will be interpreted as http://my/profile

**Comment by Surt** [comment] 2015-07-17 09:18
```php
        $this->response->redirect("/")
``` 

it's not working when not setting any ```setBaseUri```

**Comment by andresgutierrez** [comment] 2015-07-20 22:18
Fixed in the 2.0.x branch

**Closed by andresgutierrez** 2015-07-20 22:18 UTC

**Comment by virgofx** [comment] 2015-07-21 02:49
@andresgutierrez Thank you very much!

**Comment by dschissler** [comment] 2015-07-21 09:54
@andresgutierrez Perhaps you could keep a list of things to break in 3.0.

**Comment by sszdh** [comment] 2015-07-25 12:11
But now it conflict with logic that based on `request->getURI()`!
The `request->getURI()` returns `_SERVER["REQUEST_URI"]` that begins with extra `/`:

Consider this example when you want redirect user to requested URI after login:
```php
$this->response->redirect($this->request->getURI()); <-- result: redirect('/user/profile')
``` 
This issue completely breaks my app!

Should I trim each `gitURI()` in my code? :|

Thanks.

**Comment by olivier-monaco** [comment] 2015-07-25 12:31
@sszdh Can you give us an minimal usecase?

**Comment by sszdh** [comment] 2015-07-25 16:02
@olivier-monaco I did before!
Actually using getURI returns RUI with slash and you can not use this directly with `redirect()`.
This is not about any use-case,  the `getURI` returns `_SERVER["REQUEST_URI"]` depends on [this](https://github.com/phalcon/cphalcon/blob/master/phalcon/http/request.zep#L439)

It means I can not use `getURI` directly in routing and redirecting...

Thanks

**Comment by olivier-monaco** [comment] 2015-07-25 17:08
@sszdh A use-case is a way for us to understand what you want exactly. It's also a way to have/build a unit test and to ensure the code to do what your want. Reading your comment is not enough: I don't see your problem...

But maybe someone else fully understand your problem and will help you.

**Comment by olivier-monaco** [comment] 2015-07-25 20:11
@sszdh Are you using the latest version?

I added a controller for "/toto" with the following code:
```php
$this->response->redirect($this->request->getURI());
```

And when I open the URL, I get:
```
  HTTP/1.1 302 Found
  ...
  Location: /toto
  Vary: User-Agent,Accept-Encoding
```

What is wrong with this result?

**Comment by sszdh** [comment] 2015-07-25 20:46
The wrong with this result is the `getURI()` value does not suitable for redirction anymore but in last version it did.

I'm in travel now, i will provide a test script ASAP @olivier

Thanks for your attention
