### ISSUE TITLE
Question about suspicious code

### ISSUE THREAD

**Issue by kov-serg** [phalcon/cphalcon#13472] opened 2018-08-28 00:23 UTC
### Expected and Actual Behavior
See no "Fatal error: Access to undeclared static property: Phalcon\Di::$_default" under high load.

### Code to reproduce

    <?php \Phalcon\Di::reset();

### Question
Why in source of phalcon https://raw.githubusercontent.com/phalcon/cphalcon/master/build/php5/64bits/phalcon.zep.c

in line 7225:

    if (UNEXPECTED(zend_hash_quick_find(&ce->properties_info, property_name, property_name_len + 1, hash_value, (void **) &temp_property_info)==FAILURE)) {

used &ce->properties_info instead of CE_STATIC_MEMBERS(ce) ?
And why

    zend_update_class_constants(ce TSRMLS_CC);

placed after this line. Should it paced before line with zend_hash_quick_find?

Can any one explain this code?

* Phalcon version: 2.0.8(no problem) -> 2.0.10+(bug)
* PHP Version: 5.3.29(no problem) -> 5.4.45+(bug)
* Operating System: any
* Installation type: any
* Server: Apache

**Comment by Jurigag** [comment] 2018-09-07 00:12
As far as i know this issue happens on TS php.

**Comment by kov-serg** [comment] 2018-09-07 10:59
i have this issue on jino.ru hosting. If i set 2.0.8+PHP5.3 - it works, 2.0.10+PHP5.4..5.6 - stable bug.
The only difference in source code in this place.

**Comment by kov-serg** [comment] 2018-09-07 11:00
And there used NTS versions of PHP

**Comment by Jeckerson** [comment] 2018-09-07 14:18
What OS?

**Comment by kov-serg** [comment] 2018-09-12 15:41
$ cat /etc/centos-release
CentOS Linux release 7.5.1804 (Core) 
$ uname -a
Linux srv66-h-st.jino.ru 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$cat /proc/cpuinfo|grep name|head -1
model name	: Intel(R) Xeon(R) CPU           X3470  @ 2.93GHz

**Comment by Jurigag** [comment] 2018-09-18 16:47
@kov-serg this C code is generated by zephir if you think we should change it or do anything else write here please - https://github.com/phalcon/zephir or feel free to create PR about this if you know hot to fix it. I will close this issue because there is already one similar existing https://github.com/phalcon/cphalcon/issues/12056 but about C code we should discuss it in zephir repository what is generated and fix it if there is something wrong

**Closed by Jurigag** 2018-09-18 16:47 UTC

**Comment by hakimio** [comment] 2018-10-04 09:33
@kov-serg
Have you tried to compile zephir with your changes to [object.c#L1275@zephir](https://github.com/phalcon/zephir/blob/ce5397755642ba3dfc7df6e72a5cedba5749b329/kernels/ZendEngine2/object.c#L1275) ? Does it fix the "Access to undeclared static property" error?

**Comment by hakimio** [comment] 2018-10-04 09:37
@sjinks Do you know the reason for the suspicious code?

**Comment by kov-serg** [comment] 2018-10-08 12:40
Because of this:
http://php53.sewandenjoy.com/bug.php - works
http://php54.sewandenjoy.com/bug.php - problem
http://php55.sewandenjoy.com/bug.php - problem
http://php56.sewandenjoy.com/bug.php - problem

I found only difference in source code of phalcon.
https://raw.githubusercontent.com/phalcon/cphalcon/phalcon-v2.0.8/build/64bits/phalcon.zep.c
near line: "static zval **zephir_std_get_static_property("

    #if PHP_VERSION_ID < 50400
    	property = zend_std_get_static_property(scope, name, name_length, 0 TSRMLS_CC);
    #else
    	property = zephir_std_get_static_property(scope, name, name_length, zend_inline_hash_func(name, name_length + 1), 0, property_info TSRMLS_CC);
    #endif

 This code generated by zephir. But when I do this zephir forum was down.

**Comment by hakimio** [comment] 2018-10-08 13:00
@kov-serg you are looking at some old phalcon version which was made with an old zephir version. That check was removed from zephir some time ago.

Right now you only have the following:

- [object.c#L950 (Zend Engine 3 / PHP 7)](https://github.com/phalcon/zephir/blob/development/kernels/ZendEngine3/object.c#L950)
- [object.c#L1264 (Zend Engine 2 / PHP 5)](https://github.com/phalcon/zephir/blob/development/kernels/ZendEngine2/object.c#L1264)


> But when I do this zephir forum was down.

What do you mean? Do what? Zephir forum?

**Comment by kov-serg** [comment] 2018-10-08 13:08
Yes. I unable to open zephir forum in august.
I know this define was removed. I've compare source code - code is exactly the same except several lines. That's why I asking about them. I still unable to reproduce problem on virtual machine with exactly same versions of os,apache,php and phalcon, may be I need same cpu to reproduce it, but hosting I use unable to solve this issue for more then a year.

**Comment by hakimio** [comment] 2018-10-08 13:16
You should be able to easily reproduce the issue with **Thread-Safe** (the most important part) PHP 7 on Windows and Apache web server.  Once you have everything set-up, just have some loop which makes asynchronous calls (curl?) to your phalcon endpoint and I can guarantee that it will crash.

**Comment by hakimio** [comment] 2018-10-08 13:17
Also, [Zephir forum](https://forum.zephir-lang.com) works well for me. Are you behind Russian national firewall or something?

**Comment by kov-serg** [comment] 2018-10-08 21:19
Now it works. But in august and september it was inaccessible even trough tor.
