### ISSUE TITLE
Phalcon\Mvc\Model - MySQL BIT field

### ISSUE THREAD

**Issue by ndeleplace** [phalcon/cphalcon#11454] opened 2016-02-26 08:16 UTC
Phalcon 2.0.10 seems to have back the issue on BIT field :

if update without any change, values of BIT field 0 (b'0')/false become 1 on update.

See https://github.com/phalcon/cphalcon/issues/1106
It was fixe on 2.0.4 but is now back (because of a last version of MySQL or last version of Phalcon ? )

**Comment by EpicJhon** [comment] 2016-03-16 18:15
+1

**Comment by cbichis** [comment] 2016-10-04 21:23
This bug exists on 3.0.1 also.

**Comment by sergeyklay** [comment] 2016-10-18 23:29
@ndeleplace @EpicJhon  @cbichis
Could you please provide table schema and minimal script to reproduce.
I'll try to sort out

**Comment by ndeleplace** [comment] 2016-11-09 18:54
See [here ](https://github.com/phalcon/cphalcon/issues/1106)

**Comment by ndeleplace** [comment] 2016-11-09 19:02
CREATE TABLE `Test` (
  `Id` int(11) NOT NULL,
  `Name` varchar(50) NOT NULL,
  `synced` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1$$

Create :
$entity ->setName ('toto')->setSynced (0) ....
=> OK boolean FALSE in database entry

UPDATE
$entity ->setName ('toto updated') 
=> boolean TRUE  although it was FALSE/0 before and I set nothing (no setSynced on UPDATE)

I tried '->setSynced ( $entity->getSynced() == false ? 0 : 1 )' ON UPDATE
=> WORK ON ONE SERVER (MYSQL 5.5.47), DOESN'T WORK ON ANOTHER (MYSQL 5.5.43) !
All on PHALCON 2.0.10

**Comment by ndeleplace** [comment] 2016-11-09 19:09
In fact, it seems the solution that work on one server, doesn't work on the other one :

- no setSynced ON UPDATE => MYSQL 5.5.47 = synced changed to b'1', MYSQL 5.5.43 = synced left unchanged (as wanted !) to b'0'
- setSynced ( $entity->getSynced() == false ? 0 : 1 )' => MYSQL 5.5.47 =  synced forced unchanged (as wanted !) to b'0', MYSQL 5.5.43 =  synced changed to b'1'

So it is impossible to have one solution woring with any MySQL version ??

**Comment by ndeleplace** [comment] 2016-11-10 00:01
In fact, getSynced() from existing entity  :

- on one version of MySQL : string(1) ""  if true OR false,
- on another :  string(1) "1" if true, "0" if false.

So depending on MySQL version Phalcon ORM mapping has a different behavior (and always give "string", never mapped the column to a boolean or bit)

And so the update (unless activating dynamicUpdate behavior) in the first case, you got TRUE (b'1') in the end in database even if it was TRUE or FALSE in the first place !

If only it would give string(1) "1" or "0" whatever MySQL version used ... (the best should be to have à bit or boolean real value ...)

**Comment by michalcharvat** [comment] 2017-03-12 00:49
Any update on this issue? I have same problem in MariaDB 10.0.29. Problem will be probably in ORM because all data sent to database are provided as string.

**Comment by thedebian** [comment] 2018-02-06 17:27
This issue makes models with boolean fields unusable, is there a way to plan it before the 4.0.0 milestone ?

**Comment by niden** [comment] 2018-11-02 22:39
Opening a new issue for the 3.4.x version

https://github.com/phalcon/cphalcon/issues/13571

For 4.x, this has been addressed in: https://github.com/phalcon/cphalcon/pull/13562

**Closed by niden** 2018-11-02 22:39 UTC
Labels: Need information, Need script to reproduce
