### ISSUE TITLE
ErrorException: setcookie() expects at most 7 parameters, 8 given

### ISSUE THREAD

**Issue by mvanvu** [phalcon/cphalcon#14643] opened 2019-12-23 03:12 UTC
The issue when I use `(new Phalcon\Debug)->listen(true, true)` and delete a cookie name from CONTROLLER like below
```
if ($this->cookies->has('cms.site.language'))
{
          $this->cookies->delete('cms.site.language');
}
```
It works fine when $lowServerity === false

**Comment by niden** [comment] 2019-12-23 19:01
Resolved in https://github.com/phalcon/cphalcon/pull/14647

Thank you @mvanvu

**Comment by mikacalvo** [comment] 2020-06-08 15:28
Hello, warning keeps being printed if we do : 
   $cookie = $this->cookies->get('cms.site.language');
   $cookie->delete();

**Comment by niden** [comment] 2020-06-08 15:35
> Hello, warning keeps being printed if we do :
> 
> ```
> $cookie = $this->cookies->get('cms.site.language');
> $cookie->delete();
> ```

@mikacalvo What version of Phalcon and PHP are you using?

**Comment by mikacalvo** [comment] 2020-06-08 16:02
I just did the migration PHP 7.4 with Phalcon 4.0. 
In our app's cacheService we were doing a get then a delete, I changed it for a delete with the key as parameter. I reported still the 'bug' just in case

**Comment by BeMySlaveDarlin** [comment] 2021-05-07 20:42
Checked out on clean installation.
Phalcon v.4.0.x, v.4.1.x.
Cannot reproduce, perhaps fixed already.

**Closed** 2021-05-07 20:43 UTC
Labels: 5.0, bug, status: low
