### ISSUE TITLE
[2.1] Phalcon Uniqueness Validation

### ISSUE THREAD

**Issue by bluetec** [phalcon/cphalcon#11173] opened 2015-11-30 02:44 UTC
In Phalcon 2.1 Phalcon\Mvc\Model\Validation is deprecated.

How can check Uniqueness by two fields in phalcon 2.1?

```php
// Sample code in Phalcon 2.0.x
public function validation()
{
    $this->validate(new Uniqueness(array(
        'field' => array('email', 'name')
    )));
}
```

**Comment by andresgutierrez** [comment] 2015-11-30 02:48
You have to pass the model as an option: https://github.com/phalcon/cphalcon/blob/2.1.x/phalcon/validation/validator/uniqueness.zep#L87

```php
'model' => $this
```

Also, for questions like this you can use the forum: https://forum.phalconphp.com/

**Comment by bluetec** [comment] 2015-11-30 02:57
@andresgutierrez 

I did not understand how it should be done.

The code that I used to validate:
```php
public function validation()
    {
        $validator = new Validation();
        $validator->add('reference', new Validation\Validator\Uniqueness([
            'model' => $this,
            'message' => 'Duplicate Reference Code',
            'cancelOnFail' => true
        ]));

        return $this->validate($validator);
    }
```
How do I specify unique constraint for multiple columns. for example reference + userId columns?
What should be changed?

**Comment by ryomo** [comment] 2015-12-11 12:30
This is not implemented in phalcon 2.1 now.

My workaround:

```php
public function validation()
{
    $validator = new Validation();

    $count = self::count([
        'email = ?0 AND name = ?1',
        'bind' => [$this->email, $this->name]
    ]);
    if ($count) {
        $this->appendMessage(new Message('Duplicate !'));
        return false;
    }

    // other validations

    return $this->validate($validator);
}
```

**Comment by sergeyklay** [comment] 2015-12-11 14:48
So it's time to do PR :)

**Comment by nsossonko** [comment] 2016-03-25 19:27
Yes, I noticed this was broken for us too. With the new model one cannot set multi-field uniqueness checks anymore.

**Comment by dschissler** [comment] 2016-04-19 17:45
I have some ideas for how it would look.  Perhaps we could decide on how we would like it to be first.

```php
        $validator->add(null, new Validation\Validator\Uniqueness([
            'model' => $this,
            'fields'   => ['field1', 'field2']
        ]));
```

```php
        $validator->add(['field1'], ['field2'], new Validation\Validator\Uniqueness([
            'model' => $this
        ]));
```

```php
        $validator->add('field1', new Validation\Validator\Uniqueness([
            'model' => $this,
            'also'   => ['field2', 'field3']
        ]));
```

**Comment by dschissler** [comment] 2016-04-26 12:24
It would be great to have this worked out before Phalcon 2.1 goes into 3 years of LTS.  If we don't address this now then we could be stuck with a weird setup for multiple fields for the next 5 years.@sergeyklay @andresgutierrez Please spend just a few minutes to think about this before releasing 2.1.

Ok so sure there are tons of bugs on the issue tracker that need to be addressed but I think that many of those can be fixed in minor changes over the next 3 years.  This is different because its a regression in functionality and there is no super obvious way to implement it.

**Comment by DimazzzZ** [comment] 2016-05-07 19:16
@dschissler absolutely agree.

**Comment by Jurigag** [comment] 2016-05-24 19:58
@dschissler @DimazzzZ

Well im looking into it. But it will require to allow just passing array of fields to add method. Im gonna do some PR to this in few days.

Just as i see in old validator if we was passing an array it was builiding condition just with two parameters. Is it gonna be the same if we just gonna do for in fields we are passing as array and do uniquness for each item in this array ?

**Comment by sergeyklay** [comment] 2016-05-24 21:06
@Jurigag Could you please create PR?

**Comment by andresgutierrez** [comment] 2016-05-24 21:17
However that syntax could be confusing, it could be:

* Add this validator to these fields at the same time 
* and add this validator to these fields individually

**Comment by DimazzzZ** [comment] 2016-05-25 08:47
@andresgutierrez this syntax is the same as in the old implementation of Phalcon 1.3.*. As for me it means exactly "Add this validator to these fields at the same time".

**Comment by Jurigag** [comment] 2016-05-25 08:50
Well actually in old validation it was working diffrent - fields were in uniqueness validator. And there were query etc build for 2 fuilds. Now with this PR i changed it https://github.com/phalcon/cphalcon/pull/11826 - bascially if we pass array of fields to any validator it's just doinf loop in those fields and adding validator for field like it would be added as single field.

**Comment by sergeyklay** [comment] 2016-06-09 22:44
@bluetec @dschissler Could you please check now 2.1.x? See #11826

**Comment by dschissler** [comment] 2016-06-09 23:16
I'm building it now and I'll work with it tomorrow.

**Comment by dschissler** [comment] 2016-06-10 09:42
It works for me so probably this should be closed.  @Jurigag is working on an internal cleanup but it won't affect users.

**Comment by Jurigag** [comment] 2016-06-16 10:22
@dschissler done, added `CombinedFieldsValidator`

**Comment by dschissler** [comment] 2016-06-16 11:39
Sweet.  I saw it.  That solution turned out to be very easy and nice.

**Comment by sergeyklay** [comment] 2016-06-16 11:42
Well, can I close this?

**Comment by Jurigag** [comment] 2016-06-16 11:44
I guess.

**Comment by dschissler** [comment] 2016-06-16 11:45
Yes.  Its totally addressed.

**Comment by sergeyklay** [comment] 2016-06-16 11:54
👍

**Closed by sergeyklay** 2016-06-16 11:54 UTC
