### ISSUE TITLE
\Phalcon\Di:get() fails when it has to return a string.

### ISSUE THREAD

**Issue by vicaba** [phalcon/cphalcon#10244] opened 2015-05-05 08:12 UTC
Getting a string with ``` \Phalcon\Di:get() ``` hangs the program/request.  Instead, ``` \Phalcon\Di:getRaw() ``` works. Don't know if ``` \Phalcon\Di:get() ``` should work with strings, but it should throw an Exception at least.
Here are some examples:
```php
$data = "some string";

$di = new \Phalcon\Di();

$di->set($data);

$di->get($data); // Phalcon gets stuck here

```

```php
$data = "some string";

$di = new \Phalcon\Di();

$di->set($data);

$di->getRaw($data); // Returns "some string"

```

**Comment by Green-Cat** [comment] 2015-05-05 12:06
Phalcon\Di::get() will try to resolve the service. So if you pass it a string it will try to find a class matching that string. Di::getRaw() will just return the string.

**Comment by vicaba** [comment] 2015-05-05 12:55
I know, that's why I was suggesting to add an exception. 
And there's another issue that maybe is worth opening a new "issue". As you said, Phalcon\Di::get() tries to resolve the service and inject himself (the DI) into the object if it implements the appropriate interface, what if I don't want the DI to inject himself but still wanting to resolve the service? I'm facing this problem in a App that I'm doing, I'm using Phalcon components, so I can't modify them. Also, if I could modify/inherit from them it would not be a good OP design. It should be responsibility of the DI call (for example, passing an optional flag).

**Comment by andresgutierrez** [comment] 2015-08-28 21:35
Closed as not a bug

**Closed by andresgutierrez** 2015-08-28 21:35 UTC
Labels: Not a bug
