### ISSUE TITLE
FETCH_COLUMN, FETCH_KEY_PAIR

### ISSUE THREAD

**Issue by hajcu** [phalcon/cphalcon#10138] opened 2015-04-22 15:30 UTC
Fetch column, and fetch key pairs, not working.

This in phalcon 2.0 not work.
````
$result_set->setFetchMode(PDO::FETCH_COLUMN,0);
````

I think phalcon should recoginze this:
````
$sth->fetchAll(PDO::FETCH_COLUMN, 0);
````

But function fetchAll don't see any parameters :)

**Comment by salarmehr** [comment] 2015-04-24 02:53
possible duplicate of https://github.com/phalcon/cphalcon/issues/3191

**Comment by andresgutierrez** [comment] 2015-06-25 03:30
This is fixed in Phalcon 2.0.4

**Closed by andresgutierrez** 2015-06-25 03:30 UTC
