### ISSUE TITLE
Phalcon Logger Interpolation does not work

### ISSUE THREAD

**Issue by Jeckerson** [phalcon/cphalcon#16427] opened 2023-09-09 08:56 UTC
### Discussed in https://github.com/orgs/phalcon/discussions/16425

<div type='discussions-op-text'>

<sup>Originally posted by **gnikolopoulos** September  7, 2023</sup>
Hi all,

I am using the code from [here](https://docs.phalcon.io/5.0/en/logger#interpolation) in order to inject additional, dynamic data into my logging process while calling an external API, but I only get the placeholders themselves instead of the context values.

I am using Phalcon 5.2.1 and even tried the code on the example as is, to no avail.</div>

**Comment by niden** [comment] 2023-09-11 17:10
@gnikolopoulos, @s-ohnishi

The interpolation works just fine. Have a look at this test:

https://github.com/niden/cphalcon/blob/T16427-logger-interpolation/tests/unit/Logger/Formatter/Line/FormatCest.php#L144

and this test:

https://github.com/niden/cphalcon/blob/T16427-logger-interpolation/tests/unit/Logger/Logger/LogCest.php#L184

However

The documentation is incorrect since it shows the use of the `{name}` vs `%name%`.

The logger interpolator placeholders are `%` and not `{`/`}`. 

Apologies for that, I am fixing this now.

**Comment by niden** [comment] 2023-09-11 17:13
Right now there is no way that the placeholders for the interpolation in Logger/Formatter can be set. I will add that later on and let you guys know.

For now if you use `%` it will work.

Please check and let me know so that we can close this if all is OK.

**Comment by niden** [comment] 2023-09-11 17:18
I have updated the docs with the correct code.

**Comment by gnikolopoulos** [comment] 2023-09-11 22:11
> Right now there is no way that the placeholders for the interpolation in Logger/Formatter can be set. I will add that later on and let you guys know.
> 
> For now if you use `%` it will work.
> 
> Please check and let me know so that we can close this if all is OK.

I can confirm that using `%` works fine

**Comment by niden** [comment] 2023-09-11 23:28
Thank you Giorgaki. Closing this one and will work on 16430 shortly

**Closed by niden** 2023-09-11 23:28 UTC
Labels: bug, status: medium, 5.0
