### ISSUE TITLE
[BUG]: Model save: twa_secret is required

### ISSUE THREAD

**Issue by zordon13** [phalcon/cphalcon#14857] opened 2020-02-17 15:07 UTC
Questions? Forum: https://phalcon.link/forum or Discord: https://phalcon.link/discord

**Describe the bug**
In my table i have column name "**twa_secret**" charecter(16). It column dont have "NOT NULL" constraint. When i try save model i have message "twa_secret is required"

**To Reproduce**
```php
<?php

$di = new Phalcon\DI\FactoryDefault();

$di->set('db', function() {
    $connection = new Phalcon\Db\Adapter\Pdo\Postgresql([
        "host" => 'localhost',
        "username" => 'postgres',
        "dbname" => 'test',
    ]);
    return $connection;
}, true);

class TestModel extends \Phalcon\Mvc\Model {

    public $id;
    public $twa_secret;

   
    public function initialize() {
        $this->setSchema("public");
        $this->setSource("test");
    }

}

$sql = 'CREATE TABLE IF NOT EXISTS public.test (id serial,   twa_secret character varying(16),CONSTRAINT test_pkey PRIMARY KEY (id));';
$di->getDb()->execute($sql);
$model = new TestModel();
if ($model->save() === false) {
    foreach ($model->getMessages() as $message) {
        echo $message . PHP_EOL;
    }
}
```

> Provide minimal script to reproduce the issue

```php
twa_secret is required
```

**Expected behavior**
I expect insert row in to table with twa_secret = null.

**Details**
 - Phalcon version: (`php --ri phalcon`)
```
Phalcon is a full stack PHP framework, delivered as a PHP extension, offering lower resource consumption and high performance.
phalcon => enabled
Author => Phalcon Team and contributors
Version => 4.0.4
Build Date => Feb 16 2020 13:03:34
Powered by Zephir => Version 0.12.17-6724dbf

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.case_insensitive_column_map => Off => Off
phalcon.orm.cast_last_insert_id_to_int => Off => Off
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.column_renaming => On => On
phalcon.orm.disable_assign_setters => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.enable_literals => On => On
phalcon.orm.events => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.exception_on_failed_metadata_save => On => On
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.not_null_validations => On => On
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.warning.enable => On => On
```
 - PHP Version: (`php -v`)
```
PHP 7.4.2 (cli) (built: Feb 16 2020 20:34:47) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.2, Copyright (c), by Zend Technologies
    with Xdebug v2.9.2, Copyright (c) 2002-2020, by Derick Rethans
```

 - Operating System:
```
System uname: Linux-5.5.4-gentoo-x86_64-AMD_Ryzen_5_2600_Six-Core_Processor-with-gentoo-2.7
KiB Mem:    32876572 total,   8311688 free
KiB Swap:          0 total,         0 free
Timestamp of repository gentoo: Mon, 17 Feb 2020 07:30:01 +0000
Head commit of repository gentoo: 1b75d9299eed2c2f36d662bf393b5e4c161c650b
sh bash 5.0_p16
ld GNU ld (Gentoo 2.32 p2) 2.32.0
app-shells/bash:          5.0_p16::gentoo
dev-java/java-config:     2.2.0-r4::gentoo
dev-lang/perl:            5.30.1::gentoo
dev-lang/python:          2.7.17-r1::gentoo, 3.6.10::gentoo, 3.7.6::gentoo, 3.8.1::gentoo, 3.9.0_alpha2::gentoo
dev-util/cmake:           3.16.4::gentoo
dev-util/pkgconfig:       0.29.2::gentoo
sys-apps/baselayout:      2.7::gentoo
sys-apps/sandbox:         2.18::gentoo
sys-devel/autoconf:       2.13-r1::gentoo, 2.69-r5::gentoo
sys-devel/automake:       1.13.4-r2::gentoo, 1.15.1-r2::gentoo, 1.16.1-r2::gentoo
sys-devel/binutils:       2.30-r4::gentoo, 2.31.1-r4::gentoo, 2.32-r1::gentoo, 2.33.1-r1::gentoo, 2.34::gentoo
sys-devel/gcc:            8.2.0-r6::gentoo, 8.3.0-r1::gentoo, 9.1.0-r1::gentoo, 9.2.0-r4::gentoo
sys-devel/gcc-config:     2.2.1::gentoo
sys-devel/libtool:        2.4.6-r6::gentoo
sys-devel/make:           4.3::gentoo
sys-kernel/linux-headers: 5.5::gentoo (virtual/os-headers)
sys-libs/glibc:           2.30-r4::gentoo

```
 - Installation type: Compiling from source || installing via package manager
```Compiling from source```

 - Other related info (Database, table schema):
```
postgres (PostgreSQL) 12.1

```

**Comment by zordon13** [comment] 2020-02-17 15:22
When i setup:
```php
\Phalcon\Mvc\Model::setup(
    [
        'notNullValidations' => false,
    ]
);
```
save return true and row has insert, but my column dont have not null constraint.

**Comment by jaguarsdv** [comment] 2020-02-17 18:49
Same problem I have with MySQL and column type TEXT. MySQL do not allowto set a default value for TEXT column but allow to save empty string. With empty string in a model I receive the same error. To solve my problem I need to add $this->allowEmptyStringValues('{column_name}') to models 'initialize' method. So maybe this is not a BUG, just a model behaviour.

**Comment by zordon13** [comment] 2020-02-17 18:54
Problem in version phalcon: 4.0.4
In PHP 7.3.14 phalcon 3.4.5
work as expected (save() => true)

**Comment by zordon13** [comment] 2020-02-17 19:02
In PHP 7.4.2  Version => 4.0.3
work as expected (save() => true)

**Comment by RayHughes** [comment] 2020-05-11 00:27
Having the same issue in PHP 7.4 with PostgreSQL, and Phalcon4. Im strict typed and wondering if that has anything to do it it. I define the value as nullable with a value of null.

I had to work around this by over disabling validation for that field on create and checking wether it was null or not on the update. If it was null on the update, I would then redefine the validation exclusion.

**Comment by zsilbi** [comment] 2020-10-20 23:47
Fixed in https://github.com/phalcon/cphalcon/pull/14876

**Closed by zsilbi** 2020-10-20 23:47 UTC
Labels: bug, status: unverified
