### ISSUE TITLE
[BUG]: PHP7.2, PHALCON 4.0.2, $this->cache->getKeys(),  Use error reporting in the controller

### ISSUE THREAD

**Issue by as882301** [phalcon/cphalcon#14714] opened 2020-01-16 06:37 UTC
public function indexAction()
    {
        $aa = $this->cache->getKeys();
        var_dump($aa);
        die();
   }
Use error reporting in the controller

**Comment by ruudboon** [comment] 2020-01-16 06:41
Can you explain a bit more what the issue is?

**Comment by as882301** [comment] 2020-01-16 06:49
> Can you explain a bit more what the issue is?
--DI
$di->set('cache', function () {
    $config = $this->getConfig();
    $cacheConfig = $config->cache;
    if ($cacheConfig->adapter == 'Stream') {
        if (empty($dir = $cacheConfig->options->storageDir)) {
            throw new \Exception('缓存目录不能为空');
        }
        $dir = Common::dirFormat($dir);
        $mkdirRes = Common::mkdir($dir);
        if (!$mkdirRes) {
            throw new \Exception('创建目录 ' . $dir . ' 失败');
        }
    }
    $options = $cacheConfig->options->toArray();
    $adapterClassName = 'Phalcon\\Cache\\Adapter\\' . Text::camelize($cacheConfig->adapter);
    $serializerFactory = new SerializerFactory();
    $cache = new $adapterClassName($serializerFactory, $options);
    return $cache;
});

--CONFIG
'cache' => [
                'adapter' => 'Stream',
                'options' => [
                    'lifetime' => 7200,
                    'storageDir' => BASE_PATH . RUNTIME .'/cache/file/admin/',
                    'defaultSerializer' => 'Json',
                    'safekey' => false,
                    'prefix' => ''
                ]
        ],

--CONTROLLER
public function indexAction()
{
$aa = $this->cache->getKeys();
var_dump($aa);
die();
}

--ERROR
Warning: Invalid arguments supplied for str_replace() in  controllers\IndexController.php on line 14

**Comment by ruudboon** [comment] 2020-01-16 06:59
Thank you. We will investigate this.

**Comment by as882301** [comment] 2020-01-16 07:03
> Thank you. We will investigate this.

Okay, thank you！

**Comment by duongkhoangiam** [comment] 2020-01-16 16:35
i think problem getKeys need prefix.

**Comment by as882301** [comment] 2020-01-16 16:53
> i think problem getKeys need prefix.

Thank you. But not for that reason. 3.4 uses the function querykeys(). If 4. X is changed to getkeys(), an error will be reported. This function does not need a prefix

**Comment by ekmst** [comment] 2020-01-17 14:59
@as882301 
Some work has been done here https://github.com/phalcon/cphalcon/pull/14721. But I was not able to reproduce this problem.
You can build Phalcon from source (`4.0.x`) and try again?

**Comment by as882301** [comment] 2020-01-18 06:46
> @as882301
> Some work has been done here #14721. But I was not able to reproduce this problem.
> You can build Phalcon from source (`4.0.x`) and try again?

Sorry, I use windows 4.0.2 DLL

**Comment by ruudboon** [comment] 2020-01-22 17:25
@as882301 Could you try picking a dll from AppVeyor https://ci.appveyor.com/project/sergeyklay/cphalcon 
Choose your version and go to Artifacts. 

Othewise I would like to close this issue and it can be re-opened if it still occurs in 4.0.2

**Comment by ruudboon** [comment] 2020-01-25 11:10
Gonna close then assuming it's fixed. If this this is still occurring after our 4.0.3 release please re-open.

**Closed by ruudboon** 2020-01-25 11:10 UTC
Labels: 4.0.3, bug, status: unverified
