### ISSUE TITLE
$this->view->render()   debug

### ISSUE THREAD

**Issue by wydhit** [phalcon/cphalcon#13046] opened 2017-08-29 03:32 UTC
in controller
```php
return $this->view->render("A",'B',['name'=>'sam','age'=>20]);
```
but in view I can not get `$name` `$age`
https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/view.zep#L787-L789

I find this code 
```php
this->_params = params;
```
I thind that code  should be 

```php
this->_viewParams= params;
```
### Details

* Phalcon version: (`3.2.2`)
* PHP Version: (`5.6`)

**Comment by Jurigag** [comment] 2017-08-29 05:37
Hmmm you might be right, i don't even see `this->_params` used anywhere except this line.

**Comment by JABirchall** [comment] 2017-08-30 11:50
I'm not sure if this is how its intended to be used?

I assign the params individually, I also select my view
```
$this->view->pick('post/view/featured');
$this->view->user = $this->auth->user();
$this->view-post = Posts::findByPostId($id);
```
you also don't need to return the view from the controller. After the method executions Phalcon automatically renders the view.

**Comment by wydhit** [comment] 2017-08-30 12:52
`$this->view->setVars(['name'=>'sam','age'=>20]);`
in this way  that no problem


--

**Comment by JABirchall** [comment] 2017-08-31 11:41
>in this way that no problem

So is your problem resolved?

**Comment by Jurigag** [comment] 2017-08-31 15:12
I guess, he just mention here we have some property and method which is actually just some garbage which does nothing.

**Comment by wydhit** [comment] 2017-09-01 00:38
my problem resolved 
@Jurigag yes ,  if this `params ` is no used ，just remove

**Comment by sergeyklay** [comment] 2017-09-24 15:42
Fixed in the `3.2.x branch`. Feel free to open a new issue if the problem appears again. Thank you for contributing.

**Closed by sergeyklay** 2017-09-24 15:42 UTC

**Comment by dugwood** [comment] 2017-10-18 12:52
Just upgraded to 3.2.3, and hit a bug with this fix:
```php
$router->add('/test-page/{bar:[0-9]+}', ['controller' => 'MyController']);
```
```php
$this->view->setVar('bar', 'foo');
```
now returns the dispatcher's `getParam('bar')` value instead of the one set in the view. Shouldn't the dispatcher set its params before allowing `setVar()`? To me it's a breaking change, I'm to fix every controller which has the same parameters as the controller will set :-(

**Comment by Jurigag** [comment] 2017-10-18 13:07
I guess there should be array_merge paras from dispatcher and viewParams then?

**Comment by Jurigag** [comment] 2017-10-18 13:08
Though it's weird, it happens already.

**Comment by dugwood** [comment] 2017-10-18 13:12
It didn't happen in 3.2.2. So it's a breaking change in 3.2.3.

The issue is that `setVars` from dispatcher erase previously declared vars (in the controller). It may be useful to add a «noErase» option in `setVars()`, so that this behaviour is fixed. If I set something in the controller, I think it has to stay with this value.

**Comment by dugwood** [comment] 2017-10-18 13:14
@Jurigag: the issue is not the array_merge, it's the fact that:
https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/application.zep#L351
is run after every `view->setVar()`. Hence `dispatcher->getParams()` will erase any variable set in the controller.

It was indeed a bug, but the fix creates a behaviour that makes the 3.2.3 a 3.3.0...

**Comment by Jurigag** [comment] 2017-10-18 13:15
Yea tbh i don't see really a way to fix it right now. This is beacause of automatic rendering which always is passing parameters. The only way i see is really to https://github.com/sergeyklay/cphalcon/blob/3f703832786c7fb7a420bcf31ea0953ba538591d/phalcon/mvc/view.zep#L432 add here argument like reverse = true(or other name, not sure). And if merge and this reverse is true then do:

```
`let this->_viewParams = array_merge(params, this->_viewParams);`
```

Which will fix this. And use this reverse as true only when adding vars from dispatcher so it won't override params already set.

**Comment by dugwood** [comment] 2017-10-18 13:20
Clearly, as it wasn't working before, we should drop the injection in https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/application.zep#L351

Then we'll think it through, perhaps by setting it when the view is created.

@sergeyklay: can we please rollback this fix and release a new version? Should I open a new bug?

**Comment by dugwood** [comment] 2017-10-18 13:22
Not a rollback, but just remove the injection here:
https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/application.zep#L351

I'm sending a patch right now.

**Comment by Jurigag** [comment] 2017-10-18 13:22
As i told, first happens your view setting, then automatic rendering. There is no really way to reverse this process. But i think what i proposed could be good enough like reverse array_merge when adding parameters from dispatcher. So only any additional parameters are added to view, ones set by us by setVars or setVar will be not replaced this way.

**Comment by dugwood** [comment] 2017-10-18 13:24
@Jurigag the fact is the dispatcher's params were never read => we should ignore these, and that will keep this bug closed, but no breaking change. Then we can think of any other solution to inject dispatcher's params... even if it's useless I think.

Setting a param in a `getRender()` or in a `partial` is logical, forcing the dispatcher's params isn't.

**Comment by Jurigag** [comment] 2017-10-18 13:26
Well maybe yea. I don't see any point of passing dispatcher params to view anyway to be honest. Those are diffrent things really. And since it wasn't working anyway we should just drop this `dispatcher->getParams()` this is other idea worth thinking.

**Comment by dugwood** [comment] 2017-10-18 13:27
Thanks for your input.

I'm opening a new bug and a patch.
