### ISSUE TITLE
Having in query builder breaks total pages and total items of paginator

### ISSUE THREAD

**Issue by Dublerq** [phalcon/cphalcon#12111] opened 2016-08-08 21:23 UTC
Using `having` of a query builder forces it's paginator to show total pages and total items as if there was no `having` set. 
Issue confirmed in 2.1.x and 3.0.0 on windows 7, php 5.6 

How to reproduce:
/bootstrap.php

``` php
use Phalcon\Loader;
use Phalcon\Mvc\View;
use Phalcon\Mvc\Application;
use Phalcon\Di\FactoryDefault;
use Phalcon\Db\Adapter\Pdo\Mysql as DbAdapter;

// Register an autoloader
$loader = new Loader();
$loader->registerDirs(array(
    'models/',
))->register();

$di = new FactoryDefault();

$di->set('view', function () {
    $view = new View();

    $view->setViewsDir('../app/views/');

    return $view;
});

$di->set('url', function () {
    $url = new UrlProvider();

    return $url;
});

$di->set('db', function () {
        return new DbAdapter(array(
            "host"     => "localhost",
            "username" => "root",
            "password" => "",
            "dbname"   => "phalcon_test"
        ));
    });

// Setup the view component

$application = new Application($di);

// Handle the request
//$response = $application->handle();

$query = new \Phalcon\Mvc\Model\Query\Builder();
$query->setDI($di);
$query->columns('*, COUNT(*) as stock_count');
$query->from('A');
$query->groupBy('name');
$query->having('SUM(A.stock) > 0');
var_dump($query->getQuery()->getSql());
$paginator = new \Phalcon\Paginator\Adapter\QueryBuilder(array(
    "builder" => $query,
    "limit" => 1,
    "page" => 2
));
var_dump($paginator->getPaginate());
//$response->send();

```

/model/a.php:

``` php
class A extends Phalcon\Mvc\Model
{    
}
```

sql database dump:

``` sql
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE `a` (
  `id` int(11) NOT NULL,
  `name` varchar(32) NOT NULL,
  `stock` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `a` (`id`, `name`, `stock`) VALUES
(1, 'Apple', 2),
(2, 'Carrot', 6),
(3, 'pear', 0);


ALTER TABLE `a`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `a`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;
```

Expected result:
![image](https://cloud.githubusercontent.com/assets/13312449/17496767/ff78dd64-5dbe-11e6-9e2a-b87d1334bda3.png)

Query builder result:

![image](https://cloud.githubusercontent.com/assets/13312449/17496791/23ce4b22-5dbf-11e6-9ac3-4a3c1543f550.png)

**Comment by Dublerq** [comment] 2016-08-10 18:22
@sergeyklay @Jurigag Can you check it, please? Maybe I am doing something wrong...

**Comment by Jurigag** [comment] 2016-08-10 19:03
Count is done BEFORE having clause.

**Comment by Dublerq** [comment] 2016-08-10 21:06
And IMHO it's a bug because SQL response is different than paginator expected result. You can use neither aliases nor SUM/COUNT... functions  in WHERE so having is the only way here and it must be working properly

**Comment by Jurigag** [comment] 2016-08-10 21:56
What ? But you didnt do COUNT bro. You just did select. Check COUNT(*) on this query. It will return 3 :).

**Comment by Dublerq** [comment] 2016-08-11 04:55
Oh, right, you are right. I didn't know about it, sorry. But still, paginator is working differently than expected so it should be somehow improved. Do you have an idea how can we do it?

**Comment by sergeyklay** [comment] 2016-08-12 05:31
@Dublerq 
> it should be somehow improved

What do you  suggest

**Comment by Dublerq** [comment] 2016-08-12 06:17
Let's count really existing items of query result in php instead of SQL. It should help (It's a guess, I don't know)

**Comment by Izopi4a** [comment] 2016-08-13 10:05
i know its my PR, but still could be useful. 

https://github.com/phalcon/cphalcon/pull/12041

@Dublerq change the file ( cphalcon/phalcon/paginator/adapter/querybuilder.zep ) like like its in the PR, before you compile phalcon, until 3.1 release ( when its gonna be merged ) and do it like in the tests provided / or in description.

**Comment by Jurigag** [comment] 2016-08-13 10:45
But this WONT fix this @Izopi4a The only way is to do:

```
SELECT COUNT(*) FROM (
    OUR SELECT STATEMENT WHICH WILL RETURN THIS ROWS
)
```

But phalcon dont support queries like this.

**Comment by Besedin86** [comment] 2016-09-30 09:12
Have the same problem. When using HAVING in QueryBuilder, pagination execute wrong query. That's why we have to use subquery for true pagination results as @Jurigag wrote above.

**Comment by Jurigag** [comment] 2016-09-30 09:27
As i wrote. Pagination executes PROPER QUERY. Just having works AFTER selecting, count etc. This is not a bug as it is.

**Comment by Jurigag** [comment] 2017-03-14 15:41
Well, i am trying to fix this, but there is a little problem, it would be to heavy operation to figure out which columns to select imho, like get primary keys, figure out alias, user columnMap etc etc, much simpler and faster will be just adding property columns where user will provide for example "Robots.id" and this column will be used for:

```sql
SELECT COUNT(*) FROM {
    SELECT THIS COLUMNS FROM MODEL {

    } as T1
}
```

Don't se really better idea

**Comment by Izopi4a** [comment] 2017-03-14 15:53
i still beleave my idea should be fine, simply because it will be up to the developer to handle his stuff

**Comment by Jurigag** [comment] 2017-03-14 16:08
Hmmm, maybe it can be fine too, i don't know really, it's not hard to do it like my idea, but still developer would need provide columns for count select.

**Comment by Izopi4a** [comment] 2017-03-14 16:11
i absolutely agree with you, i am just afraid that implementing such a dynamic options for pagination might become too complicated / complex to people to use them. 

It just orm should be "1 liner" in my mind, thats all

But i dont mind, if someone come up with a plan we can agree who to cook it up

**Comment by Jurigag** [comment] 2017-03-14 16:27
I mean something like:

```php
'builder'    => $builder, // some builder with Robots aliast and RobotsParts alias
        'limit'      => 20,
        'page'       => $currentPage,
        'columns' => 'Robots.id'
```

And then for getting count there will be query:

```sql
SELECT COUNT(*) FROM {
    SELECT Robots.id FROM // our columns option
    // the rest of query from builder
} as T1
```

Any dynamic way to figure out this columns for this nested select will cause slowdown really.

**Comment by Jurigag** [comment] 2017-03-15 14:00
This thing should be consider as fix or new feature?

**Comment by Jurigag** [comment] 2017-03-17 14:32
https://github.com/phalcon/cphalcon/pull/12712

Here is my PR for this thing, let me know what you think.

**Comment by Jurigag** [comment] 2017-06-23 10:58
This can be closed.

**Closed** 2017-06-23 14:20 UTC
