### ISSUE TITLE
A bizarre question!!!it looks like  impossible !

### ISSUE THREAD

**Issue by lxshui** [phalcon/cphalcon#13145] opened 2017-11-03 12:28 UTC
As shown below:
![deepinscreenshot_select-area_20171103201541](https://user-images.githubusercontent.com/18578376/32373664-5128d0c2-c0d5-11e7-8c19-9a4e2cdd5cc8.png)

Then I did an experiment,the Code structure is same as phalcon.but result....

```php
<?php
class a
{
    public $fun;
    public function setb(callable $fun)
    {
        $this->fun = $fun;
    }
    public function getb($p)
    {
        return call_user_func($this->fun);
    }
}
$a = new a();
$a->setb(
    function () {
        var_dump($this);
        return 'fffffff';
    }
);
echo $a->getb('');

```
Result::!!!!
![deepinscreenshot_select-area_20171103202620](https://user-images.githubusercontent.com/18578376/32373678-62ae42c8-c0d5-11e7-9df8-85f987e0fdc3.png)

why ????

**Comment by victorhramos** [comment] 2017-11-03 14:40
```php
public function setb(callable $fun)
 {
        $this->fun = $fun;
        
        **return $this;**
 }
```

???

**Comment by Jurigag** [comment] 2017-11-03 20:20
http://php.net/manual/en/closure.bindto.php can be closed

**Comment by sergeyklay** [comment] 2017-11-03 21:13
I'm closing since this is a not a bug report. We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).

**Closed by sergeyklay** 2017-11-03 21:13 UTC
