### ISSUE TITLE
[BUG]: Use of "static" in callables is deprecated 

### ISSUE THREAD

**Issue by robert-deepnorth** [phalcon/cphalcon#16408] opened 2023-08-17 04:43 UTC
**Describe the bug**
PHP throws error while using model's static method find() and findFirst()

**To Reproduce**
```php
$rows = Robots::find([
    'columns' => 'id',
    'conditions' => 'status_id IN ({ids:array})',
    'bind' => ['ids' => [1, 3]],
]);
```
  
**Details**
 - Phalcon version: 5.2.3
 - PHP Version: 8.2.9
 - Operating System: Centos Stream 8
 - Installation type: installing via remi package manager
  dnf module enable php:remi-8.2
  dnf install php-phalcon5
 - Server: Nginx

**Comment by niden** [comment] 2023-08-17 12:44
Related https://github.com/phalcon/cphalcon/issues/16263

**Comment by hakimio** [comment] 2023-08-17 14:08
Also https://github.com/zephir-lang/zephir/issues/2405

**Comment by rudiservo** [comment] 2023-08-25 18:46
@niden Paginator\Adapter\Model has a call_user_func in line 116, that also throws a warning.
line 100 might be the issue.

**Comment by niden** [comment] 2024-01-06 22:54
Closing this - duplicate of https://github.com/phalcon/cphalcon/issues/16263

Tracking progress there.

**Closed by niden** 2024-01-06 22:54 UTC
Labels: bug, status: medium, external dependency, 5.0
