### ISSUE TITLE
[BUG]: Phalcon\Image\Adapter\Gd throwing an exception for the text function

### ISSUE THREAD

**Issue by nickweavers** [phalcon/cphalcon#15188] opened 2020-10-27 10:37 UTC
Questions? Forum: https://phalcon.link/forum or Discord: https://phalcon.link/discord

**Describe the bug**
Phalcon\Image\Adapter\Gd throwing an exception for the text function
I have described the issue here and  what I have  done to investigate:
https://stackoverflow.com/questions/64541937/phalcon-image-adapter-gd-throwing-an-exception-for-the-text-function
But I think this must be a bug because I am calling the text function with the correct parameters as per the Phalcon 3.4 docs.

I have the following in my code:
```
use Phalcon\Image\Adapter\GD as Image;
...
    $imagePath = BASE_DIR . '/public/img/map-icons/' . $client->getId() . '/' . $file;
    $image = new Image($imagePath);
...
    $fontFile = $this->getFontPath();
    $image->text($text, $x, $y, 1, '#FFFFFF', $fontSize, $fontFile);
```
Under Phalcon 1.3.4 and php 5.4.45 it works fine, but when I migrated the application to a new server running Phalcon version 3.4.5 and php 7.3.17 the ``$image->text($text, $x, $y, 1, '#FFFFFF', $fontSize, $fontFile);`` is giving the following error:
```
Project staging.api.my-domain.com raised exception class Phalcon\lmage\Exception with message "Call to imagettfbboxO failed" at gd.zep, line 357
```
The literal values being passed to $image->text(..) are as follows:
```
$image->text(H, 9, 20, 1, '#FFFFFF', 11, '/var/www/vhosts/staging.api.mydomain.com/src/fonts/arialbd.ttf');
```
When I try the example for PHP's imagettfbbox given on the page here ``https://www.php.net/manual/en/function.imagettfbbox.php`` the example works and shows a white box with text written across it diagonally.

So it doesn't appear to be a problem  with PHP imagettfbbox.

**Details**
 - Phalcon version: 3.4.5
 - PHP Version: 7.3.17
 - Operating System: Amazon Linux (an EC2)
 - Installation type: ``sudo yum-config-manager --enable remi-php73``
 - Zephir version (if any):
 - Server: Apache
 - Other related info (Database, table schema):

**Additional context**
Here are the php extensions that are installed:
```
$ php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dbg
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
memcached
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
phalcon
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
zip
zlib
```

**Comment by nickweavers** [comment] 2020-10-27 11:43
I have created a small test case:
```
<?php
DebugBreak('1@127.0.0.1:7869');
require('../vendor/autoload.php'); 
use Phalcon\Image\Adapter\GD as Image;
$imagePath = './img/map-icons/sebroche/house.png';
$image = new Image($imagePath);
$fontPath = '../fonts/arialbd.ttf';
$image->text('Hello', 20, 20, 9, '#FFFFFF', 10, $fontPath);
?>
```
Here's the output when I run it from the cli:
```
$ php test.php
PHP Fatal error:  Uncaught Phalcon\Image\Exception: Call to imagettfbbox() failed in phalcon/image/adapter/gd.zep:357
Stack trace:
#0 [internal function]: Phalcon\Image\Adapter\Gd->_text('Hello', 20, 20, 9, 255, 255, 255, 10, '../fonts/arialb...')
#1 /var/www/vhosts/staging.api.mydomain.com/src/public/test.php(8): Phalcon\Image\Adapter->text('Hello', 20, 20, 9, '#FFFFFF', 10, '../fonts/arialb...')
#2 {main}
  thrown in phalcon/image/adapter/gd.zep on line 357
```

**Comment by Jeckerson** [comment] 2020-10-27 11:49
Related #14950

**Comment by Jeckerson** [comment] 2020-10-27 12:46
@nickweavers Please try to specify absolute path to the font inside `$fontPath` variable.

**Comment by nickweavers** [comment] 2020-10-27 12:59
Okay, I have updated my example to use absolute paths:
```
<?php
DebugBreak('1@127.0.0.1:7869');
require('../vendor/autoload.php'); 
use Phalcon\Image\Adapter\GD as Image;
$imagePath = '/var/www/vhosts/staging.api.mydomain.com/src/public/img/map-icons/sebroche/house.png';
$image = new Image($imagePath);
$fontPath = '/var/www/vhosts/staging.api.mydomain.com/src/fonts/arialbd.ttf';
$image->text('Hello', 20, 20, 9, '#FFFFFF', 10, $fontPath); 
?>
but I still get the error:
```
$ php test.php
PHP Fatal error:  Uncaught Phalcon\Image\Exception: Call to imagettfbbox() failed in phalcon/image/adapter/gd.zep:357
Stack trace:
#0 [internal function]: Phalcon\Image\Adapter\Gd->_text('Hello', 20, 20, 9, 255, 255, 255, 10, '/var/www/vhosts...')
#1 /var/www/vhosts/staging.property-api-v2.supadu.com/src/public/test.php(8): Phalcon\Image\Adapter->text('Hello', 20, 20, 9, '#FFFFFF', 10, '/var/www/vhosts...')
#2 {main}
  thrown in phalcon/image/adapter/gd.zep on line 357
```

**Comment by Jeckerson** [comment] 2020-10-27 13:53
To hotfix your problem, just do not specify `$fontPath` variable into `text()` method.

The problem is located in `let s0 = (int) space[0];`, which apparently can not be zero (according existing logic).
https://github.com/phalcon/cphalcon/blob/a8035814aa9a8a2438f92ebf5128964e7c48fd3f/phalcon/Image/Adapter/Gd.zep#L602-L612

**Comment by nickweavers** [comment] 2020-10-27 14:12
@Jeckerson, what font will it use if one cannot be given to the text() method?

**Comment by Jeckerson** [comment] 2020-10-27 15:43
@nickweavers It will use different approach with different functions.

https://github.com/phalcon/cphalcon/blob/a8035814aa9a8a2438f92ebf5128964e7c48fd3f/phalcon/Image/Adapter/Gd.zep#L641-L654

Check docs of `imagestring` function - https://www.php.net/manual/en/function.imagestring.php

**Comment by niden** [comment] 2021-04-21 13:10
Thank you @nickweavers for the report.

This has been resolved with https://github.com/phalcon/cphalcon/pull/15418

**Closed by niden** 2021-04-21 13:10 UTC
Labels: 5.0, bug, status: low
