### ISSUE TITLE
[BUG]: Null cannot be set in the source parameter when firing an event.

### ISSUE THREAD

**Issue by fagai** [phalcon/cphalcon#15133] opened 2020-08-20 21:28 UTC
**Describe the bug**

Null cannot be set in the source parameter when firing an event.
There is an example using null in the documentation.
https://docs.phalcon.io/4.0/ja-jp/events#responses

Also, you cannot specify a character string.
There are many examples of using $this in the documentation, but I put values ​​such as user_id.

https://github.com/phalcon/cphalcon/commit/c4cf1db714fa32ef5526baebd37f7df6572418b7

**To Reproduce**
> Phalcon\Events\Exception: The source of register event must be an object, got NULL"
> Phalcon\Events\Exception: The source of register event must be an object, got string

```php
$eventsManager->fire('custom:custom', null);
```

> Provide minimal script to reproduce the issue

```php
<?php

use Phalcon\Events\Manager as EventsManager;

$eventsManager = new EventsManager();

$eventsManager->attach(
    'custom:custom',
    function () {
        return 'first response';
    }
);

$eventsManager->fire('custom:custom', null);
```

**Expected behavior**

```php
No Error
```

**Details**
 - Phalcon version: 4.0.5
- PHP Version: 7.2.30
 - Operating System: alpine linux
 - Installation type: Compiling from source
 - Zephir version (if any): 
 - Server: Apache+php-fpm
 - Other related info (Database, table schema):

**Comment by fagai** [comment] 2020-11-04 02:47
This issue worked in 3.4.

**Comment by Izopi4a** [comment] 2021-05-04 08:04
i don't think this would have workerd in any 3.x version. Based on this : https://github.com/phalcon/cphalcon/blob/3.0.x/phalcon/events/manager.zep#L376 2nd parameter is always the component that is listening for the event. 
the 3rd param ( data ) can be null. Seems like the docs are wrong and needs to be updated

**Comment by fagai** [comment] 2021-05-04 08:14
In the service I was developing, I have confirmed that it worked without problems even if the second argument was null. (v3.4.5)

**Comment by Izopi4a** [comment] 2021-05-04 09:10
ok indeed in 3.4.x is working. for me it is 

```
Version | 3.4.4 //phalcon
Powered by Zephir | Version 0.10.16-6826149172
```

but i think this issue is because of https://github.com/zephir-lang/zephir/issues/1656. This was merged in zephir 0.11+ and we used zephir 0.10 to build phalcon 3.4.X because it was breaking everything. before that zephir wasn't respecting params and return types correctly.

for me we only need to update the docs, I don't think there is a bug here. 

also I am able to reproduce this error:
```
 [TypeError] Phalcon\Events\Manager::fire(): Argument #2 ($source) must be of type object, null given
``` 

and not exactly what you have shown. but I am pretty sure it is the same case.

**Comment by fagai** [comment] 2021-05-04 09:20
I see.

I had this problem because I sometimes didn't use the second argument.
Currently, we are dealing with it by passing an empty object. So if it's in the right direction, that's fine.

**Comment by Jeckerson** [comment] 2021-05-04 09:30
I'm starting to see some sense to 2nd argument `source` be `nullable`:

```
object source = null
```

@niden Could you provide more information if my thoughts makes sense?

**Comment by niden** [comment] 2021-10-05 18:56
I looked at the manager code and making the `source` `nullable` can be done. The manager can fire the event when the `source` is null

```
let status = call_user_func_array(
    handler,
    [event, source, data]
);
```

We can make this change in v5 since it will break BC.

**Comment by niden** [comment] 2021-10-05 18:57
Personally I never had to send `null` to the source; I always sent the actual object that was using this code.

**Comment by niden** [comment] 2021-10-06 15:08
Resolved in https://github.com/phalcon/cphalcon/pull/15710

Thank you @fagai

**Closed by niden** 2021-10-06 15:08 UTC
Labels: documentation, breaks bc, bug, status: low, 5.0
