### ISSUE TITLE
[BUG][1.3.0] Phalcon\Mvc\Model\Query\Builder + Paginator query builder + HAVING SQL = error

### ISSUE THREAD

**Issue by lantian** [phalcon/cphalcon#2068] opened 2014-02-21 13:25 UTC
Example php code:
```php
$builder = new Builder();
        $builder
            ->columns(['u.*', 'role' => 'r.name'])
            ->addFrom('User\Model\User', 'u')
            ->leftJoin('User\Model\Role', 'u.role_id = r.id', 'r')
            ->having("role LIKE '%Admin%'");

$qb = new QueryBuilder(
            [
                "builder" => $builder,
                "limit" => $this->getItemsCountPerPage(),
                "page" => $this->getDI()->getRequest()->getQuery('page', 'int', 1)
            ]
        );

$this->_paginator = $qb->getPaginate();
```

Throws an exception:
```text
Phalcon\Mvc\Model\Exception: 
Column 'role' doesn't belong to any of the selected models (1), when preparing:

SELECT COUNT(*) [rowcount] 
FROM [User\Model\User] AS [u] 
LEFT JOIN [User\Model\Role] AS [r] ON u.role_id = r.id 
HAVING role LIKE '%Admin%' 
```
It erase all 'columns' data with COUNT(\*). Actually it must add COUNT(\*) AS rowcount to the end of columns SQL query, that will become like: "SELECT u.\*. r.name AS role, COUNT(\*) AS rowcount"

**Comment by andresgutierrez** [comment] 2015-06-23 15:15
Closed as not a bug

**Closed by andresgutierrez** 2015-06-23 15:15 UTC
Labels: Not a bug
