### ISSUE TITLE
Custom Resultsets getResultsetClass have a bug

### ISSUE THREAD

**Issue by pz9042** [phalcon/cphalcon#14245] opened 2019-07-12 10:02 UTC
php version is 7.2.19, and phalcon version is 3.4.3

I add below code in my model 

```php
public function getResultsetClass(){
	    return 'Patient\Models\Custom';
	}
```
when i call find in this way
```php
$r = ClinicalDepartment::find( [ 'conditions' =>'parent_id> :parent_id:', 'bind' =>[ 'parent_id' =>'0' ], 'columns' =>'department_id,department_name,ico' ] );
    	print_r($r);exit;
```
the result return a `Phalcon\Mvc\Model\Resultset\Simpl` object ,and  _model is `Phalcon\Mvc\Model\Row Object`

if i don't specify columns in `find` parameter, the result return `Patient\Models\Custom` object, and _model is `Patient\Models\ClinicalDepartment Object`

**Comment by Jurigag** [comment] 2019-07-22 12:20
This is not a bug, it works as expected. When you use columns then you have not full model object, hat's why it returns simple resultset class. It will return your custom only if you get full models.

**Comment by pz9042** [comment] 2019-07-28 06:42
> This is not a bug, it works as expected. When you use columns then you have not full model object, hat's why it returns simple resultset class. It will return your custom only if you get full models.

thanks to your answer

**Comment by ruudboon** [comment] 2019-08-03 13:40
Can we close this?

**Closed** 2019-08-03 13:49 UTC
Labels: 4.0, Not a bug
