### ISSUE TITLE
[BUG]: Fatal error: Return value of Phalcon\Mvc\View\Engine\AbstractEngine::partial() must be of the type string, null returned in Unknown on line 0 Call Stack

### ISSUE THREAD

**Issue by jonnywang** [phalcon/cphalcon#14429] opened 2019-09-29 07:31 UTC
cphalcon-4.0.0-rc.1 
```
<?php $this->partial('_partials/header'); ?>
<?php echo $this->getContent(); ?>
<?php $this->partial('_partials/footer'); ?>
```

**Comment by Jeckerson** [comment] 2019-09-29 08:35
Why you call second partial with from `view`?

Instead
```
<?php $this->view->partial('_partials/footer'); ?>
```

Try
```
<?php $this->partial('_partials/footer'); ?>
```

**Comment by jonnywang** [comment] 2019-09-29 09:55
i use <?php $this->view->partial('_partials/footer'); ?> is ok

```
<?php $this->partial('_partials/header'); ?>
<?php echo $this->getContent(); ?>
<?php $this->partial('_partials/footer'); ?>
```

works fine on v3.4.4, but v4.0.0-rc.1 will ouput Fatal error

**Comment by niden** [comment] 2019-09-29 14:34
I need to confirm this but it seems that we will need to add `null` to the return type for `partial`

This is not an issue with v3 because it uses an older version of Zephir that allows this to pass, whereas v4 is more strict with interfaces and return types.

**Comment by ruudboon** [comment] 2019-09-30 12:39
@jonnywang Can you give me some more info/code how to reproduce this issue?
Trying it based on the code above but unable to reproduce this errors.

**Comment by jonnywang** [comment] 2019-10-04 13:55
```php
class IndexController extends \Phalcon\Mvc\Controller
{

	public function todoAction()
	{
		$this->view->setMainView('_layouts/default');
	}

}

### views/_layouts/default.phtml
```
<?php $this->partial('_partials/header'); ?>
<?php echo $this->getContent(); ?>
<?php $this->partial('_partials/footer'); ?>
```

### views/_partials/header.phtml
### views/_partials/footer.phtml
### views/index/todo.phtml

**Comment by niden** [comment] 2019-10-05 17:16
Resolved in https://github.com/phalcon/cphalcon/pull/14447

**Closed by niden** 2019-10-05 17:16 UTC
Labels: 4.0, Breaks BC, Bug - Medium, Hacktoberfest, Need script to reproduce
