### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by RayHughes** [phalcon/cphalcon#15112] opened 2020-07-17 14:39 UTC
**Describe the bug**
Uniqueness validator does not check for differences in case with the database field itself allowing a duplicate value to be entered into the database itself. 

**To Reproduce**
Add a record to your database in all capitals. Attempt to create a user using the below validation. A duplicate user will be created.  

Api Request Validator

```php
        $this->add(
            'username',
            new Uniqueness(
                [
                    'model' => new User(),
                    'message' => 'Username is taken',
                    'convert' => function (array $values) {
                        $values["username"] = strtolower($values["username"]);

                        return $values;
                    }
                ]
            )
        );
```

**Expected behavior**
Validation will fail because there is a match as the database field would be compared in lowercase as well.

**Screenshots**
<img width="109" alt="Screen Shot 2020-07-17 at 10 34 36 AM" src="https://user-images.githubusercontent.com/4381883/87797774-2775f180-c819-11ea-9865-f9432ad90f5b.png">

**Details**
 - Phalcon version: 4.0.6
 - PHP Version: 7.4.x
 - Operating System: Alpine (Docker)
 - Installation type: Compiling from source
 - Zephir version (if any): 
 - Server: Nginx
 - Database: Postgres

**Comment by Jeckerson** [comment] 2020-07-23 09:45
Current validation will depend on database configuration of case sensitivity. In your case you could create validation via Callback Validator and make custom query will it will check case of string.

**Comment by zsilbi** [comment] 2020-09-09 23:04
@RayHughes you can use a different collation in the database (for example in MySQL: `utf8mb4_bin`) to prevent this.

Not a bug, closing this.

**Closed by zsilbi** 2020-09-09 23:04 UTC
Labels: bug, status: unverified
