### ISSUE TITLE
Volt nesteds blocks

### ISSUE THREAD

**Issue by kniaz-tolya** [phalcon/cphalcon#10914] opened 2015-09-09 16:25 UTC
if the opportunity to implement in volt, it does not support nested blocks?
Forced to use temporary twig

{% extends "layout.volt" %}

{% block content %}
   {% block body %}
            Content Body Text
   {% endblock %}
 Content Text
{% endblock %}

**Comment by lajosbencz** [comment] 2015-09-09 16:30
Duplicate of #329 

According to the roadmap, it will be implemented in the 2.1 version: https://github.com/phalcon/cphalcon/wiki/Roadmap

**Closed** 2015-09-09 16:43 UTC

**Comment by kniaz-tolya** [comment] 2015-09-09 16:47
Thanks
