### ISSUE TITLE
2.0.x PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'username.tablename' doesn't exist 

### ISSUE THREAD

**Issue by zikezhang** [phalcon/cphalcon#10360] opened 2015-05-15 15:33 UTC
*  I find my table via findFirst
```javascript
$user = \Model\User::findFirst([                                       
    "(email :email: OR id = :email:) AND pw = :password:'",  
    'bind' => array('email' => $email, 'password' => sha1($password))                     
]);                                                                                       
```
and is indeed get right data.

*   I update the instance 
```javascript
$user->setLoginTime(date("Y-m-d H:i:s"));                  
$user->setLoginIp($this->request->getClientAddress());     
```

*  I save the instance.
```javascript
if ($user->update() == false) {                             
    $user->rollback("Cannot Update User Login info");   
    foreach ($user->getMessages() as $message) {            
        echo $this->flashSession->error($message);              
    }                                                           
}                                                               
```

I got the error
> PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'username.tablename' doesn't exist 

so, I am confused that why I can't save the data, and also why is
>username.tablename' 

not 
>databasename.tablename' 

?

**Comment by SidRoberts** [comment] 2015-05-15 16:09
The problem is likely with your DB service:

```php
// Setup the database service
$di->set('db', function(){
    return new DbAdapter(array(
        "host"     => "localhost",
        "username" => "root",
        "password" => "secret",
        "dbname"   => "test_db"
    ));
});
```

Are you `username` and `dbname` parameters set correctly?

**Comment by zikezhang** [comment] 2015-05-15 16:17
Sure, the DB parameters is right.

And I can use 
>findFirst(['']);

**Comment by sergeyklay** [comment] 2016-06-09 21:07
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Closed by sergeyklay** 2016-06-09 21:07 UTC
Labels: Need information, Need script to reproduce
