### ISSUE TITLE
[BUG]: TagFactory __invoke and Html\Helper\Meta,Link,Script,Style. Store reset at each call

### ISSUE THREAD

**Issue by yannux** [phalcon/cphalcon#16441] opened 2023-09-26 16:13 UTC
**Describe the bug**
When calling  multiple times the Meta helper, previous stored values disappear.

**To Reproduce**

```php
//IndexController.php
$this->tag->meta()->addName('robots', 'index, nofollow');

//index.phtml
<?= $this->tag->meta()->addName('author', 'Me'); ?>
```
Only output 
```html
<meta name="robots" content="index,nofollow">
```

Another quick example 
```
var_dump($this->tag->meta()->addName('test1', 'test1')->addName('test2', 'test2')->__toString());
var_dump($this->tag->meta()->addName('test3', 'test3')->__toString());
```
![image](https://github.com/phalcon/cphalcon/assets/533125/c68b9d3a-a624-42d0-9fef-fd3652327f7f)

**Expected behavior**

```php
//IndexController.php
$this->tag->meta()->addName('robots', 'index, nofollow');

//index.phtml
<?= $this->tag->meta()->addName('author', 'Me'); ?>
```
Must output 
```html
<meta name="robots" content="index,nofollow">
<meta name="author" content="me">
```

**Details**
 - Phalcon version: 5.3.0
 - PHP Version: 8.1.23
 - Operating System: DEbian
 - Installation type: pecl
 - Server: Apache
 
**Additional context**

Each time you call  $this->tag->meta()  AbstractSeries::__invoke reset the store
![image](https://github.com/phalcon/cphalcon/assets/533125/df324283-315e-44fb-a3ef-dd34607fe9d9)

**Comment by niden** [comment] 2023-09-26 18:52
I am not sure if this is a bug to be honest.

Doing this:

```php

$this
    ->tag
    ->meta()
        ->addName('robots', 'index, nofollow')
        ->addName('author', 'Me')
;
```
will produce 
```
    <meta name="robots" content="index, nofollow">
    <meta name="author" content="Me">
```

If you change the example to this:

```php
// IndexController.php
$this->tag->meta()->addName('robots', 'index, nofollow');

// index.phtml
<?php $this->tag->meta()->addName('author', 'Me'); ?>
<?= $this->tag->meta(); ?>
```
then it should work as expected. The chaining makes the `__toString()` called first since you use `<?=` and the contents get cleared, and then the assignment comes with `addName`. I think that is what is happening there.

A test that I wrote is as follows

```php
        $escaper = new Escaper();
        $meta    = new Meta($escaper);
        $meta
            ->addName('robots', 'index, nofollow')
            ->addName('author', 'Me')
        ;

        $expected = '    <meta name="robots" content="index, nofollow">'
            . PHP_EOL
            . '    <meta name="author" content="Me">'
            . PHP_EOL;
        $actual   = (string) $meta;
        $I->assertSame($expected, $actual);

        $meta = new Meta($escaper);
        $meta->addName('robots', 'index, nofollow');

        $expected = '    <meta name="robots" content="index, nofollow">'
            . PHP_EOL
            . '    <meta name="author" content="Me">'
            . PHP_EOL;
        $actual   = (string) $meta->addName('author', 'Me');
        $I->assertSame($expected, $actual);
```

As you can see it works with either setting the `addName` further down.

I am wondering, can you try something like this and let me know?

```
//IndexController.php
$this->tag->meta()->addName('robots', 'index, nofollow');

//index.phtml
<?= ($this->tag->meta()->addName('author', 'Me')); ?>
```

**Comment by s-ohnishi** [comment] 2023-09-27 02:36
I tried.
```PHP
// IndexController.php
$this->tag->meta()->addName('robots', 'index, nofollow');

// index.phtml
<!-- start -->
<?php $this->tag->meta()->addName('author', 'Me'); ?>
<?= $this->tag->meta(); ?>
<!-- end -->
```
The results are below.
````HTML
<!-- start -->
<!-- end -->
````
Currently, I think it is possible to obtain the expected output with the following.
```PHP
// index.phtml
<!-- start -->
<?= $this->tag->newInstance('meta'); ?>
<?= $this->tag->meta()->addName('author', 'Me'); ?>
<!-- end -->
````
In this case, it will be as follows.
```HTML
<!-- start -->
    <meta name="robots" content="index, nofollow">
    <meta name="author" content="Me">
<!-- end -->
```
Although the method name is "new"Instance, it returns the registered "old"Instance.


PHP 8.1.20
Phalcon 5.3.1

**Comment by s-ohnishi** [comment] 2023-09-27 03:37
Since you can only have one TagFactory for each service (tag), you cannot write multiple tags at the same time unless you retain the instance of the service you created first.

If you use `$this->tag->meta()`, a new instance will be returned, so if you do the following, the viewport will disappear.
```PHP
class IndexController extends \Phalcon\Mvc\Controller
{
     public function beforeExecuteRoute($dispatcher)
     {
         $this->tag->meta()->addName('viewport', 'idth=device-width, initial-scale=1.0');
     }
     public function indexAction()
     {
         $this->tag->meta()->addName('robots', 'index, nofollow');
     }
````
Hasn't this been pointed out as an odd specification (probably a bug)?

If you want to use it like this, you need to do the following.
```PHP
class IndexController extends \Phalcon\Mvc\Controller
{
     protected $meta;
     public function beforeExecuteRoute($dispatcher): void
     {
         $this->meta = $this->tag->meta()->addName('viewport', 'idth=device-width, initial-scale=1.0');
     }
     public function indexAction()
     {
         $this->meta->addName('robots', 'index, nofollow');
     }
````
Honestly, I think it's very inconvenient.

**Comment by yannux** [comment] 2023-09-27 07:42
Yes it's not conveniant. 

I try another workaround, 

```php
//BaseController (used for common code for others controller
$this->view->meta = $this->tag->meta();


//IndexController extends BaseController
$this->view->meta->addName('description', 'foo');

//index.phtml  works with this->view ok $meta
<?= $this->view->meta;?> //works
<?= $this->view->meta->addName('foot', 'bar');;?> //works
```

**Comment by yannux** [comment] 2023-09-27 07:45
> Hasn't this been pointed out as an odd specification (probably a bug)?

Don't know, Niden said on discord : 
``` 
Meta should be doing the same thing as title because it is the same code that handles either of those helpers.
```
(https://discord.com/channels/310910488152375297/310910488152375297/1104470868131852392)

So if it's intended to work like Title, we can expect to be able to do $this->tag->meta()  on different file without loosing data ?

**Comment by s-ohnishi** [comment] 2023-09-27 13:16
Similar to `title`, which is output only once, meta, style, script, etc., which output multiple tags, return instances registered in `TagFactory`, so their usage is the same.
However, as pointed out by yannux, `__invoke()` uses `this->store = [];`, so the contents are cleared every time it is called.

There is no problem with clearing it when you intend, but since it is not common, I think it is acceptable to call it in a special way.
I think adding something will be used a lot.
Currently, it is quite troublesome to have to call `tag->newInstance('meta')->addName()` to a registered "old" instance and be careful not to clear its contents.

Conversely, you may want to output the same tag with different content regardless of what is registered in `store`.
now
```PHP
<?= $this->tag->meta()->addName('something', 'foo'); ?>
````
is very intuitive and easy to use, but it destroys registered information, so I don't think there is any other way than to write the HTML directly instead of using a helper.
If `newInstance()` really returned a new instance, we wouldn't have to do that.

**Comment by s-ohnishi** [comment] 2023-09-27 13:53
Looking at the manual, it seems that CSS and JavaScript are based on the use of assets.
I don't think there is any alternative for meta.
They may choose to extend the assets rather than change the obscure specification of the AbstractSeries class.
I think it's a bug, so I'm hoping that the twisted specifications will be fixed to a straightforward one.

**Comment by s-ohnishi** [comment] 2023-09-28 00:27
@yannux 
> So if it's intended to work like Title, we can expect to be able to do $this->tag->meta() on different file without loosing data ?

Currently, I think this is possible by using `$this->tag->newInstance('meta')`.
It's not "new" at all, so I'm not convinced by the name and specifications.

**Comment by yannux** [comment] 2023-09-28 13:04
@s-ohnishi  
> > So if it's intended to work like Title, we can expect to be able to do $this->tag->meta() on different file without loosing data ?
> 
> Currently, I think this is possible by using `$this->tag->newInstance('meta')`. It's not "new" at all, so I'm not convinced by the name and specifications.

Yes I'm ok with that. 

So currently I'm using this solution :
```php
//BaseController (used for common code for others controller
$this->view->meta = $this->tag->meta();


//IndexController extends BaseController
$this->view->meta->addName('description', 'foo');

//index.phtml  works with this->view ok $meta
<?= $this->view->meta; ?> //works
<?= $this->view->meta->addName('foo', 'bar'); ?> //works
```

**Comment by s-ohnishi** [comment] 2023-09-28 14:19
@yannux 
I'm glad you found your solution with the current Phalcon.

**Comment by niden** [comment] 2023-10-02 13:09
@yannux What is the status of this?

I saw you made some changes as a workaround by assigning the `meta()` to a variable. Did any of the suggestions I posted work? 

Can you try this:

```
//IndexController extends BaseController
$this->tag->meta()->addName('description', 'foo');

//index.phtml
<?= $this->tag->meta()->addName('foo', 'bar'); ?>
<?= $this->view->meta(); ?>
```

**Comment by yannux** [comment] 2023-10-02 13:28
@niden  sorry I was focus in test and exchange with  s-ohnishi  and did not answer you :(

![image](https://github.com/phalcon/cphalcon/assets/533125/1b259333-b92d-4790-b53a-428a1ea76b93)

The result is
```html
 <!-- start $this->tag->meta()->addName('foo', 'bar') -->
     <meta name="foo" content="bar">
 <!-- end $this->tag->meta(); -->
```

**Comment by niden** [comment] 2023-10-02 13:42
This is so weird. I will do some more investigation on this. You should be seeing both meta tags. Sigh

**Comment by niden** [comment] 2023-10-02 13:42
Thank you for testing

**Comment by yannux** [comment] 2023-10-02 13:46
> Each time you call $this->tag->meta() AbstractSeries::__invoke reset the store
> ![image](https://user-images.githubusercontent.com/533125/270723711-df324283-315e-44fb-a3ef-dd34607fe9d9.png)

maybe because of this?

**Comment by niden** [comment] 2023-10-02 13:56
Most likely yes. That is where I was leaning

**Comment by niden** [comment] 2023-10-02 13:58
Initially I was thinking of introducing a `->reset()` method which would clear the store. It looks that we need that.

**Comment by s-ohnishi** [comment] 2023-10-03 02:59
> Initially I was thinking of introducing a `->reset()` method which would clear the store. It looks that we need that.

I think you need a method to remove elements in the store more than a method to clear the store.
However, to do this, you will need a search method that uses partial string matching or regular expressions to identify "the element".

**Comment by s-ohnishi** [comment] 2023-10-04 03:31
There were other things that were needed.
The loading order of both style sheets and JavaScript has meaning.
For some reason, someone may need to load an element they want to add before a specific element.
`spl_autoload_register()` does not allow us to control the order in detail, but it is possible to insert at the beginning as well as append at the end.
We can also remove specific autoload functions with `spl_autoload_unregister()`.
I think we need at least the same level of control.

**Comment by christoferd** [comment] 2023-10-18 14:21
Just some ideas...

`$this->tag->meta()` is probably creating a new instance every time.

Is that method supposed to check if an instance already exists and is attached?

`$this->tag` does this always reference the same instance?

**Comment by s-ohnishi** [comment] 2023-10-19 16:30
> $this->tag->meta() is probably creating a new instance every time.

It does not create a new instance.
However, as already pointed out, when returning the instance, the registered data is cleared before returning it, so it is almost the same as a new instance.


> Is that method supposed to check if an instance already exists and is attached?

yes. Returns an instance that already exists (registered as a service).


> $this->tag does this always reference the same instance?

yes. I think it's returning an instance of the same TagFactory.

I think the first step to solving the problem is to avoid clearing the registered data when returning the instance.

**Comment by niden** [comment] 2023-10-24 19:08
Resolved in https://github.com/phalcon/cphalcon/pull/16455

Added a `reset()` method and removed the clearing of the internal store on `__invoke()`. 

At the moment manipulation of entries (remove for instance) is not feasible since they do not have a unique name. That could be a NFR for the future.

**Closed by niden** 2023-10-24 19:08 UTC
Labels: bug, status: medium, 5.0
