### ISSUE TITLE
$this->tag->getTitle() return Array when using prependTitle

### ISSUE THREAD

**Issue by fesiong** [phalcon/cphalcon#13039] opened 2017-08-27 03:50 UTC
when I use prependTitle to prepend title, it return back Array.

```html
<title>Array - 明泽网络</title>
```

```php
$this->tag->prependTitle($article->title);
```
### Details

* Phalcon version: (3.2.2)
* PHP Version: (7.1.4)
* Operating System: Centos
* Installation type: Compiling from source
* Server: Nginx

**Comment by sergeyklay** [comment] 2017-08-31 17:37
```zep
public static function prependTitle(var title) -> void
```

Could you please explain a bit more?

**Comment by sergeyklay** [comment] 2017-10-21 10:46
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Closed by sergeyklay** 2017-10-21 10:46 UTC
Labels: Need information

**Comment by fesiong** [comment] 2018-01-17 07:57
Now nginx returns 502.
php in controller:
`
public function indexAction(){
    $this->tag->prependTitle('topic title');
    $this->tag->setTitle('site name');
}
`
volt in view:
`
<!DOCTYPE html>
<html lang="en">
<head>
{{ get_title() }}
</head>
<body>
<div class="hide" id="page-title">{{ get_title(false) }}</div>
</body>
`
php-fpm error:
`
[17-Jan-2018 15:53:53] WARNING: [pool www] child 56155 exited on signal 6 (SIGABRT - core dumped) after 2553.492746 seconds from start
`
nginx error:
`
2018/01/17 15:52:34 [error] 8732#0: *197 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: www.qinrennew.com, request: "GET /order HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "www.qinrennew.com"
`
core dump:
`
* thread #1, stop reason = signal SIGSTOP
  * frame #0: 0x00000001091737f0 php-fpm`zif_array_reverse + 504
    frame #1: 0x000000010928feae php-fpm`zend_call_function + 1796
    frame #2: 0x000000010a2c7f42 phalcon.so`zephir_call_user_function + 1761
    frame #3: 0x000000010a2cc333 phalcon.so`zephir_call_func_aparams + 204
    frame #4: 0x000000010a2fe53f phalcon.so`zim_Phalcon_Tag_getTitle + 2704
    frame #5: 0x00000001092f28a0 php-fpm`ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER + 345
    frame #6: 0x00000001092db907 php-fpm`execute_ex + 56
    frame #7: 0x00000001092dba73 php-fpm`zend_execute + 295
    frame #8: 0x000000010a2f0dcd phalcon.so`zephir_require_ret + 296
    frame #9: 0x000000010a4129da phalcon.so`zim_Phalcon_Mvc_View_Engine_Volt_render + 1393
    frame #10: 0x000000010928feae php-fpm`zend_call_function + 1796
    frame #11: 0x000000010a2c7f42 phalcon.so`zephir_call_user_function + 1761
    frame #12: 0x000000010a2c7557 phalcon.so`zephir_call_class_method_aparams + 207
    frame #13: 0x000000010a383aa4 phalcon.so`zim_Phalcon_Mvc_View__engineRender + 4879
    frame #14: 0x000000010928feae php-fpm`zend_call_function + 1796
    frame #15: 0x000000010a2c7f42 phalcon.so`zephir_call_user_function + 1761
    frame #16: 0x000000010a2c7557 phalcon.so`zephir_call_class_method_aparams + 207
    frame #17: 0x000000010a386066 phalcon.so`zim_Phalcon_Mvc_View_render + 6074
    frame #18: 0x000000010928feae php-fpm`zend_call_function + 1796
    frame #19: 0x000000010a2c7f42 phalcon.so`zephir_call_user_function + 1761
    frame #20: 0x000000010a2c7557 phalcon.so`zephir_call_class_method_aparams + 207
    frame #21: 0x000000010a33ce83 phalcon.so`zim_Phalcon_Mvc_Application_handle + 11200
    frame #22: 0x00000001092f28a0 php-fpm`ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER + 345
    frame #23: 0x00000001092db907 php-fpm`execute_ex + 56
    frame #24: 0x00000001092dba73 php-fpm`zend_execute + 295
    frame #25: 0x00000001092a0087 php-fpm`zend_execute_scripts + 287
    frame #26: 0x0000000109240992 php-fpm`php_execute_script + 616
    frame #27: 0x0000000109346fdc php-fpm`main + 6966
    frame #28: 0x00007fff96fe8235 libdyld.dylib`start + 1
    frame #29: 0x00007fff96fe8235 libdyld.dylib`start + 1
`


Details
Phalcon version: (3.3.0)
PHP Version: (7.1.13)
Operating System: MacOS 10.12.6
Installation type: Compiling from source
Server: Nginx

**Comment by sergeyklay** [comment] 2018-01-18 14:52
@fesiong Could you please open a new issue with code to reproduce
