### ISSUE TITLE
[NFR]  Load models with relations

### ISSUE THREAD

**Issue by braska** [phalcon/cphalcon#2647] opened 2014-07-27 15:42 UTC
Sometimes ORM generates a lot of requests. To avoid this, you can load the model with relations. Like this:
```php
class Items extends \Phalcon\Mvc\Model {
    protected $_load_with = array(
        'category'
    );
    public function initialize() {
        $this->belongsTo('category_id', 'App\Models\Categories', 'id',
            array('alias' => 'category')
        );
    }
}
```
And when you request a relational model (`(new Items())->category`), it will be already loaded.
It can be implemented using join.
P.S. Sorry for my terrible English.

**Comment by andresgutierrez** [comment] 2015-04-09 20:10
Duplicate of #1117

**Closed by andresgutierrez** 2015-04-09 20:10 UTC
Labels: New Feature Request

**Comment by serroba** [comment] 2015-05-11 02:53
@andresgutierrez I am not quite sure, why this is close. I see the duplication, but is this new feature added to the framework?

If not, and the issue is closed, means this will not be included ever?

**Comment by Green-Cat** [comment] 2015-05-11 10:25
@serroba The issue this is duplicating is still open.

**Comment by MrDutchy** [comment] 2016-11-30 15:24
Not anymore. It's closed now by sergeyklay stating that "Eager Loading is a really bad idea popularized by frameworks that do not care about performance."

I don't agree with him. The competition has it but it looks like the Phalcon team is not going to add this.

I ran into many situations where proper eager loading would lead to substantial **performance gain** if implemented correctly.

**Comment by MrDutchy** [comment] 2016-11-30 16:04
Not anymore. It's closed now by sergeyklay stating that "Eager Loading is a really bad idea popularized by frameworks that do not care about performance."
