### ISSUE TITLE
Route action and controller parameter inconsistencies

### ISSUE THREAD

**Issue by scrnjakovic** [phalcon/cphalcon#13555] opened 2018-10-28 15:58 UTC
```php
$router->add('...', [
    'controller' => 'my_controller' // MyController
    'action' => 'my_action' // my_action
]);
```

**Comment by stamster** [comment] 2018-10-30 10:42
That's why I prefer to use [MicroCollection](https://docs.phalconphp.com/en/3.4/application-micro#routing-handlers-controllers) - define everything manually.

```php
$adminRoutes->get('/deconnexion', 'logout', 'admin_logout');
```

**Comment by scrnjakovic** [comment] 2018-10-30 10:58
@stamster nonetheless, the fact that framework treats those two differently is an issue :)

**Comment by scrnjakovic** [comment] 2018-10-30 14:43
@Ark4ne the two are closely related, so if we use one case for controller, we should stick with it when it comes to the action as well, regardless of the lack of the standard for the action.

Standards exist so that code we write is compatible and predictable. The lack of it doesn't mean we should stop caring. Having controller and action use two completely different cases introduces unexpected behavior, especially since it's not clearly mentioned in the docs.

But I could delete my whole answer and just say **consistency**.

**Comment by niden** [comment] 2018-10-31 17:21
Not going to be fixed/addressed in `3.x` series. Adding this to `4.x`

Thank you @scrnjakovic

**Comment by scrnjakovic** [comment] 2018-10-31 18:45
Nope, thank you @niden.

**Comment by JABirchall** [comment] 2018-11-11 23:15
@scrnjakovic If i get this right you want the framework to call your controller `My_Controller`
Unfortunatly I this will be possible, even in 4.x as 4.0 is aiming to be full PSR compliant, and class named `My_Controller` will violate PSR-0, PSR-1, PSR-2, PSR-4 and PSR-12 you can't use underscores in Namespaces or classnames.

**Comment by gnumoksha** [comment] 2018-11-27 15:22
@JABirchall as @scrnjakovic said, the problem is the different behaviour. `my_controller` will be mapped to `MyController` and `my_action` will be mapped to a controller's method named `my_action`. Since @Ark4ne already pointed out the PSR guidelines for the class name, the most reasonable is to change the way Phalcon maps the action name.

**Comment by niden** [comment] 2019-02-06 00:10
Resolved

**Closed by niden** 2019-02-06 00:10 UTC
Labels: Bug - Medium
