### ISSUE TITLE
Phalcon store data in database in Windows-1252.

### ISSUE THREAD

**Issue by divined** [phalcon/cphalcon#3177] opened 2014-12-31 14:55 UTC
Why? And how to change?

All tables are utf8_general_ci

**Comment by sergeyklay** [comment] 2015-01-02 21:44
Try `options` param in database config:

```php
<?php

return new \Phalcon\Config([
   //...,
    'database' => [
        'adapter'  => '...',
        'host'     => '...',
        'username' => '...',
        'password' => '...',
        'dbname'   => '...',
        'options'  => [
            PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES 'UTF8'",
        ]
    ]
]);
```

**Comment by divined** [comment] 2015-01-03 16:16
not working

**Comment by sergeyklay** [comment] 2015-01-04 01:47
How do you determine that exactly Phalcon stores data in Windows-1252 encoding?

**Comment by divined** [comment] 2015-01-04 13:05
Yes, this is working production web server. All frameworks work fine.

**Comment by olivier-monaco** [comment] 2015-01-08 23:13
I think Ð”Ð¾ÑÑ‚ÑƒÐ¿ Ðº Ð°Ð´Ð¼Ð¸Ð½Ð¸ÑÑ‚Ñ€Ð°Ñ‚Ð¸Ð²Ð½Ð¾ is not Windows-1252. It's a russian string encoded with utf-8 but read as a 8-bit charset like Windows-1252.

Can you try with the following string and give me what phpMyAdmin gives you?
<pre>
xxéyyàzz
</pre>

**Comment by divined** [comment] 2015-01-09 08:16
Ð”Ð¾ÑÑ‚ÑƒÐ¿ Ðº Ð°Ð´Ð¼Ð¸Ð½Ð¸ÑÑ‚Ñ€Ð°Ñ‚Ð¸Ð²Ð½Ð¾ - it's w1252 100%
utf8 - show all russian words.

I use Yii and Drupal, both of them use utf8 to store data, and in the phpmyadmin i can read text fine.

xxéyyàzz ??? What i nust to try?

Store thist word from phalcon to db?

**Comment by olivier-monaco** [comment] 2015-01-09 15:18
Let consider the following characters:
<pre>
Ð´Ð¼Ð¸Ð½Ð¸
</pre>

What you see is a set of bytes represented using a charset. A charset is like a filter that take one or more bytes and provides a representation.

Using the CP1252 charset to convet this representation to bytes, give us the following data as hex (see http://en.wikipedia.org/wiki/Windows-1252):
<pre>
d0 b4 d0 bc d0 b8 d0 bd d0 b8
</pre>

The first byte, d0, is a special codepoint for a 2 bytes utf-8 character. See http://en.wikipedia.org/wiki/UTF-8#Description. So, you must use the Cyrillic table (http://en.wikipedia.org/wiki/Cyrillic_(Unicode_block)) to represent this data as UTF-8.

As a result, the same data, but using the UTF-8 charset has the following representation:
<pre>
дмини
</pre>

But why phpMyAdmin show you "Ð´Ð¼Ð¸Ð½Ð¸"?

One possible reason is a "double encoded" string. Example:

You receive data from a web form, let's say "дмини". You think it's a CP1252 encoded string so you use utf8_encode to convert it before sending to the database. But, it was already encoded as UTF-8 and now it's a "double encoded" UTF-8 string...

Remember, a charset is just a filter over a set of bytes. Using a charset does not change the data be using functions like utf8_encode, utf8_decode ou iconv change the data.

Using utf8_encode over:
<pre>
d0 b4 d0 bc d0 b8 d0 bd d0 b8
</pre>

gives you:
<pre>
C3 90 C2 B4 C3 90 C2 BC C3 90 C2 B8 C3 90 C2 BD C3 90 C2 B8
</pre>

And if you use the UTF-8 charset over this data, you see "Ð´Ð¼Ð¸Ð½Ð¸".

So, what to do?

Create a table like:
<pre>
CREATE TABLE `toto` (
	`id` INT(11) NULL DEFAULT NULL,
	`text` VARCHAR(256) NULL DEFAULT NULL
) ENGINE=InnoDB COLLATE='utf8_general_ci';
</pre>

And execute this code:
<pre>
		$config = array(
		    "host" => "...",
		    "username" => "...",
		    "password" => "...",
		    "dbname" => "...",
			    "options" => array(
			        \PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES UTF8",
			    )
		);

		// Create a connection
		$connection = new \Phalcon\Db\Adapter\Pdo\Mysql($config);


		$sql = 'insert into toto (id, text) values (:id, :text)';
		$connection->execute($sql, array('id' => 1, 'text' => 'дмини'));
		$connection->execute($sql, array('id' => 2, 'text' => utf8_encode('дмини')));
</pre>

You must see one entry with "дмини" (id 1) and one with "Ð´Ð¼Ð¸Ð½Ð¸" (id 2).

Now, you can try to read data from yourdatabase using Phalcon and use the following function to see what is the data:
<pre>
function str2hex($text) {
	$hex = '';
	for ($i = 0; $i &lt; strlen($text); ++$i) {
		$c = $text[$i];
		$hex .= dechex(ord($c)).' ';
	}
	return $hex;
}
</pre>

I hope this help.

**Comment by sergeyklay** [comment] 2015-01-09 15:41
@olivier-monaco :+1:

**Comment by divined** [comment] 2015-01-09 16:02
olivier-monaco, ok? i understand what happaends.

Now. When create the model object:

<pre>
$sMenu = new Menus();
$sMenu->name = $menuName;
$sMenu->label = $menu['label'];
$sMenu->description = $menu['description'];
$sMenu->save();

where $menuName and $menu = $_post variables.
</pre>

What i must do to avoid double encoding?

**Comment by olivier-monaco** [comment] 2015-01-09 16:11
Can you use the str2hex function over data from $_POST. Eg.

<pre>
foreach ($_POST as $name => $value) {
    echo $name.' => '.var_export(str2hex($value), true).'<br/>'.PHP_EOL;
}
</pre>

**Comment by olivier-monaco** [comment] 2015-01-09 16:18
Do you store all your PHP files as UTF-8 encoded?

**Comment by divined** [comment] 2015-01-09 16:34
Yes? all files are utf8

**Comment by divined** [comment] 2015-01-09 16:35
Can you use the str2hex function over data from $_POST. Eg.

w8 a min

**Comment by divined** [comment] 2015-01-09 16:39
<pre>
main-menu => 'd093d0bbd0b0d0b2d0bdd0bed0b520d0bcd0b5d0bdd18e' 
management-menu => 'd0a3d0bfd180d0b0d0b2d0bbd0b5d0bdd0b8d0b5' 
user-menu => d09fd0bed0bbd18cd0b7d0bed0b2d0b0d182d0b5d0bbd18cd181d0bad0bed0b520d0bcd0b5d0bdd18e'
</pre>

**Comment by olivier-monaco** [comment] 2015-01-09 18:13
Can you provide the "create table" statement of your SQL table?

**Comment by olivier-monaco** [comment] 2015-01-09 18:36
No... I don't need you table structure, it's not a transcoding problem... ;)

The problem is before storing the data.

Can you run this code and give me the output?
<pre>
var_dump($this->db->fetchAll('show variables like "%character_set%";'));
</pre>

**Comment by divined** [comment] 2015-01-09 21:59
<pre>
array(8) {   
[0]=>   array(4) {     
["Variable_name"]=>     string(20) "character_set_client"     
[0]=>     string(20) "character_set_client"     
["Value"]=>     string(6) "latin1"     
[1]=>     string(6) "latin1"   }   

[1]=>   array(4) {     
["Variable_name"]=>     string(24) "character_set_connection"    
[0]=>     string(24) "character_set_connection"     
["Value"]=>     string(6) "latin1"     
[1]=>     string(6) "latin1"   }   

[2]=>   array(4) {     
["Variable_name"]=>     string(22) "character_set_database"     
[0]=>     string(22) "character_set_database"     
["Value"]=>     string(4) "utf8"     
[1]=>     string(4) "utf8"   }   

[3]=>   array(4) {     
["Variable_name"]=>     string(24) "character_set_filesystem"     
[0]=>     string(24) "character_set_filesystem"     
["Value"]=>     string(6) "binary"     
[1]=>     string(6) "binary"   }   

[4]=>   array(4) {     
["Variable_name"]=>     string(21) "character_set_results"     
[0]=>     string(21) "character_set_results"     
["Value"]=>     string(6) "latin1"     
[1]=>     string(6) "latin1"   }   

[5]=>   array(4) {     
["Variable_name"]=>     string(20) "character_set_server"     
[0]=>     string(20) "character_set_server"     
["Value"]=>     string(4) "utf8"     
[1]=>     string(4) "utf8"   }   

[6]=>   array(4) {     
["Variable_name"]=>     string(20) "character_set_system"     
[0]=>     string(20) "character_set_system"     
["Value"]=>     string(4) "utf8"     
[1]=>     string(4) "utf8"   }   

[7]=>   array(4) {     ["Variable_name"]=>     string(18) "character_sets_dir"     
[0]=>     string(18) "character_sets_dir"     
["Value"]=>     string(26) "/usr/share/mysql/charsets/"     
[1]=>     string(26) "/usr/share/mysql/charsets/"   } }        
</pre>

**Comment by olivier-monaco** [comment] 2015-01-09 22:06
character_set_connection => latin1

You connexion with MySQL is not using UTF-8. This is your problem.

As sergeyklay said, you must add:
<pre>
        'options'  => [
            PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES 'UTF8'",
        ]
</pre>

**Comment by divined** [comment] 2015-01-09 22:09
no, u write:
<pre>
$config = array(
            "host" => "...",
            "username" => "...",
            "password" => "...",
            "dbname" => "...",
                "options" => array(
                    \PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES UTF8",
                )
        );
</pre>

**Comment by divined** [comment] 2015-01-09 22:13
<pre>
return new \Phalcon\Config(array(
    'database' => array(
        'adapter'     => 'Mysql',
        'host'        => 'localhost',
        'username'    => 'phalcon',
        'password'    => '***',
        'dbname'      => 'phalcon',
        'options'  => [
            PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES 'UTF8'",
        ]
    ),
    ....
</pre>
array(8) { 
	[0]=> array(4) { 
		["Variable_name"]=> string(20) "character_set_client" 
		[0]=> string(20) "character_set_client" 
		["Value"]=> string(6) "latin1" 
		[1]=> string(6) "latin1" 
	} 
	
	[1]=> array(4) { 
		["Variable_name"]=> string(24) "character_set_connection" 
		[0]=> string(24) "character_set_connection" 
		["Value"]=> string(6) "latin1" 
		[1]=> string(6) "latin1" 
	} 
	
	[2]=> array(4) { 
		["Variable_name"]=> string(22) "character_set_database" 
		[0]=> string(22) "character_set_database" 
		["Value"]=> string(4) "utf8" 
		[1]=> string(4) "utf8" 
	} 
	
	[3]=> array(4) { 
		["Variable_name"]=> string(24) "character_set_filesystem" 
		[0]=> string(24) "character_set_filesystem" 
		["Value"]=> string(6) "binary" 
		[1]=> string(6) "binary" 
	} 
	
	[4]=> array(4) { 
		["Variable_name"]=> string(21) "character_set_results" 
		[0]=> string(21) "character_set_results" 
		["Value"]=> string(6) "latin1" 
		[1]=> string(6) "latin1" 
	} 
	
	[5]=> array(4) { 
		["Variable_name"]=> string(20) "character_set_server" 
		[0]=> string(20) "character_set_server" 
		["Value"]=> string(4) "utf8" 
		[1]=> string(4) "utf8" 
	} 
	
	[6]=> array(4) { 
		["Variable_name"]=> string(20) "character_set_system" 
		[0]=> string(20) "character_set_system" 
		["Value"]=> string(4) "utf8" 
		[1]=> string(4) "utf8" 
	} 
	
	[7]=> array(4) { 
		["Variable_name"]=> string(18) "character_sets_dir" 
		[0]=> string(18) "character_sets_dir" 
		["Value"]=> string(26) "/usr/share/mysql/charsets/" 
		[1]=> string(26) "/usr/share/mysql/charsets/" 
	} 
} 
<pre>

</pre>

**Comment by divined** [comment] 2015-01-09 22:15
no changes whith options argument

**Comment by divined** [comment] 2015-01-09 22:16
and try:

<pre>
return new \Phalcon\Config(array(
    'database' => array(
        'adapter'     => 'Mysql',
        'host'        => 'localhost',
        'username'    => 'phalcon',
        'password'    => '***',
        'dbname'      => 'phalcon',
        'options'  => array(
              PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES 'UTF8'",
        )
    ),
    ....
</pre>

**Comment by olivier-monaco** [comment] 2015-01-09 22:36
Where do you use this code? I've never used the "adapter" key in config...

My way is to explicitly create the adapter:
<pre>
		// Database
		$di->setShared('db', function() use ($di) {
		    $config = $di->get('config');
		    return new \Phalcon\Db\Adapter\Pdo\Mysql($config->database->toArray());
		});
</pre>

How is created your connection?

**Comment by sergeyklay** [comment] 2015-01-09 22:56
And try to create new db for tests:

```sql
CREATE DATABASE `mydb` COLLATE 'utf8_general_ci';

CREATE TABLE `menus` (
  `id` SERIAL PRIMARY KEY,
  `name` VARCHAR(128) NOT NULL,
  `label` VARCHAR(255) DEFAULT NULL,
  `description` TEXT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**Comment by divined** [comment] 2015-01-09 23:13
no changes

**Comment by divined** [comment] 2015-01-09 23:14
<pre>
$config = include __DIR__ . '/config.php';
$di->set('db', function () use ($config) {
            return new \Phalcon\Db\Adapter\Pdo\Mysql(array(
                'host' => $config->database->host,
                'username' => $config->database->username,
                'password' => $config->database->password,
                'dbname' => $config->database->dbname
            ));
        });
</pre>

**Comment by olivier-monaco** [comment] 2015-01-09 23:17
Here it is! You do not copy the options parameter...

Replace the return by
<pre>
            return new \Phalcon\Db\Adapter\Pdo\Mysql($config->database->toArray());
</pre>

**Comment by divined** [comment] 2015-01-09 23:21
oh, it work )))

how can i miss this (((

**Comment by divined** [comment] 2015-01-09 23:26
thx a lot!!!

**Comment by sergeyklay** [comment] 2015-01-09 23:38
@divined You're Welcome :)

**Comment by olivier-monaco** [comment] 2015-01-10 10:59
Please close the issue.

**Closed** 2015-01-10 13:00 UTC

**Comment by sergeyklay** [comment] 2015-01-16 21:43
@olivier-monaco 

> Where do you use this code? I've never used the "adapter" key in config...

Well, just found it :)

voilà https://github.com/phalcon/phalcon-devtools/blob/master/scripts/Phalcon/Builder/Scaffold.php#L120
